name: symantec-endpoint-protection
pipeline:
  - name: parsed_event
    external:
      name: grok.match
      properties:
        pattern: "%{VIRUS_SCAN_RESULT}|%{AGENT_ACTIVITIES}|%{AGENT_SYSTEM}|%{AGENT_BEHAVIOR}|%{SCAN_RESULT}|%{THREAT_DETECTION}"
        custom_patterns:
          VIRUS_SCAN_RESULT: '%{DATA:reason},IP Address: %{IP:host_ip},Computer name: %{HOSTNAME:host_hostname},Source: %{DATA:source},Risk name: %{DATA:risk_name},Occurrences: %{NUMBER:sightings},File path: %{DATA:file_path},Description: %{DATA:description},Actual action: %{DATA:main_action},Requested action: %{DATA:action},Secondary action: %{DATA:secondary_action},Event time: %{TIMESTAMP_ISO8601:first_seen},Event Insert Time: %{TIMESTAMP_ISO8601:event_insert_time},End Time: %{TIMESTAMP_ISO8601:last_seen},Last update time: %{TIMESTAMP_ISO8601:modification_date},Domain Name: %{DATA:domain_name},Group Name: %{DATA:group_name},Server Name: %{DATA:server_name},User Name: %{DATA:username},Source Computer Name: %{DATA:source_computer_name},Source Computer IP: %{IP:source_computer_ip}?,Disposition: %{DATA:disposition},Download site: %{DATA:url},Web domain: %{DATA:site_domain},Downloaded by: %{DATA:downloaded_by},Prevalence: %{DATA:prevalence},Confidence: %{DATA:confidence},URL Tracking Status: %{DATA:url_tracking},First Seen: %{DATA:discovery_at},Sensitivity: %{DATA:sensitivity},Allowed application reason: %{DATA:application_reason},Application hash: %{BASE16NUM:application_hash},Hash type: %{DATA:application_hash_type},Company name: %{DATA:company_name},Application name: %{DATA:application_name},Application version: %{DATA:application_version},Application type: %{INT:application_type},File size \(bytes\): %{INT:file_size},Category set: %{DATA:rule_category},Category type: %{DATA:rule_type},Location: %{DATA:location},Intensive Protection Level: %{NUMBER:protection_level},Certificate issuer: %{DATA:cert_issuer},Certificate signer: %{DATA:cert_signer},Certificate thumbprint: %{DATA:cert_thumbprint},Signing timestamp: %{NUMBER:cert_timestamp}?,Certificate serial number: %{BASE16NUM:cert_serial_number}?'
          AGENT_ACTIVITIES: "Site: %{DATA:site_name},Server Name: %{DATA:server_name},Domain Name: %{DATA:domain_name},%{DATA:reason},%{DATA:host_hostname},%{DATA:username},%{HOSTNAME:host_name}"
          AGENT_SYSTEM: '%{HOSTNAME:host_hostname},Category: %{NUMBER:event_category},%{DATA:source},\"?Event Description: %{DATA:reason}\"?,Event time: %{TIMESTAMP_ISO8601:start_date},Group Name: %{GREEDYDATA:group_name}'
          AGENT_BEHAVIOR: '%{HOSTNAME:host_hostname},%{IP:host_ip}?,%{DATA:action},%{DATA:action_object},%{DATA:api_name}?,Begin: %{TIMESTAMP_ISO8601:start_date},End Time: %{TIMESTAMP_ISO8601:end_date},Rule: %{DATA:rule_name}?,%{NUMBER:process_id}?,%{DATA:process_path}?,%{NUMBER:return_code},%{DATA:module_name}?,%{DATA:process_params}?,User Name: %{DATA:username}?,Domain Name: %{DATA:domain_name}?,Action Type: %{NUMBER:action_type}?,File size \(bytes\): %{NUMBER:file_size}?,Device ID:( %{DATA:device_id})?'
          SCAN_RESULT: 'Scan ID: %{NUMBER:scan_id},Begin: %{DATA:start_date},End Time: %{DATA:end_date},%{DATA:scan_status}?,Duration \(seconds\): %{NUMBER:scan_duration}?,User1: %{DATA:username},User2: %{DATA},%{DATA:reason},%{DATA:result},Command: %{DATA:scan_command},Threats: %{NUMBER:detected_threats},Infected: %{NUMBER:detected_infections},Total files: %{NUMBER:total_files},Omitted: %{NUMBER:omitted_files},Computer: %{DATA:host_hostname},IP Address: %{IP:host_ip},Domain Name: %{DATA:domain_name},Group Name: %{DATA:group_name},Server Name: %{DATA:server_name},Scan Type: %{DATA:scan_type}'
          THREAT_DETECTION: "%{HOSTNAME:host_hostname},Event Description: \\[SID(\\s|\u00a0)?: %{NUMBER:sig_id}\\] %{DATA:reason},Event Type: %{DATA:event_type}?,Local Host IP: %{IP:host_ip},Local Host MAC: %{DATA:host_mac}?,Remote Host Name: %{HOSTNAME:remote_name}?,Remote Host IP: %{IP:remote_ip},Remote Host MAC: %{DATA:remote_mac}?,%{DATA:direction},%{DATA:transport},,Begin: %{TIMESTAMP_ISO8601:start_date},End Time: %{TIMESTAMP_ISO8601:end_date},Occurrences: %{NUMBER:sightings},Application: %{DATA:application_name},Location: %{DATA},User Name: %{DATA:username},Domain Name: %{DATA:domain_name}?,Local Port: %{NUMBER:source_port},Remote Port: %{NUMBER:remote_port},CIDS Signature ID: %{NUMBER:signature_id},CIDS Signature string: %{DATA:signature_label},CIDS Signature SubID: %{NUMBER:signature_subid},Intrusion URL: %{DATA:intrusion_url},Intrusion Payload URL: %{DATA:intrusion_payload_url}?,SHA-256: %{DATA:intrusion_payload_SHA256},MD-5: %{DATA:intrusion_payload_MD5}?,Intensive Protection Level: %{DATA:protection_level},URL Risk: %{DATA:url_risk},URL Category: %{DATA:url_category}"
  - name: set_timestamp_field
  - name: set_ecs_fields
  - name: set_broadcom_fields

stages:
  set_timestamp_field:
    actions:
      - set:
          # For events with starting date
          "@timestamp": "{{parsed_event.message.start_date | to_rfc3339}}"
        filter: "{{parsed_event.message.start_date not in [null, '']}}"
      - set:
          # For events with ending date (the event is emitted at the ending date)
          "@timestamp": "{{parsed_event.message.end_date | to_rfc3339}}"
        filter: "{{parsed_event.message.end_date not in [null, '']}}"
      - set:
          # For events with modification date (the event is emitted at the modification date)
          "@timestamp": "{{parsed_event.message.modification_date | to_rfc3339}}"
        filter: "{{parsed_event.message.modification_date not in [null, '']}}"
  set_ecs_fields:
    actions:
      - set:
          observer.vendor: "Broadcom"
          observer.product: "Symantec Endpoint Protection"
          event.category: ["process"]
          event.reason: "{{parsed_event.message.reason}}"
          event.action: "{{parsed_event.message.action}}"
          event.start: "{{parsed_event.message.start_date | to_rfc3339}}"
          host.hostname: "{{parsed_event.message.host_hostname}}"
          host.name: "{{parsed_event.message.host_name}}"
          file.path: "{{parsed_event.message.file_path}}"
          file.size: "{{parsed_event.message.file_size}}"
          process.pid: "{{parsed_event.message.process_id}}"
          process.executable: "{{parsed_event.message.process_path}}"
          process.name: "{{parsed_event.message.process_path | basename}}"
          process.working_directory: "{{parsed_event.message.process_path | dirname}}"
          destination.domain: "{{parsed_event.message.remote_name}}"
          destination.ip: "{{parsed_event.message.remote_ip}}"
          destination.port: "{{parsed_event.message.remote_port}}"
          url.original: "{{parsed_event.message.intrusion_url}}"
          file.hash.md5: "{{parsed_event.message.intrusion.payload_md5}}"
          file.hash.sha256: "{{parsed_event.message.intrusion.payload_sha256}}"

      - set:
          event.end: "{{parsed_event.message.end_date | to_rfc3339}}"
        filter: "{{parsed_event.message.end_date not in [null, '']}}"

      - set:
          host.ip: "{{parsed_event.message.host_ip}}"
        filter: "{{parsed_event.message.host_ip | is_ipaddress}}"

      - set:
          network.direction: "{{parsed_event.message.direction | lower}}"
        filter: "{{parsed_event.message.get('direction') != None}}"
      - set:
          network.transport: "{{parsed_event.message.transport | lower}}"
        filter: "{{parsed_event.message.get('transport') != None}}"

      - set:
          source.ip: "{{parsed_event.message.host_ip}}"
        filter: "{{parsed_event.message.host_ip | is_ipaddress}}"

      - set:
          source.port: "{{parsed_event.message.source_port}}"
        filter: "{{parsed_event.message.get('source_port') != None}}"

      - set:
          user.name: "{{parsed_event.message.username}}"
        filter: "{{parsed_event.message.get('username') != None and parsed_event.message.username != 'Aucun(e)' and parsed_event.message.username.lower() != 'none'}}"
      - set:
          host.mac: "{{parsed_event.message.host_mac}}"
        filter: "{{parsed_event.message.get('host_mac') != None and parsed_event.message.host_mac != '000000000000'}}"
      - set:
          destination.mac: "{{parsed_event.message.remote_mac}}"
        filter: "{{parsed_event.message.get('remote_mac') != None and parsed_event.message.remote_mac != '000000000000'}}"
      - set:
          event.reason: "{{parsed_event.message.action_object}}"
        filter: "{{parsed_event.message.get('api_name') == 'Système' and parsed_event.message.action == 'Continue'}}"
      - translate:
        dictionary:
          "Blocked": ["denied"]
        mapping:
          event.action: event.type
        fallback: ["info"]
      - set:
          process.args: '["{{parsed_event.message.process_params}}"]'
        filter: "{{parsed_event.message.get('process_params') != None and parsed_event.message.get('process_params') != 'Aucun(e)'}}"
      - set:
          event.category: ["malware"]
        filter: "{{'Virus' in parsed_event.message.get('reason') or parsed_event.message.get('scan_id') != None}}"
      - set:
          event.category: ["intrusion_detection"]
        filter: "{{parsed_event.message.get('signature_id') != None}}"
      - set:
          event.category: ["network"]
        filter: "{{parsed_event.message.get('source') == 'REP' or 'downloaded' in parsed_event.message.get('reason')}}"
      - set:
          threat.enrichments: >
            [{
              "indicator": {
                "type": "file",
                {% if parsed_event.message.get('first_seen') != None %}"first_seen": "{{parsed_event.message.first_seen | to_rfc3339}}",{% endif %}
                {% if parsed_event.message.get('last_seen') != None %}"last_seen": "{{parsed_event.message.last_seen | to_rfc3339}}",{% endif %}
                {% if parsed_event.message.get('modification_date') != None %}"modified_at": "{{parsed_event.message.modification_date | to_rfc3339}}",{% endif %}
                {% if parsed_event.message.get('sightings') != None %}"sightings": {{parsed_event.message.sightings}},{% endif %}
                {% if parsed_event.message.get('risk_name') != None %}"description": "{{parsed_event.message.risk_name}}",{% endif %}
                {% if parsed_event.message.get('file_path') != None or parsed_event.message.get('file_size') != None %}
                "file": {
                  {% if parsed_event.message.get('file_path') != None %}
                  "path": r"{{parsed_event.message.file_path}}",
                  {% endif %}
                  {% if parsed_event.message.get('file_size') != None %}"size": {{parsed_event.message.file_size}},{% endif %}
                }
                {% endif %}
              }
            }]
        filter: '{{parsed_event.message.get("first_seen") != None or parsed_event.message.get("last_seen") != None or parsed_event.message.get("modification_date") != None or parsed_event.message.get("sightings") != None or parsed_event.message.get("risk_name") != None or parsed_event.message.get("file_path") != None}}'

  set_broadcom_fields:
    actions:
      - set:
          broadcom.endpoint_protection.source: "{{parsed_event.message.source}}"
          broadcom.endpoint_protection.server.domain: "{{parsed_event.message.domain_name}}"
          broadcom.endpoint_protection.server.group: "{{parsed_event.message.group_name}}"
          broadcom.endpoint_protection.server.name: "{{parsed_event.message.server_name}}"
          broadcom.endpoint_protection.application.code_signature.certificate.serial_number: "{{parsed_event.message.cert_serial_number}}"
          broadcom.endpoint_protection.application.code_signature.certificate.thumbprint: "{{parsed_event.message.cert_thumbprint}}"
          broadcom.endpoint_protection.application.code_signature.signer: "{{parsed_event.message.cert_signer}}"
          broadcom.endpoint_protection.application.code_signature.subject_name: "{{parsed_event.message.cert_issuer}}"
          broadcom.endpoint_protection.application.hash.sha2: "{{parsed_event.message.application_hash}}"
          broadcom.endpoint_protection.application.name: "{{parsed_event.message.application_name}}"
          broadcom.endpoint_protection.application.version: "{{parsed_event.message.application_version}}"
          broadcom.endpoint_protection.action.main: "{{parsed_event.message.main_action}}"
          broadcom.endpoint_protection.action.secondary: "{{parsed_event.message.secondary_action}}"
          broadcom.endpoint_protection.prevalence: "{{parsed_event.message.prevalence}}"
          broadcom.endpoint_protection.confidence: "{{parsed_event.message.confidence}}"
          broadcom.endpoint_protection.downloaded_by.file.path: "{{parsed_event.message.downloaded_by}}"
          broadcom.endpoint_protection.threat.type: "{{parsed_event.message.rule_type}}"
          broadcom.endpoint_protection.threat.category: "{{parsed_event.message.rule_category}}"
          broadcom.endpoint_protection.threat.payload: "{{parsed_event.message.intrusion_payload_url}}"
          broadcom.endpoint_protection.scan.id: "{{parsed_event.message.scan_id}}"
          broadcom.endpoint_protection.scan.duration: "{{parsed_event.message.scan_duration}}"
          broadcom.endpoint_protection.scan.command: "{{parsed_event.message.scan_command}}"
          broadcom.endpoint_protection.scan.type: "{{parsed_event.message.scan_type}}"
          broadcom.endpoint_protection.scan.result.threats: "{{parsed_event.message.detected_threats}}"
          broadcom.endpoint_protection.scan.result.infections: "{{parsed_event.message.detected_infections}}"
          broadcom.endpoint_protection.scan.result.total: "{{parsed_event.message.total_files}}"
          broadcom.endpoint_protection.scan.result.omitted: "{{parsed_event.message.omitted_files}}"
          broadcom.endpoint_protection.cids.signature.id: "{{parsed_event.message.signature_id}}"
          broadcom.endpoint_protection.cids.signature.label: "{{parsed_event.message.signature_label}}"
          broadcom.endpoint_protection.cids.signature.sub_id: "{{parsed_event.message.signature_subid}}"
      - set:
          broadcom.endpoint_protection.application.code_signature.timestamp: "{{parsed_event.message.cert_timestamp | to_rfc3339}}"
        filter: '{{parsed_event.message.cert_timestamp != "0"}}'
      - set:
          broadcom.endpoint_protection.scan.status: "{{parsed_event.message.scan_status | lower}}"
        filter: '{{parsed_event.message.get("scan_status") != None}}'
      - set:
          broadcom.endpoint_protection.application.code_signature.digest_algorithm: "{{parsed_event.message.application_hash_type | lower()}}"
        filter: '{{parsed_event.message.get("application_hash_type") != None}}'
      - set:
          broadcom.endpoint_protection.protection.level: "{{parsed_event.message.protection_level}}"
        filter: '{{parsed_event.message.get("protection_level") != None and parsed_event.message.protection_level != "N/A"}}'
      - set:
          broadcom.endpoint_protection.threat.risk: "{{parsed_event.message.url_risk}}"
        filter: '{{parsed_event.message.get("url_risk") != None and parsed_event.message.url_risk != "N/A"}}'
      - set:
          broadcom.endpoint_protection.threat.category: "{{parsed_event.message.url_category}}"
        filter: '{{parsed_event.message.get("url_category") != None and parsed_event.message.url_category != "N/A"}}'
