name: varonis-data-security-saas
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: "alert"
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          event.dataset: "alert"

          observer.vendor: "Varonis"
          observer.product: "DatAdvantage"
          observer.type: "dlp-solution"

      - set:
          "@timestamp": "{{parsed_event.message.generationTime.dateTimeUtc | to_rfc3339}}"
          rule.id: "{{parsed_event.message.policy.id}}"
          rule.name: "{{parsed_event.message.policy.name}}"
          log.level: "{{parsed_event.message.policy.severity}}"

          varonis.datalert.rule.category: "{{parsed_event.message.policy.category}}"
          varonis.datalert.num_events: "{{parsed_event.message.eventsCount}}"
          varonis.datalert.id: "{{parsed_event.message.id}}"
          varonis.datalert.status: "{{parsed_event.message.status}}"
          varonis.datalert.datasource: "{{parsed_event.message.dataSource}}"
