name: Trapster
ignored_values: []
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message
  - name: parsed_time
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.time
        output_field: time
        timezone: "UTC"
  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_time.time}}"
          observer.vendor: "Trapster"
          observer.product: "Trapster"

      - set:
          host.name: "{{parsed_event.message.host}}"
          event.reason: "{{parsed_event.message.event.description}}"
          event.action: "{{parsed_event.message.event.action}}"
          event.start: "{{parsed_event.message.event.start_time | to_rfc3339}}"
          event.end: "{{parsed_event.message.event.end_time | to_rfc3339}}"

      - set:
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          event.kind: "alert"
        filter: "{{parsed_event.message.event.category != 'disconnected'}}"

      - set:
          event.category: ["host"]
          event.type: ["device"]
        filter: "{{parsed_event.message.event.category == 'disconnected'}}"

      - set:
          source.ip: "{{parsed_event.message.event.src_ip}}"
          source.port: "{{parsed_event.message.event.src_port}}"
          source.domain: "{{parsed_event.message.event.src_ip_reverse}}"

      - set:
          destination.ip: "{{parsed_event.message.event.dst_ip}}"
          destination.port: "{{parsed_event.message.event.dst_port}}"

      - set:
          device.id: "{{parsed_event.message.event.device.id}}"
          group.name: "{{parsed_event.message.event.group}}"

      - set:
          ballpoint.trapster.device.template: "{{parsed_event.message.event.device.template}}"
          ballpoint.trapster.device.name: "{{parsed_event.message.event.device.name}}"
          ballpoint.trapster.group: "{{parsed_event.message.event.group}}"
          ballpoint.trapster.channel: "{{parsed_event.message.event.channel}}"
          ballpoint.trapster.category: "{{parsed_event.message.event.category}}"
          ballpoint.trapster.events_count: "{{parsed_event.message.event.events_count}}"
          ballpoint.trapster.acknowledged: "{{parsed_event.message.event.acknowledged}}"
          ballpoint.trapster.extra: "{{parsed_event.message.event.extra}}"
