name: thales_safenet
pipeline:
  - name: deserialize
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: general_value_setter
stages:
  general_value_setter:
    actions:
      - set:
          event.module: 'safenet'
          event.category: 'authentication'
          event.code: '{{deserialize.message.details.actionText}}'
          event.type: '{{deserialize.message.details.type}}'
          event.action: '{{deserialize.message.details.action}}'
          event.reason: '{{deserialize.message.details.message}}'
          user.name: '{{deserialize.message.context.principalId}}'
          source.ip: "{{deserialize.message.context.originatingAddress.replace(\" \", \"\")}}"
          safenet.sourceid: '{{deserialize.message.id}}'
          safenet.tenantid: '{{deserialize.message.context.tenantId}}'
          safenet.globalaccessid: '{{deserialize.message.context.globalAccessId}}'
          safenet.scenario: '{{deserialize.message.context.scenarioName}}'
          safenet.state: '{{deserialize.message.details.state}}'
          safenet.credentials.type: '{{deserialize.message.details.credentials[0].type}}'
          safenet.credentials.state: '{{deserialize.message.details.credentials[0].state}}'
