name: thales_safenet
pipeline:
  - name: deserialize
    description: ''
    filter: ''
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: general_value_setter
    description: ''
    filter: ''
    external: null
stages:
  general_value_setter:
    actions:
      - set:
          event.module: 'safenet'
          event.category: 'authentification'
          event.type: '{{deserialize.message.details.type}}'
          event.action: '{{deserialize.message.details.action}}'
          user.name: '{{deserialize.message.context.principalId}}'


        filter: ''
        name: set
