name: thales_safenet
pipeline:
  - name: deserialize
    description: ''
    filter: ''
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: general_value_setter
    description: '' 
    filter: ''
    external: null
stages:
  general_value_setter:
    actions:
      - set:
          event.module: 'safenet'
          event.category: 'authentification'
          event.code: '{{deserialize.message.details.actionText}}'
          event.type: '{{deserialize.message.details.type}}'
          event.action: '{{deserialize.message.details.action}}'
          event.reason: '{{deserialize.message.details.message}}'
          user.name: '{{deserialize.message.context.principalId}}'
          source.ip: '{{deserialize.message.context.originatingAddress}}'
          safenet.sourceid: '{{deserialize.message.id}}'
          safenet.tenantid: '{{deserialize.message.context.tenantId}}'
          safenet.globalaccessid: '{{deserialize.message.context.globalAccessId}}'
        filter: ''
        name: set
