name: vigidomain
ignored_values: []
pipeline:
  - name: data
    description: ""
    filter: ""
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: raw
  - name: fields
    description: ""
    filter: ""
    external: null
stages:
  fields:
    actions:
      - set:
          event.end: "{{data.raw.dateLastSeen}}"
          event.url: "{{data.raw.url}}"
          log.level: "{{data.raw.severity}}"
          rule.name: "{{data.raw.type}}"
          "@timestamp": "{{data.raw.date}}"
          event.code: "{{data.raw.type}}"
          event.kind: alert
          event.start: "{{data.raw.dateFirstSeen}}"
          event.message: "{{data.raw.description}}"
          rule.category: "{{data.raw.functionality}}"
          event.category: ["configuration"]
          event.type: ["info"]
          event.provider: "{{data.raw.source}}"
          vigidomain.status: "{{data.raw.status}}"
          vigidomain.subject: "{{data.raw.subject}}"
        filter: ""
        name: set
      - set:
          related.ip: "{{data.raw.typoIps}}"
          server.domain: "{{data.raw.subject}}"
          event.category: ["threat"]
          event.type: ["indicator"]
          destination.domain: "{{data.raw.typoDetection}}"
          vigidomain.typosquatting.registrar: "{{data.raw.typoRegistrarName}}"
          vigidomain.typosquatting.name_servers: "{{data.raw.typoNameServers}}"
          vigidomain.typosquatting.has_mx_record: "{{data.raw.typoHasMxRecord}}"
          vigidomain.typosquatting.registered_at: "{{data.raw.typoRegisteredAt}}"
          vigidomain.typosquatting.has_txt_record: "{{data.raw.typoHasTxtRecord}}"
          vigidomain.typosquatting.domain_age_days: "{{data.raw.typoDomainAgeDays}}"
          vigidomain.typosquatting.detection_strategies: "{{data.raw.typoDetectionStrategies}}"
          vigidomain.typosquatting.similarity_percentage: "{{data.raw.typoSimilarityPercentage}}"
        filter: "{{data.raw['type'] == 'TYPOSQUATTING_DOMAIN_DETECTED'}}"
        name: set
