name: Winlogbeat
pipeline:
  - name: json
    external:
      name: json.parse-json
      properties:
        output_field: event
  - name: parse_kv_hashes
    filter: "{{json.event.winlog.event_data.Hashes != null}}"
    external:
      name: kv.parse-kv
      properties:
        input_field: "{{json.event.winlog.event_data.Hashes}}"
        output_field: hash
        value_sep: "="
        item_sep: ","
  - name: fields
stages:
  fields:
    actions:
      - set:
          "@timestamp": '{{json.event["@timestamp"]}}'
          action: "{{json.event.action}}"
          action.properties: "{{json.event.winlog.event_data}}"
          user.target.name: "{{json.event.winlog.event_data.TargetUserName}}"
          user.target.domain: "{{json.event.winlog.event_data.TargetDomainName}}"
          action.id: "{{json.event.event.code | string}}"
          agent: "{{json.event.agent}}"
          as: "{{json_event.event.as}}"
          beat: "{{json.event.beat}}"
          client: "{{json_event.event.client}}"
          cloud: "{{json_event.event.cloud}}"
          cloud.image.id: "{{json_event.event.cloud.image.id}}"
          code_signature: "{{json_event.event.code_signature}}"
          container: "{{json_event.event.container}}"
          data_stream: "{{json_event.event.data_stream}}"
          destination: "{{json.event.destination}}"
          dll: "{{json.event.dll}}"
          dns: "{{json.event.dns}}"
          docker: "{{json_event.event.docker}}"
          error: "{{json.event.error}}"
          event.action: "{{json.event.event.action}}"
          event.category: "{{json.event.event.category}}"
          event.code: "{{json.event.event.code | string}}"
          event.kind: "{{json.event.event.kind}}"
          event.module: "{{json.event.event.module}}"
          event.reason: "{{json.event.event.reason}}"
          event.provider: "{{json.event.event.provider}}"
          event.type: "{{json.event.event.type}}"
          event.original: "{{json.event.message}}"
          action.outcome: "{{json.event.event.outcome}}"
          file: "{{json.event.file}}"
          file.directory: "{{json.event.winlog.event_data.TargetFileName | dirname}}"
          file.name: "{{json.event.winlog.event_data.TargetFileName | basename}}"
          file.path: "{{json.event.winlog.event_data.TargetFileName}}"
          file.extension: "{{json.event.winlog.event_data.TargetFileName.split('.') | last}}"
          file.drive_letter: "{{json.event.winlog.event_data.TargetFileName.split(':') | first}}"
          jolokia: "{{json_event.event.jolokia}}"
          kubernetes: "{{json_event.event.kubernetes}}"
          host: "{{json.event.host}}"
          log: "{{json.event.log}}"
          network: "{{json.event.network}}"
          powershell: "{{json.event.powershell}}"
          process: "{{json.event.process}}"
          process.command_line: "{{json.event.winlog.event_data.CommandLine}}"
          process.executable: "{{json.event.winlog.event_data.Image}}"
          process.name: "{{json.event.winlog.event_data.Image | basename}}"
          process.parent.executable: "{{json.event.winlog.event_data.ParentImage}}"
          process.parent.name: "{{json.event.winlog.event_data.ParentImage| basename}}"
          process.working_directory: "{{json.event.winlog.event_data.CurrentDirectory}}"
          process.pe.original_file_name: "{{json.event.winlog.event_data.OriginalFileName}}"
          registry: "{{json.event.registry}}"
          registry.path: "{{json.event.winlog.event_data.TargetObject}}"
          registry.data.strings: "{{json.event.winlog.event_data.Details}}"
          registry.value: '{{json.event.winlog.event_data.TargetObject.split("\\") | last}}'
          registry.hive: '{{json.event.winlog.event_data.TargetObject.split("\\") | first}}'
          registry.key: '{{json.event.winlog.event_data.TargetObject.split("\\")[:-1] | join("\\")}}'
          source: "{{json.event.source}}"
          sysmon: "{{json.event.sysmon}}"
          timeseries: "{{json_event.event.timeseries}}"
          url: "{{json.event.url}}"
          user: "{{json.event.user}}"
          winlog: "{{json.event.winlog}}"
      - set:
          winlog.provider_guid: "{{json.event.winlog.provider_guid | lower}}"
        filter: '{{json.event.winlog.get("provider_guid") != None}}'
      - set:
          winlog.activity_id: "{{json.event.winlog.activity_id | lower}}"
        filter: '{{json.event.winlog.get("activity_id") != None}}'
      - set:
          process.hash.md5: "{{parse_kv_hashes.hash.MD5}}"
          process.hash.sha1: "{{parse_kv_hashes.hash.SHA1}}"
          process.hash.sha256: "{{parse_kv_hashes.hash.SHA256}}"
          process.hash.sha384: "{{parse_kv_hashes.hash.SHA384}}"
          process.hash.sha512: "{{parse_kv_hashes.hash.SHA512}}"
          process.hash.ssdeep: "{{parse_kv_hashes.hash.SSDEEP}}"
          process.hash.tlsh: "{{parse_kv_hashes.hash.TLSH}}"
          winlog.process.hash: >
            { {%- for (key,value) in parse_kv_hashes.hash.items() -%}
              "{{key | lower}}": "{{value}}",
            {%- endfor -%} }
        filter: "{{parse_kv_hashes.hash != None}}"
