name: forcepoint-ngfw
ignored_values: null
pipeline:
  - name: parsed_event
    filter: '{{original.message.startswith(''LEEF'')}}'
    external:
      name: leef.parse-leef
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: parsed_event
    filter: '{{original.message.startswith(''CEF:'')}}'
    external:
      name: cef.parse-cef
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: parsed_event
    filter: '{{parsed_event is not mapping}}'
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{original.message}}'
        output_field: message
        value_sep: '='
        item_sep: ','
  - name: parsed_msg
    filter: '{{parsed_event.message.msg is defined}}'
    external:
      name: grok.match
      properties:
        input_field: '{{parsed_event.message.msg}}'
        output_field: message
        pattern: >-
          %{COMMAND_HISTORY}|%{DHCP_REPLY}|%{DHCP_REQUEST}|%{VPN_TRIGGER}|%{OTHER}
        custom_patterns:
          OTHER: '%{DATA:reason}'
          DHCP_REPLY: >-
            Message type
            %{WORD:dhcp_type}\.\sXID\:\s0x%{NOTSPACE:xid}\.\sRelay\sip\s%{IP:dhcp_relay_ip}\.\sServer\sID\:\s%{IP:server_id}\.\sDNS\:\s%{IP:dns_ip}\.
          VPN_TRIGGER: >-
            VPN\strigger\sipv[4-6]\(%{IP:source_ip}\)\s\-\>\sipv[4-6]\(%{IP:destination_ip}\)\,\stunnel\s%{GREEDYDATA:tunnel_id}
          DHCP_REQUEST: >-
            Message type
            %{WORD:dhcp_type}\.\sXID\:\s0x%{NOTSPACE:xid}\.\sRelay\sip\s%{IP:dhcp_relay_ip}\.\sRelayed\sto\s%{IP:server_id}(\.\sServer\sID\:\s%{IP:server_id})?\.\sHostname\:\s%{GREEDYDATA:hostname}\.
          COMMAND_HISTORY: >-
            (%{GREEDYDATA:tty}\s)?(HISTORY|history)\:\sPID\\=%{NUMBER:pid}\sUID\\=%{NUMBER:uid}\sUSER\\=%{USERNAME:process_user}\s%{GREEDYDATA:command_line}
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: '{{parsed_event.message.get(''rt'') or parsed_event.message.devTime}}'
        output_field: timestamp
        format: ''
        timezone: UTC
  - name: ecs_observer_mapping
  - name: ecs_event_mapping
  - name: ecs_source_mapping
  - name: ecs_destination_mapping
  - name: ecs_network_mapping
  - name: ecs_user_mapping
  - name: ecs_process_mapping
  - name: ecs_custom_fields
  - name: ecs_authentication_categorization
  - name: ecs_configuration_categorization
  - name: ecs_process_categorization
  - name: ecs_session_categorization
  - name: ecs_file_categorization
  - name: ecs_network_categorization
  - name: ecs_kind_categorization
  - name: ecs_outcome_categorization
    filter: >-
      {{final.event.type != ['info']}}
stages:
  ecs_observer_mapping:
    actions:
      - set:
          observer.type: firewall
          observer.vendor: '{{parsed_event.message.DeviceVendor|lower}}'
          observer.product: '{{parsed_event.message.DeviceProduct}}'
          observer.version: '{{parsed_event.message.DeviceVersion}}'
      - set:
          observer.egress.interface.name: '{{parsed_event.message.deviceOutboundInterface}}'
          observer.ingress.interface.name: '{{parsed_event.message.deviceInboundInterface}}'
      - set:
          observer.hostname: >-
            {{parsed_event.message.sender}}
        filter: '{{not (parsed_event.message.sender|is_ipaddress)}}'
      - set:
          observer.hostname: >-
            {{parsed_event.message.dvchost}}
        filter: '{{final.observer.hostname is not defined and (not (parsed_event.message.dvchost|is_ipaddress))}}'
      - set:
          observer.hostname: >-
            {{parsed_event.message.deviceExternalId}}
        filter: '{{final.observer.hostname is not defined and (not (parsed_event.message.deviceExternalId|is_ipaddress))}}'
      - set:
          observer.ip: >-
            {{parsed_event.message.sender}}
        filter: '{{parsed_event.message.sender|is_ipaddress}}'
      - set:
          observer.ip: '{{parsed_event.message.dvc}}'
        filter: '{{final.observer.ip is not defined and (parsed_event.message.dvc | is_ipaddress)}}'
      - set:
          observer.ip: >-
            {{parsed_event.message.deviceExternalId}}
        filter: '{{final.observer.ip is not defined and (parsed_event.message.deviceExternalId|is_ipaddress)}}'
  ecs_event_mapping:
    actions:
      - set:
          '@timestamp': '{{parsed_date.timestamp}}'
          event.module: '{{parsed_event.message.deviceFacility}}'
          event.reason: '{{parsed_event.message.originalSituation}}'
          event.message: '{{parsed_event.message.msg or parsed_event.message.message}}'
          event.severity: '{{parsed_event.message.sev or parsed_event.message.Severity}}'
      - set:
          event.code: '{{parsed_event.message.DeviceEventClassID}}'
          event.action: '{{parsed_event.message.Name}}'
        filter: '{{parsed_event.message.DeviceEventClassID|int != 0}}'
      - set:
          event.action: '{{parsed_event.message.DeviceEventClassID}}'
        filter: '{{parsed_event.message.DeviceEventClassID|int == 0}}'
  ecs_source_mapping:
    actions:
      - set:
          source.ip: '{{parsed_event.message.src}}'
        filter: '{{parsed_event.message.src | is_ipaddress}}'
      - set:
          source.nat.ip: >-
            {{parsed_event.message.srcPostNAT or
            parsed_event.message.sourceTranslatedAddress}}
        filter: >-
          {{parsed_event.message.srcPostNAT | is_ipaddress or
          parsed_event.message.sourceTranslatedAddress | is_ipaddress}}
      - set:
          source.mac: '{{parsed_event.message.srcMAC}}'
          source.port: '{{parsed_event.message.srcPort or parsed_event.message.spt}}'
          source.nat.port: '{{parsed_event.message.srcPostNATPort}}'
  ecs_destination_mapping:
    actions:
      - set:
          destination.ip: '{{parsed_event.message.dst}}'
        filter: '{{parsed_event.message.dst | is_ipaddress}}'
      - set:
          destination.nat.ip: >-
            {{parsed_event.message.dstPostNAT or
            parsed_event.message.destinationTranslatedAddress}}
        filter: >-
          {{parsed_event.message.srcPostNAT | is_ipaddress or
          parsed_event.message.sourceTranslatedAddress | is_ipaddress}}
      - set:
          destination.port: '{{parsed_event.message.dstPort or parsed_event.message.dpt}}'
          destination.nat.port: '{{parsed_event.message.dstPostNATPort}}'
  ecs_network_mapping:
    actions:
      - set:
          network.protocol: '{{parsed_event.message.proto}}'
        filter: '{{parsed_event.message.proto|int == 0}}'
      - set:
          network.iana_number: '{{parsed_event.message.proto}}'
        filter: '{{parsed_event.message.proto|int != 0}}'
      - set:
          network.application: '{{parsed_event.message.app}}'
      - translate:
        dictionary:
          "1": icmp
          "2": igmp
          "6": tcp
          "17": udp
          "41": ipv6
          "47": gre
          "50": esp
          "51": ah
          "58": ipv6-icmp
          "89": ospf
          "132": sctp
        mapping:
          network.iana_number: network.transport
  ecs_user_mapping:
    actions:
      - set:
          user.name: '{{parsed_event.message.usrName}}'
  ecs_process_mapping:
    actions:
      - set:
          process.pid: '{{parsed_msg.message.pid}}'
          process.user.name: '{{parsed_msg.message.process_user}}'
          process.command_line: '{{parsed_msg.message.command_line}}'
        filter: '{{parsed_msg.message is defined}}'
      - set:
          process.name: >-
            {{parsed_event.message.process or parsed_event.message.processName
            or parsed_event.message.ProcessName}}
          process.user.id: '{{parsed_msg.message.uid}}'
          process.thread.id: >-
            {{parsed_event.message.ThreadID or parsed_event.message.threadID or
            parsed_event.message.process.thread.id}}
  ecs_custom_fields:
    actions:
      - set:
          forcepoint.firewall.action: '{{parsed_event.message.action or parsed_event.message.act}}'
      - set:
          forcepoint.firewall.dhcp.dns: '{{parsed_msg.message.dns_ip}}'
        filter: >-
          {{parsed_msg.message is defined and
          parsed_msg.message.dns_ip|is_ipaddress}}
      - set:
          forcepoint.firewall.dhcp.relay: '{{parsed_msg.message.dhcp_relay_ip}}'
        filter: >-
          {{parsed_msg.message is defined and
          parsed_msg.message.dhcp_relay_ip|is_ipaddress}}
      - set:
          forcepoint.firewall.dhcp.type: '{{parsed_msg.message.dhcp_type}}'
      - set:
          forcepoint.firewall.dhcp.server: '{{parsed_msg.message.server_id}}'
        filter: >-
          {{parsed_msg.message is defined and
          parsed_msg.message.server_id|is_ipaddress}}
      - set:
          forcepoint.firewall.dhcp.hostname: '{{parsed_msg.message.hostname}}'
          forcepoint.firewall.vpn.tunnel_id: '{{parsed_msg.message.tunnel_id}}'
        filter: '{{parsed_msg.message is defined}}'
      - set:
          forcepoint.firewall.rule.id: '{{parsed_event.message.cs1}}'
          forcepoint.firewall.rule.nat_id: '{{parsed_event.message.cs2}}'
  ecs_authentication_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''authentication'']}}'
        filter: >-
          {{'auth' in final.event.action or 'login' in final.event.action or
          'logout' in final.event.action or 'logged in' in
          final.event.action|lower or 'logged out' in final.event.action|lower
          or 'logon' in final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''end'']}}'
        filter: >-
          {{'end' not in final.event.type and 'authentication' in
          final.event.category and 'logout' in final.event.action|lower or
          'done' in final.event.action|lower or ('end' in
          final.event.action|lower and not ('pend' in final.event.action|lower
          or 'send' in final.event.action|lower))}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{'info' not in final.event.type and 'authentication' in
          final.event.category and 'end' not in final.event.type and 'info' in
          final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''start'']}}'
        filter: >-
          {{'start' not in final.event.type and 'authentication' in
          final.event.category and 'end' not in final.event.type and 'info' not
          in final.event.type}}
  ecs_configuration_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''configuration'']}}'
        filter: >-
          {{ 'config' in final.event.action|lower or 'policy' in
          final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''access'']}}'
        filter: >-
          {{'access' not in final.event.type and 'configuration' in
          final.event.category and ('read' in final.event.action|lower or 'view'
          in final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''change'']}}'
        filter: >-
          {{'change' not in final.event.type and 'configuration' in
          final.event.category and ('change' in final.event.action|lower or
          'update' in final.event.action|lower or 'load' in
          final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''creation'']}}'
        filter: >-
          {{'creation' not in final.event.type and 'configuration' in
          final.event.category and ('new' in final.event.action|lower or 'set'
          in final.event.action|lower or 'create' in final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''deletion'']}}'
        filter: >-
          {{'deletion' not in final.event.type and 'configuration' in
          final.event.category and ('delete' in final.event.action|lower or
          'remove' in final.event.action|lower or 'create' in
          final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{final.event.type is not defined and 'configuration' in
          final.event.category}}
  ecs_process_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''process'']}}'
        filter: '{{final.process is defined}}'
      - set:
          event.type: '{{(final.event.type|default([])) + [''access'']}}'
        filter: >-
          {{'access' not in final.event.type and 'process' in
          final.event.category and ('read' in final.event.action|lower or 'view'
          in final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''change'']}}'
        filter: >-
          {{'change' not in final.event.type and 'process' in
          final.event.category and ('update' in final.event.action|lower or
          'edit' in final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''start'']}}'
        filter: >-
          {{'start' not in final.event.type and 'process' in
          final.event.category and ('new' in final.event.action|lower or
          'launch' in final.event.action|lower or 'start' in
          final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''end'']}}'
        filter: >-
          {{'end' not in final.event.type and 'process' in final.event.category
          and ('stop' in final.event.action|lower or 'kill' in
          final.event.action|lower)}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{final.event.type is not defined and 'process' in
          final.event.category}}
  ecs_session_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''session'']}}'
        filter: >-
          {{'session' not in final.event.category and 'session' in
          final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''end'']}}'
        filter: >-
          {{'end' not in final.event.type and 'session' in final.event.category
          and ('close' in final.event.action|lower or ('end' in
          final.event.action|lower and not ('pend' in final.event.action|lower
          or 'send' in final.event.action|lower)))}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{'info' not in final.event.type and 'session' in final.event.category
          and 'info' in final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''start'']}}'
        filter: >-
          {{'start' not in final.event.type and 'session' in
          final.event.category and 'end' not in final.event.type and 'info' not
          in final.event.type}}
  ecs_file_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''file'']}}'
        filter: >-
          {{final.event.category is not defined and "file" in parsed_event.message.deviceFacility|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{'info' not in final.event.type and 'file' in
          final.event.category}}
  ecs_network_categorization:
    actions:
      - set:
          event.category: '{{(final.event.category|default([])) + [''network'']}}'
        filter: >-
          {{final.event.category is not defined and final.observer.type ==
          'firewall'}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''connection'']}}'
        filter: >-
          {{'connection' not in final.event.type and 'network' in
          final.event.category and 'connection' in final.event.action|lower}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''end'']}}'
        filter: >-
          {{'end' not in final.event.type and 'network' in final.event.category
          and ('close' in final.event.action|lower or ('end' in
          final.event.action|lower and not ('pend' in final.event.action|lower
          or 'send' in final.event.action|lower)))}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''start'']}}'
        filter: >-
          {{'start' not in final.event.type and 'network' in
          final.event.category and 'connection' in final.event.type and 'end'
          not in final.event.type and 'info' not in final.event.type}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''allowed'']}}'
        filter: >-
          {{'allowed' not in final.event.type and 'network' in
          final.event.category and (('allow' in final.event.action|lower or
          'permit' in final.event.action|lower) or ('allow' in
          parsed_event.message.action|lower or 'permit' in
          parsed_event.message.action|lower))}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''denied'']}}'
        filter: >-
          {{'denied' not in final.event.type and 'network' in
          final.event.category and (('discard' in final.event.action|lower or
          'block' in final.event.action|lower or 'deny' in
          final.event.action|lower or 'denied' in final.event.action|lower) or
          ('discard' in parsed_event.message.action|lower or 'block' in
          parsed_event.message.action|lower or 'deny' in
          parsed_event.message.action|lower or 'denied' in
          parsed_event.message.action|lower))}}
      - set:
          event.type: '{{(final.event.type|default([])) + [''info'']}}'
        filter: >-
          {{'network' in final.event.category and (final.event.type is not
          defined or ('info' not in final.event.type and 'authentication' in
          final.event.category and 'end' not in final.event.type and 'info' in
          final.event.action|lower))}}
  ecs_kind_categorization:
    actions:
      - set:
          event.kind: alert
        filter: >-
          {{'alert' in final.event.message|lower or 'alert' in
          final.event.action|lower}}
      - set:
          event.kind: event
        filter: '{{final.event.kind is not defined}}'
  ecs_outcome_categorization:
    actions:
      - set:
          event.outcome: failure
        filter: >-
          {{'fail' in final.event.action|lower}}
      - set:
          event.outcome: success
        filter: '{{final.event.outcome is not defined}}'
