repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: check-yaml

  # Prettier formatting check for parser.yml files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: .*/parser\.yml$
        types: [yaml]

  # Run linting checks
  - repo: local
    hooks:
      - id: install-utils
        name: Install utils dependencies
        entry: poetry -C utils install
        language: system
        pass_filenames: false

      - id: linter-check
        name: Run Python linter on changes
        entry: poetry -C utils run python linter.py check --changes
        language: system
        pass_filenames: false
        always_run: true

      - id: check-intake-format
        name: Check Intake Formats
        entry: poetry -C utils run python checks --changes --ignore_event_fieldset_errors --ignore_missing_parsers --ignore_missing_tests --ignore_empty_descriptions
        language: system
        pass_filenames: false

      # Run pytest on changed formats
      - id: pytest-changes
        name: Run pytest on changed formats
        entry: poetry -C utils run pytest test_formats.py --color=yes -vv --changes
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
