repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: check-yaml

  # Prettier formatting check for parser.yml files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        files: .*/parser\.yml$
        types: [yaml]

  # Run linting checks
  - repo: local
    hooks:
      - id: linter-check
        name: Run Python linter on changes
        entry: bash -c 'cd utils && poetry run python linter.py check --changes'
        language: system
        pass_filenames: false
        always_run: true

      # Run pytest on changed formats
      - id: pytest-changes
        name: Run pytest on changed formats
        entry: bash -c 'cd utils && poetry run pytest test_formats.py --color=yes -vv --changes'
        language: system
        pass_filenames: false
        always_run: true
