repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: check-yaml
  - repo: local
    hooks:
      - id: install-utils
        name: Install utils dependencies
        entry: poetry -C utils install
        language: system
        pass_filenames: false

      - id: check-intake-format
        name: Check Intake Formats
        entry: poetry -C utils run python checks --changes --ignore_event_fieldset_errors --ignore_missing_parsers --ignore_missing_tests --ignore_empty_descriptions
        language: system
        pass_filenames: false
