[tools]
node = '24'
python = '3.14'
pipx = "1.11.1"
"pipx:uv" = '0.11.8'
"npm:prettier" = '3.8.3'

[env]
UV_PROJECT = "utils"

[tasks.create-module]
description = "Create a new intake format module"
usage = '''
flag "--overwrite-if-exists" help="Overwrite the format if it already exists"
'''
run = "uv run utils/generate.py new-module ${usage_overwrite_if_exists}"

[tasks.create-format]
description = "Create a new intake format"
usage = '''
arg "<module>" help="Path to the module to create the format in"
flag "--overwrite-if-exists" help="Overwrite the format if it already exists"
'''
run = "uv run utils/generate.py new-format ${usage_module} ${usage_overwrite_if_exists}"

[tasks.create-test]
description = "Create a new test file for a format"
run = "uv run utils/create_test.py"

[tasks.test]
description = "Run tests"
run = "uv run pytest utils/test_formats.py"
