name: cloudflare-gateway-http
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: set_ecs_fields
  - name: set_cloudflare_fields
stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{json_event.message.Datetime}}"
          cloud.account.id: "{{json_event.message.AccountID}}"
          destination.domain: "{{json_event.message.HTTPHost}}"
          destination.port: "{{json_event.message.DestinationPort}}"
          device.id: "{{json_event.message.DeviceID}}"
          event.action: "{{json_event.message.Action}}"
          event.category: ["network"]
          event.dataset: "gateway_http"
          event.type: ["info"]

      - set:
          destination.ip: "{{json_event.message.DestinationIP}}"
        filter: "{{json_event.message.DestinationIP | is_ipaddress}}"

      - set:
          event.type: ["info", "allowed"]
        filter: '{{json_event.message.Action == "allow"}}'
      - set:
          event.type: ["denied"]
        filter: '{{json_event.message.Action == "deny"}}'
      - set:
          file.hash.sha256: "{{json_event.message.BlockedFileHash}}"
        filter: "{{json_event.message.BlockedFileHash | length == 64 }}"
      - set:
          file.name: "{{json_event.message.BlockedFileName}}"
          file.size: "{{json_event.message.BlockedFileSize}}"
          file.type: "{{json_event.message.BlockedFileType}}"
          host.hostname: "{{json_event.message.DeviceName}}"
          http.request.method: "{{json_event.message.HTTPMethod}}"
          http.request.referrer: "{{json_event.message.Referer}}"
          http.response.status_code: "{{json_event.message.HTTPStatusCode}}"
          http.version: "{{json_event.message.HTTPVersion}}"
          network.protocol: "http"
          observer.type: "proxy"
          observer.vendor: "Cloudflare"

      - set:
          source.ip: "{{json_event.message.SourceIP}}"
        filter: "{{json_event.message.SourceIP | is_ipaddress}}"

      - set:
          source.port: "{{json_event.message.SourcePort}}"
          user_agent.original: "{{json_event.UserAgent}}"
          user.id: "{{json_event.message.UserID}}"
          user.email: "{{json_event.message.Email}}"
          url.original: "{{json_event.message.URL}}"

  set_cloudflare_fields:
    actions:
      - set:
          cloudflare.BlockedFileReason: "{{json_event.message.BlockedFileReason}}"
        filter: '{{json_event.message.BlockedFileReason is not in [""]}}'
      - set:
          cloudflare.DownloadedFileNames: "{{json_event.message.DownloadedFileNames}}"
      - set:
          cloudflare.file_list: "{{json_event.message.FileInfo.files}}"
        filter: "{{json_event.message.FileInfo.files != []}}"
      - set:
          cloudflare.InternalSourceIP: "{{json_event.message.InternalSourceIP}}"
        filter: '{{json_event.message.InternalSourceIP is not in [""]}}'
      - set:
          cloudflare.IsIsolated: "{{json_event.message.IsIsolated}}"
      - set:
          cloudflare.PolicyID: "{{json_event.message.PolicyID}}"
        filter: '{{json_event.message.PolicyID is not in [""]}}'
      - set:
          cloudflare.PolicyName: "{{json_event.message.PolicyName}}"
        filter: '{{json_event.message.PolicyName is not in [""]}}'
      - set:
          cloudflare.RequestID: "{{json_event.message.RequestID}}"
        filter: '{{json_event.message.RequestID is not in [""]}}'
      - set:
          cloudflare.UntrustedCertificateAction: "{{json_event.message.UntrustedCertificateAction}}"
        filter: '{{json_event.message.UntrustedCertificateAction is not in [""]}}'
      - set:
          cloudflare.UploadedFileNames: "{{json_event.message.UploadedFileNames}}"
        filter: "{{json_event.message.UploadedFileNames != []}}"
