version: 2.0
uuid: 26d13f8c-3cbc-4def-a958-16019c9ca601
format_uuid: b3aa9d39-7bbe-46fe-bdc8-f91f0d1ce2ac
rule: Slack Audit Logs Application Installed Organization-Wide
description: >-
  An application was extended to every workspace of the organization, gaining access across all of them.
sources: https://docs.slack.dev/reference/audit-logs-api/methods-actions-reference
effort: master
detection:
  selection:
    sekoiaio.intake.dialect_uuid: 'b3aa9d39-7bbe-46fe-bdc8-f91f0d1ce2ac' # Slack Audit Logs
    event.action: 'org_app_upgraded_to_org_install'
  condition: selection
alert_category: policy-violation
alert_type: unauthorized-application
alert_severity: 50
attack:
  - T1528
data_sources:
  - Third-party application logs
similarity_strategy:
  - sekoiaio.entity.uuid
  - user.name
  - slack.audit_logs.entity.id
tags:
  - Slack Audit Logs
changelog:
  - date: 30/09/2026
    level: minor
    change: Initial rule
