version: 2.0
uuid: 2a74252d-87ce-48ce-bcfa-b00b10330e43
format_uuid: b3aa9d39-7bbe-46fe-bdc8-f91f0d1ce2ac
rule: Slack Audit Logs Authentication Settings Changed
description: >-
  The SSO or two-factor authentication setting changed, or an identity provider configuration was modified.
sources: https://docs.slack.dev/reference/audit-logs-api/methods-actions-reference
effort: master
detection:
  selection:
    sekoiaio.intake.dialect_uuid: 'b3aa9d39-7bbe-46fe-bdc8-f91f0d1ce2ac' # Slack Audit Logs
    event.action:
      - 'idp_configuration_added'
      - 'idp_configuration_deleted'
      - 'idp_prod_configuration_updated'
      - 'pref.sso_setting_changed'
      - 'pref.two_factor_auth_changed'
  condition: selection
alert_category: information-content-security
alert_type: unauthorised-information-modification
alert_severity: 60
attack:
  - T1556
data_sources:
  - Third-party application logs
similarity_strategy:
  - sekoiaio.entity.uuid
  - user.name
  - event.action
tags:
  - Slack Audit Logs
changelog:
  - date: 30/09/2026
    level: minor
    change: Initial rule
