name: ibm-aix
pipeline:
  - name: pre_parsing
    external:
      name: grok.match
      properties:
        input_field: "original.message"
        output_field: pre_message
        pattern: '%{DATA:raw_message}'


  - name: parsed_event
    external:
      name: grok.match
      properties:
        input_field: "{{pre_parsing.pre_message.raw_message}}"
        output_field: message
        pattern: '%{FILE_Link}|%{FILE_Unlink}|%{FILE_Rename}|%{FILE_Pipe}|%{FILE_Read}|%{USER_Login}|%{TCP_klisten}|%{TCP_kbind}|%{TCP_kaccept}|%{FS_Chroot}|%{FS_Rmdir}|%{FS_Mkdir}|%{PROC_Execute}|%{PROC_SetUserIDs}|%{PROC_SetGroups}|%{PROC_Kill}|%{PROC_LoadError}|%{PROC_RealGID}|%{PROC_Sysconfig}|%{S_PASSWD_READ}|%{PROC_Adjtime}|%{S_USER_WRITE}|%{SRC_Star_Stop}|%{AUD_It}|%{AUD_Proc}|%{CRON_Start_Finish}'
        custom_patterns:
          AIX_Time: '%{MONTHDAY}\s*%{MONTH}\s*%{YEAR}\s*%{TIME}'
          FILE_Link: '(filename\s*%{DATA:file_name}\s*)?FILE_Link\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No\s*associated\s*roles(\s*linkname\s*%{DATA:file_target_path}\s*filename\s*%{NOTSPACE:file_name})?'
          FILE_Unlink: 'FILE_Unlink\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No\s*associated\s*roles\s*filename\s*%{NOTSPACE:file_name}'
          FILE_Rename: 'FILE_Rename\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*frompath:\s*%{DATA:file_path} topath:%{DATA:file_name}'
          FILE_Read: 'FILE_Read\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*file descriptor = 1635083369 filename =\s*%{NOTSPACE:file_name} object read event detected\s*%{NOTSPACE}'
          FILE_Pipe: 'FILE_Pipe\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*read:\s*%{INT} write:\s*%{INT}'
          USER_Login: '(flags: 80, libpath: , file:\s*%{DATA:file_name} )?USER_Login\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles(\s*user:\s*%{NOTSPACE:user_name} tty:\s*%{NOTSPACE:process_tty})?'
          FS_Chroot: 'FS_Chroot\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*change root directory to:\s*%{NOTSPACE:file_name}'
          FS_Rmdir: 'FS_Rmdir\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*remove of directory:\s*%{NOTSPACE:file_directory}'
          FS_Mkdir: 'FS_Mkdir\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*mode:\s*%{INT} dir:\s*%{NOTSPACE:file_directory}'
          PROC_Execute: 'PROC_Execute\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*euid:\s*%{INT:user_id} egid:\s*%{INT:group_id} epriv:\s*%{BASE16NUM}:%{BASE16NUM} name\s*%{NOTSPACE:process_name}(\s*%{NOTSPACE:file_name})?%{DATA:process_command_line}'
          PROC_Kill: 'PROC_Kill\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*pid:\s*%{NUMBER:process_pid}, sig:\s*%{NUMBER}'
          PROC_LoadError: 'PROC_LoadError\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group} FAIL\s*%{AIX_Time}\s*No associated roles\s*flags: 80, libpath:%{DATA}, file:\s*%{DATA:file_name}%{DATA}'
          PROC_RealGID: 'PROC_RealGID\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*old rgid:\s*%{NUMBER}, new gid:\s*%{NUMBER}, which:%{DATA}'
          PROC_SetUserIDs: 'PROC_SetUserIDs\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*effect:\s*%{NUMBER}, real:\s*%{NUMBER}, saved:\s*%{NUMBER}, login:\s*%{NUMBER}%{DATA}'
          PROC_SetGroups: 'PROC_SetGroups\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*group set:%{DATA}'
          PROC_Sysconfig: 'PROC_Sysconfig\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*%{INT}'
          S_PASSWD_READ: 'S_PASSWD_READ\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*audit object read event detected\s*%{NOTSPACE:file_name}'
          PROC_Adjtime: 'PROC_Adjtime\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*old time:\s*%{AIX_Time}, delta:\s*%{INT}:%{INT}'
          AUD_It: 'AUD_It\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles%{DATA}'
          AUD_Proc: 'AUD_Proc\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*pid:\s*%{NUMBER:process_pid} cmd:\s*%{NUMBER}'
          S_USER_WRITE: 'S_USER_WRITE\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*audit object write event detected\s*%{NOTSPACE:file_name}'
          SRC_Star_Stop: '(SRC_Start|SRC_Stop)\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*%{NOTSPACE:file_name}'
          CRON_Start_Finish: '(CRON_Start|CRON_Finish)\s*%{NOTSPACE:process_name}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*(event = start cron job cmd =\s*%{DATA:process_command_line}|user =\s*%{DATA} pid =\s*%{NUMBER:process_pid}) time = %{DAY} %{MONTH} %{MONTHDAY} %{TIME} %{YEAR}'
          TCP_klisten: 'TCP_klisten\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*%{DATA}'
          TCP_kbind: 'TCP_kbind\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*No associated roles\s*%{BASE16NUM}\s*%{DATA:file_name}'
          TCP_kaccept: 'TCP_kaccept\s*%{NOTSPACE:user_name}\s*%{NOTSPACE:user_group}\s*%{NOTSPACE:process_user_name}\s*%{NOTSPACE:status}\s*%{AIX_Time}\s*(No associated roles|!)\s*%{BASE16NUM} (Port\s*%{IP:source_ip}\s*%{INT:source_port})?%{DATA}'

  - name: set_common_fields
  - name: set_ecs_fields

stages:
  set_common_fields:
    actions:
      - set:
          action.target: "process"
          event.code: '{{pre_parsing.pre_message.message_number_grok}}'
          event.kind: 'event'
          event.category: ['process']
          observer.vendor: 'IBM'
          
  set_ecs_fields:
    actions:
      - set:
          action.status: '{{parsed_event.message.status}}'
          file.name: '{{parsed_event.message.file_name}}'
          file.directory: '{{parsed_event.message.file_directory}}'
          file.path: '{{parsed_event.message.file_path}}'
          file.target_path: '{{parsed_event.message.file_target_path}}'
          group.name: '{{parsed_event.message.user_group}}'
          group.id: '{{parsed_event.message.group_id}}'
          process.name: '{{parsed_event.message.process_name}}'
          process.tty: '{{parsed_event.message.process_tty}}'
          process.pid: '{{parsed_event.message.process_pid}}'
          process.user.name: '{{parsed_event.message.process_user_name}}'
          process.command_line: '{{parsed_event.message.process_command_line}}'
          source.ip:  '{{parsed_event.message.source_ip}}'
          source.port:  '{{parsed_event.message.source_port}}'
          user.name: '{{parsed_event.message.user_name}}'
          user.id: '{{parsed_event.message.user_id}}'