name: umbrella-ip
pipeline:
  - name: parsed_event
    external:
      name: dsv.parse-dsv
      properties:
        columnnames:
          - datetime
          - log_hostname
          - source_ip
          - source_port
          - destination_ip
          - destination_port
          - data
        delimiter: ","
  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": '{{parsed_event.message.datetime.strip('' '').strip(''"'') | to_rfc3339 }}'
          action.name: "block"
          action.outcome: "success"
          action.target: "network-traffic"
          source.ip: "{{parsed_event.message.source_ip}}"
          source.port: "{{parsed_event.message.source_port}}"
          destination.ip: "{{parsed_event.message.destination_ip}}"
          destination.port: "{{parsed_event.message.destination_port}}"
          host.hostname: "{{parsed_event.message.log_hostname}}"
