name: pradeo-mtd
pipeline:
  - name: json_event
    external:
      name: json.parse-json
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: json_event.message.creationDate
        output_field: date
        timezone: "Europe/Paris"
  - name: metadata
  - name: initiator
  - name: permission
  - name: detection
  - name: correlation
  - name: compliance
stages:
  metadata:
    actions:
      - set:
          "@timestamp": "{{parsed_date.date}}"
          "event.action": "{{json_event.message.type}}"
          pradeo.metadata.id: "{{json_event.message.id}}"
          pradeo.metadata.creationDate: "{{json_event.message.creationDate}}"
          pradeo.metadata.source: "{{json_event.message.source}}"
          pradeo.metadata.category: "{{json_event.message.category}}"
          pradeo.metadata.type: "{{json_event.message.type}}"
  initiator:
    actions:
      - filter: '{{json_event.message.source == "device" and json_event.message.device != null}}'
        set:
          pradeo.initiator.id: "{{json_event.message.device.id}}"
          pradeo.initiator.serialNumber: "{{json_event.message.device.serialNumber}}"
          pradeo.initiator.name: "{{json_event.message.device.name}}"
          pradeo.initiator.email: "{{json_event.message.device.email}}"
          pradeo.initiator.imei: "{{json_event.message.device.imei}}"
          pradeo.initiator.byod: "{{json_event.message.device.byod}}"
          pradeo.initiator.declaredOperatingSystem: "{{json_event.message.device.declaredOperatingSystem}}"
          pradeo.initiator.declaredOperatingSystemVersion: "{{json_event.message.device.declaredOperatingSystemVersion}}"
          pradeo.initiator.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.initiator.declaredModel: "{{json_event.message.device.declaredModel}}"
          pradeo.initiator.lastConnection: "{{json_event.message.device.enrollmentStatus.lastConnection}}"
          pradeo.initiator.coupled: "{{json_event.message.device.enrollmentStatus.coupled}}"
          pradeo.initiator.mdmId: "{{json_event.message.device.emmDeviceInfo.externalId}}"
          pradeo.initiator.emm: "{{json_event.message.device.emmDeviceInfo.emm}}"
      - filter: '{{json_event.message.source == "admin" and json_event.message.user != null}}'
        set:
          user.id: "{{json_event.message.user.id}}"
          user.email: "{{json_event.message.user.email}}"
          user.full_name: "{{json_event.message.user.firstName}} {{json_event.message.user.lastName}}"
  permission:
    actions:
      - filter: '{{json_event.message.type == "DevicePermissionStatusUpdated"}}'
        set:
          event.category: ["configuration"]
          event.type: ["change"]
          pradeo.device.id: "{{json_event.message.content.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.device.name}}"
          pradeo.device.email: "{{json_event.message.content.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.device.emmDeviceInfo.emm}}"
          pradeo.permission.name: "{{json_event.message.content.permission}}"
          pradeo.permission.value: "{{json_event.message.content.value}}"
  detection:
    actions:
      - filter: '{{json_event.message.type == "DeviceDetection"}}'
        set:
          event.category: ["process"]
          event.type: ["info"]
          pradeo.device.id: "{{json_event.message.content.id}}"
          pradeo.detection.status: "{{json_event.message.content.metric}}"
          pradeo.detection.value: "{{json_event.message.content.status}}"
      - filter: '{{json_event.message.type == "DeviceSystemStatusRecordUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["change"]
          pradeo.device.id: "{{json_event.message.content.deviceSystemStatusRecord.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.deviceSystemStatusRecord.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.deviceSystemStatusRecord.device.name}}"
          pradeo.device.email: "{{json_event.message.content.deviceSystemStatusRecord.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.deviceSystemStatusRecord.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.deviceSystemStatusRecord.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.deviceSystemStatusRecord.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.deviceSystemStatusRecord.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.deviceSystemStatusRecord.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.deviceSystemStatusRecord.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.deviceSystemStatusRecord.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.deviceSystemStatusRecord.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.deviceSystemStatusRecord.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.deviceSystemStatusRecord.device.emmDeviceInfo.emm}}"
          pradeo.detection.status: "{{json_event.message.content.deviceSystemStatusRecord.deviceSystemStatus.name}}"
          pradeo.detection.value: "{{json_event.message.content.deviceSystemStatusRecord.value}}"
      - filter: '{{json_event.message.type == "DeviceNetworkStatusRecordUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["change"]
          pradeo.device.id: "{{json_event.message.content.deviceNetworkStatusRecord.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.deviceNetworkStatusRecord.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.deviceNetworkStatusRecord.device.name}}"
          pradeo.device.email: "{{json_event.message.content.deviceNetworkStatusRecord.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.deviceNetworkStatusRecord.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.deviceNetworkStatusRecord.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.deviceNetworkStatusRecord.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.deviceNetworkStatusRecord.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.deviceNetworkStatusRecord.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.deviceNetworkStatusRecord.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.deviceNetworkStatusRecord.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.deviceNetworkStatusRecord.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.deviceNetworkStatusRecord.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.deviceNetworkStatusRecord.device.emmDeviceInfo.emm}}"
          pradeo.detection.status: "{{json_event.message.content.deviceNetworkStatusRecord.deviceNetworkStatus.name}}"
          pradeo.detection.value: "{{json_event.message.content.deviceNetworkStatusRecord.value}}"
      - filter: '{{json_event.message.type == "DeviceStatusHistoryUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["info"]
          pradeo.device.id: "{{json_event.message.content.deviceId}}"
          pradeo.detection.status: "{{json_event.message.content.event.kind}}"
          pradeo.detection.value: "{{json_event.message.content.event.value}}"
  correlation:
    actions:
      - filter: '{{json_event.message.type == "DeviceCorrelationUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["info"]
          pradeo.device.id: "{{json_event.message.content.deviceCorrelation.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.deviceCorrelation.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.deviceCorrelation.device.name}}"
          pradeo.device.email: "{{json_event.message.content.deviceCorrelation.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.deviceCorrelation.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.deviceCorrelation.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.deviceCorrelation.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.deviceCorrelation.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.deviceCorrelation.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.deviceCorrelation.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.deviceCorrelation.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.deviceCorrelation.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.deviceCorrelation.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.deviceCorrelation.device.emmDeviceInfo.emm}}"
          pradeo.policy.id: "{{json_event.message.content.deviceCorrelation.detectionPolicy.id}}"
          pradeo.policy.name: "{{json_event.message.content.deviceCorrelation.detectionPolicy.name}}"
          pradeo.correlation.applicationThreatLevel: "{{json_event.message.content.deviceCorrelation.applicationThreatLevel}}"
          pradeo.correlation.networkThreatLevel: "{{json_event.message.content.deviceCorrelation.networkThreatLevel}}"
          pradeo.correlation.systemThreatLevel: "{{json_event.message.content.deviceCorrelation.systemThreatLevel}}"
          pradeo.correlation.matchedSystemStatusLevels: "{{json_event.message.content.deviceCorrelation.matchedSystemStatusLevels}}"
          pradeo.correlation.matchedNetworkStatusLevels: "{{json_event.message.content.deviceCorrelation.matchedNetworkStatusLevels}}"
  compliance:
    actions:
      - filter: '{{json_event.message.type == "DeviceApplicationComplianceUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["change"]
          pradeo.device.id: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.name}}"
          pradeo.device.email: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.device.emmDeviceInfo.emm}}"
          pradeo.compliance.matchedResponseRules: "{{json_event.message.content.deviceApplication.compliance.matchedResponseRules}}"
          pradeo.application.id: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.id}}"
          pradeo.application.package: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.package.package}}"
          pradeo.application.system: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.package.system}}"
          pradeo.application.version: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.version}}"
          pradeo.application.versionCode: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.versionCode}}"
          pradeo.application.name: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.name}}"
          pradeo.application.md5: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.md5}}"
          pradeo.application.sha1: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.sha1}}"
          pradeo.application.sha256: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.application.sha256}}"
          pradeo.detection.status: "{{json_event.message.content.deviceApplicationCompliance.deviceApplication.status}}"
      - filter: '{{json_event.message.type == "DeviceComplianceUpdated"}}'
        set:
          event.category: ["process"]
          event.type: ["change"]
          pradeo.device.id: "{{json_event.message.content.deviceCompliance.device.id}}"
          pradeo.device.serialNumber: "{{json_event.message.content.deviceCompliance.device.serialNumber}}"
          pradeo.device.name: "{{json_event.message.content.deviceCompliance.device.name}}"
          pradeo.device.email: "{{json_event.message.content.deviceCompliance.device.email}}"
          pradeo.device.imei: "{{json_event.message.content.deviceCompliance.device.imei}}"
          pradeo.device.byod: "{{json_event.message.content.deviceCompliance.device.byod}}"
          pradeo.device.declaredOperatingSystem: "{{json_event.message.content.deviceCompliance.device.declaredOperatingSystem}}"
          pradeo.device.declaredOperatingSystemVersion: "{{json_event.message.content.deviceCompliance.device.declaredOperatingSystemVersion}}"
          pradeo.device.declaredOperatingSystemSecurityPatchDate: "{{json_event.message.content.deviceCompliance.device.declaredOperatingSystemSecurityPatchDate}}"
          pradeo.device.declaredModel: "{{json_event.message.content.deviceCompliance.device.declaredModel}}"
          pradeo.device.lastConnection: "{{json_event.message.content.deviceCompliance.device.enrollmentStatus.lastConnection}}"
          pradeo.device.coupled: "{{json_event.message.content.deviceCompliance.device.enrollmentStatus.coupled}}"
          pradeo.device.mdmId: "{{json_event.message.content.deviceCompliance.device.emmDeviceInfo.externalId}}"
          pradeo.device.emm: "{{json_event.message.content.deviceCompliance.device.emmDeviceInfo.emm}}"
          pradeo.compliance.matchedResponseRules: "{{json_event.message.content.deviceCompliance.matchedResponseRules}}"
          pradeo.detection.status: "{{json_event.message.content.deviceCompliance.status}}"
