name: pradeo-mtd
pipeline:
  - name: json_parse
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: base_parser
  - name: custom_parser
stages:
  base_parser:
    actions:
      - set:
          pradeo.type: '{{json_parse.message.type}}'
          pradeo.source: '{{json_parse.message.source}}'
          pradeo.content: '{{json_parse.message.content}}'
          pradeo.category: '{{json_parse.message.category}}'
          pradeo.event.id: '{{json_parse.message.id}}'
          pradeo.device.name: '{{json_parse.message.content.last_name}}'
          pradeo.device.email: '{{json_parse.message.content.email}}'
          pradeo.company.details: '{{json_parse.message.company}}'
          pradeo.application.sha1: '{{json_parse.message.content.application.sha1}}'
          pradeo.device.detection: '{{json_parse.message.content.metric}}'
          pradeo.event.creationDate: '{{json_parse.message.creationDate}}'
          pradeo.application.allowed: '{{json_parse.message.content.allowed}}'
          pradeo.application.package: '{{json_parse.message.content.application.package}}'
          pradeo.application.version: '{{json_parse.message.content.application.version}}'
          pradeo.device.detection.status: '{{json_parse.message.content.event.value}}'
        filter: ''
        name: set
  custom_parser:
    actions:
      - set:
          pradeo.device.id: '{{json_parse.message.content.id}}'
          pradeo.detection.status: '{{json_parse.message.content.status}}'
        filter: '{{base_parser.pradeo.type=="DeviceDetection"}}'
        name: set
      - set:
          pradeo.device.id: '{{json_parse.message.content.device.id}}'
          pradeo.device.info: '{{json_parse.message.content.device}}'
        filter: ''
        name: set
      - set:
          pradeo.device.id: '{{json_parse.message.content.deviceId}}'
        filter: ''
        name: set
      - set:
          pradeo.device.detection: '{{json_parse.message.content.event.kind}}'
        filter: ''
        name: set
      - set:
          pradeo.application.package: '{{json_parse.message.content.application.package.package}}'
        filter: '{{json_parse.message.type=="ApplicationAssociatedToCompany"}}'
        name: set
      - set:
          pradeo.detection.status: '{{json_parse.message.content.event.value}}'
        filter: '{{json_parse.message.type=="DeviceStatusHistoryUpdated"}}'
        name: set
      - set:
          pradeo.device.id: '{{json_parse.message.content.deviceNetworkStatusRecord.device.id}}'
          pradeo.device.name: '{{json_parse.message.content.deviceNetworkStatusRecord.device.name}}'
          pradeo.device.email: >-
            {{json_parse.message.content.deviceNetworkStatusRecord.device.email}}
          pradeo.device.configuration: >-
            {{json_parse.message.content.deviceNetworkStatusRecord.device.configuration}}
        filter: '{{base_parser.pradeo.type=="DeviceNetworkStatusRecordUpdated"}}'
        name: set
      - set:
          pradeo.device.configuration: '{{json_parse.message.content.device.deviceConfiguration}}'
        filter: '{{base_parser.pradeo.type=="DevicePermissionStatusUpdated"}}'
        name: set
      - set:
          pradeo.device.id: '{{json_parse.message.content.deviceSystemStatusRecord.device.id}}'
          pradeo.device.name: '{{json_parse.message.content.deviceSystemStatusRecord.device.name}}'
          pradeo.device.email: '{{json_parse.message.content.deviceSystemStatusRecord.device.email}}'
          pradeo.device.configuration: >-
            {{json_parse.message.content.deviceSystemStatusRecord.device.configuration}}
        filter: '{{base_parser.pradeo.type=="DeviceSystemStatusRecordUpdated"}}'
        name: set
      - set:
          pradeo.device.id: '{{json_parse.message.content.deviceCompliance.device.id}}'
          pradeo.device.name: '{{json_parse.message.content.deviceCompliance.device.email}}'
          pradeo.compliance.status: '{{json_parse.message.content.deviceCompliance.status}}'
        filter: '{{base_parser.pradeo.type=="DeviceComplianceUpdated"}}'
        name: set
      - set:
          pradeo.application.package: '{{json_parse.message.content.application.package.package}}'
        filter: '{{base_parser.pradeo.type=="ApplicationCreated"}}'
        name: set