name: pradeo.mtd-mtd
pipeline:
  - name: json_parse
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: base_parser
  - name: custom_parser
stages:
  base_parser:
    actions:
      - set:
          pradeo.mtd.type: '{{json_parse.message.type}}'
          pradeo.mtd.source: '{{json_parse.message.source}}'
          pradeo.mtd.content: '{{json_parse.message.content}}'
          pradeo.mtd.category: '{{json_parse.message.category}}'
          event.code: '{{json_parse.message.id}}' #done
          user.name: '{{json_parse.message.content.last_name}}' #done
          user.email: '{{json_parse.message.content.email}}' #done
          pradeo.mtd.company.details: '{{json_parse.message.company}}'
          hash.sha1: '{{json_parse.message.content.application.sha1}}' #done
          pradeo.mtd.device.detection: '{{json_parse.message.content.metric}}'
          pradeo.mtd.event.creationDate: '{{json_parse.message.creationDate}}' #done
          pradeo.mtd.application.allowed: '{{json_parse.message.content.allowed}}'
          package.name: '{{json_parse.message.content.application.package}}' #done
          package.version: '{{json_parse.message.content.application.version}}' #done
          pradeo.mtd.device.detection.status: '{{json_parse.message.content.event.value}}'
  custom_parser:
    actions:
      - set:
          device.id: '{{json_parse.message.content.id}}' #done
          pradeo.mtd.detection.status: '{{json_parse.message.content.status}}'
        filter: '{{base_parser.pradeo.mtd.type=="DeviceDetection"}}'
        name: set
      - set:
          device.id: '{{json_parse.message.content.device.id}}' #done
          pradeo.mtd.device.info: '{{json_parse.message.content.device}}'
        filter: ''
        name: set
      - set:
          device.id: '{{json_parse.message.content.deviceId}}' #done
        filter: ''
        name: set
      - set:
          pradeo.mtd.device.detection: '{{json_parse.message.content.event.kind}}'
        filter: ''
        name: set
      - set:
          package.name: '{{json_parse.message.content.application.package.package}}'
        filter: '{{json_parse.message.type=="ApplicationAssociatedToCompany"}}'
        name: set
      - set:
          pradeo.mtd.detection.status: '{{json_parse.message.content.event.value}}'
        filter: '{{json_parse.message.type=="DeviceStatusHistoryUpdated"}}'
        name: set
      - set:
          device.id: '{{json_parse.message.content.deviceNetworkStatusRecord.device.id}}' #done
          user.name: '{{json_parse.message.content.deviceNetworkStatusRecord.device.name}}' #done
          user.email: >- #done
            {{json_parse.message.content.deviceNetworkStatusRecord.device.email}}
          pradeo.mtd.device.configuration: >-
            {{json_parse.message.content.deviceNetworkStatusRecord.device.configuration}}
        filter: '{{base_parser.pradeo.mtd.type=="DeviceNetworkStatusRecordUpdated"}}'
        name: set
      - set:
          pradeo.mtd.device.configuration: '{{json_parse.message.content.device.deviceConfiguration}}'
        filter: '{{base_parser.pradeo.mtd.type=="DevicePermissionStatusUpdated"}}'
        name: set
      - set:
          device.id: '{{json_parse.message.content.deviceSystemStatusRecord.device.id}}' #done
          user.name: '{{json_parse.message.content.deviceSystemStatusRecord.device.name}}' #done
          user.email: '{{json_parse.message.content.deviceSystemStatusRecord.device.email}}' #done
          pradeo.mtd.device.configuration: >-
            {{json_parse.message.content.deviceSystemStatusRecord.device.configuration}}
        filter: '{{base_parser.pradeo.mtd.type=="DeviceSystemStatusRecordUpdated"}}'
        name: set
      - set:
          device.id: '{{json_parse.message.content.deviceCompliance.device.id}}' #done
          user.email: '{{json_parse.message.content.deviceCompliance.device.email}}' #done
          pradeo.mtd.compliance.status: '{{json_parse.message.content.deviceCompliance.status}}'
        filter: '{{base_parser.pradeo.mtd.type=="DeviceComplianceUpdated"}}'
        name: set
      - set:
          package.name: '{{json_parse.message.content.application.package.package}}' #done
        filter: '{{base_parser.pradeo.mtd.type=="ApplicationCreated"}}'
        name: set