#!/usr/bin/env bash
#MISE description="Fix changes"

# Lint tests, smart-descriptions and metadata files
uv run utils/linter.py fix --changes

# Lint parsers & logos
while IFS= read -r -d '' item; do
  case "$item" in
  *ingest/parser.yml)
    npx prettier --write "$item"
    ;;
  *logo.png)
    dest=$(mktemp -d "${TMPDIR:-/tmp/}logo.XXXXXXXXXXXX")
    uv run utils/normalize_image.py normalize_image "$item" "$dest/logo.png"
    mv "$dest/logo.png" "$item"
    ;;
  esac
done < <(git diff --name-only -z)
