#!/usr/bin/env bash
#MISE description="Validate changes"

# Validate tests, smart-descriptions files, metadata
echo "Validate tests, smart-descriptions files and metadata"
uv run utils/linter.py check --changes

# Validate parsers
echo "Validate parser(s)"
while IFS= read -r -d '' parser; do
  case "$parser" in
  *ingest/parser.yml)
    npx prettier --check "$parser"
    ;;
  esac
done < <(git diff --name-only -z)

# Validate the compliance
echo "Check the changes against compliances"
uv run python utils/checks --changes

# Execute the tests against changes
echo "Check the tests"
uv run pytest utils/test_formats.py --changes -vv
