name: FortiProxy
pipeline:
  - name: parsed_event
    external:
      name: kv.parse-kv
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.eventtime
        output_field: timestamp
        format: "timestamp"
  - name: convert_reqtime
    filter: "{{parsed_event.message.reqtime != null}}"
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.reqtime
        output_field: date
        format: timestamp
  - name: convert_resptime
    filter: "{{parsed_event.message.resptime != null}}"
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.resptime
        output_field: date
        format: timestamp
  - name: convert_respfinishtime
    filter: "{{parsed_event.message.respfinishtime != null}}"
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.respfinishtime
        output_field: date
        format: timestamp
  - name: set_fields
stages:
  set_fields:
    actions:
      - set:
          host.name: '{{parsed_event.message.to}}'
        filter: '{{parsed_event.message.get("to") != None}}'

      - set:
          host.name: '{{parsed_event.message.srcname}}'
        filter: '{{parsed_event.message.get("srcname") != None}}'

      - set:
          event.start: '{{parsed_date.timestamp[:-6]}}Z'
          action.name: '{{parsed_event.message.action}}'
          action.type: '{{parsed_event.message.utmaction}}'
          fortinet.vd: '{{parsed_event.message.vd}}'
          fortinet.devid: '{{parsed_event.message.devid}}'
          fortinet.logid: '{{parsed_event.message.logid}}'
          fortinet.sessionid: '{{parsed_event.message.sessionid}}'
          fortinet.srcintfrole: '{{parsed_event.message.srcintfrole}}'
          fortinet.dstintfrole: '{{parsed_event.message.dstintfrole}}'
          host.os.platform: '{{parsed_event.message.devtype}}'
          host.type: '{{parsed_event.message.osname}}'
          fortinet.mastersrcmac: '{{parsed_event.message.mastersrcmac}}'
          fortinet.srcserver: '{{parsed_event.message.srcserver}}'
          fortinet.countapp: '{{parsed_event.message.countapp}}'
          fortinet.policyid: '{{parsed_event.message.policyid}}'
          fortinet.poluuid: '{{parsed_event.message.poluuid}}'
          fortinet.policytype: '{{parsed_event.message.policytype}}'
          fortinet.policymode: '{{parsed_event.message.policymode}}'
          fortinet.level: '{{parsed_event.message.level}}'
          fortinet.trandisp: '{{parsed_event.message.trandisp}}'
          fortinet.utmref: '{{parsed_event.message.utmref}}'
          fortinet.reqtype: '{{parsed_event.message.reqtype}}'
          fortinet.proto: '{{parsed_event.message.proto}}'
          fortinet.appcat: '{{parsed_event.message.appcat}}'
          client.packets: '{{parsed_event.message.sentpkt}}'
          destination.packets: '{{parsed_event.message.rcvdpkt}}'
          event.kind: '{{parsed_event.message.type}}'
          event.category: '{{parsed_event.message.subtype}}'
          event.duration: '{{parsed_event.message.duration}}'
          source.bytes: '{{parsed_event.message.sentbyte}}'
          source.mac: '{{parsed_event.message.srcmac}}'
          source.port: '{{parsed_event.message.srcport}}'
          source.geo.country_name: '{{parsed_event.message.srccountry}}'
          observer.ingress.interface.name: '{{parsed_event.message.srcintf}}'
          observer.egress.interface.name: '{{parsed_event.message.dstintf}}'
          destination.port: '{{parsed_event.message.dstport}}'
          destination.geo.country_name: '{{parsed_event.message.dstcountry}}'
          server.nat.port: '{{parsed_event.message.transport}}'
          service.name: '{{parsed_event.message.service | lower}}'
          destination.bytes: '{{parsed_event.message.rcvdbyte}}'
          fortinet.app: '{{parsed_event.message.app}}'
          fortinet.applist: '{{parsed_event.message.applist}}'
          fortinet.apprisk: '{{parsed_event.message.apprisk}}'
          process.pid: '{{parsed_event.message.appid}}'
          user.name: '{{parsed_event.message.user}}'
          fortinet.group: '{{parsed_event.message.group}}'
          observer.type: proxy
          observer.vendor: Fortinet
          observer.product: FortiProxy
          observer.hostname: '{{parsed_event.message.devname}}'

      - set:
          source.ip: '{{parsed_event.message.srcip}}'
        filter: '{{parsed_event.message.srcip | is_ipaddress }}'

      - set:
          destination.ip: '{{parsed_event.message.dstip}}'
        filter: '{{parsed_event.message.dstip | is_ipaddress }}'

      - set:
          server.nat.ip: '{{parsed_event.message.transip}}'
        filter: '{{parsed_event.message.transip | is_ipaddress }}'


      - set:
          destination.domain: '{{parsed_event.message.dstname}}'
          url.domain: '{{parsed_event.message.dstname}}'
          url.full : '{{parsed_event.message.dstname}}{{parsed_event.message.url}}'
          url.original: '{{parsed_event.message.url}}'
        filter: '{{parsed_event.message.hostname == null}}'
      - set:
          destination.domain: '{{parsed_event.message.hostname}}'
          url.domain: '{{parsed_event.message.hostname}}'
          url.full : '{{parsed_event.message.hostname + parsed_event.message.url}}'
          url.original: '{{parsed_event.message.url}}'
        filter: '{{parsed_event.message.hostname != null and parsed_event.message.subtype != "http-transaction"}}'
      - set:
          destination.domain: '{{parsed_event.message.hostname}}'
          url.domain: '{{parsed_event.message.hostname}}'
          url.full : '{{parsed_event.message.url}}'
          url.original: '{{parsed_event.message.url}}'
        filter: '{{parsed_event.message.hostname != null and parsed_event.message.subtype == "http-transaction"}}'
      - set:
          action.type: '{{parsed_event.message.eventtype}}'
        filter: '{{parsed_event.message.utmaction == null}}'
      - set:
          fortinet.filteridx: '{{parsed_event.message.filteridx}}'
          fortinet.filtername: '{{parsed_event.message.filtername}}'
          fortinet.filtercat: '{{parsed_event.message.filtercat}}'
          fortinet.dlpextra: '{{parsed_event.message.dlpextra}}'
          fortinet.profile: '{{parsed_event.message.profile}}'
          fortinet.filtertype: '{{parsed_event.message.filtertype}}'
          fortinet.eventid: '{{parsed_event.message.eventid}}'
          fortinet.severity: '{{parsed_event.message.severity}}'
          fortinet.fctuid: '{{parsed_event.message.fctuid}}'
          fortinet.forwardedfor: '{{parsed_event.message.forwardedfor}}'
          fortinet.sender: '{{parsed_event.message.sender}}'
          fortinet.subject: '{{parsed_event.message.subject}}'
          fortinet.recipient: '{{parsed_event.message.recipient}}'
          fortinet.trueclntip: '{{parsed_event.message.trueclntip}}'
          fortinet.unauthuser: '{{parsed_event.message.unauthuser}}'
          fortinet.unauthusersource: '{{parsed_event.message.unauthusersource}}'
          fortinet.vrf: '{{parsed_event.message.vrf}}'
          fortinet.direction: '{{parsed_event.message.direction}}'
          fortinet.docsource: '{{parsed_event.message.docsource}}'
          file.type: '{{parsed_event.message.filetype}}'
          user_agent.original: '{{parsed_event.message.agent}}'
          file.name: '{{parsed_event.message.filename}}'
          file.size: '{{parsed_event.message.filesize}}'
          email.from: '{{parsed_event.message.from}}'
          email.to: '{{parsed_event.message.to}}'
        filter: '{{parsed_event.message.eventtype == "dlp"}}'
      - set:
          http.request.bytes: '{{parsed_event.message.reqlength}}'
          http.response.bytes: '{{parsed_event.message.resplength}}'
          http.response.status_code: '{{parsed_event.message.statuscode}}'
          fortinet.resptype: '{{parsed_event.resptype}}'
          fortinet.reqtime: '{{convert_reqtime.date[:-6]}}Z'
          fortinet.resptime: '{{convert_resptime.date[:-6]}}Z'
          fortinet.respfinishtime: '{{convert_respfinishtime.date[:-6]}}Z'
          event.duration: '{{parsed_event.message.duration}}'
        filter: '{{parsed_event.message.subtype == "http-transaction"}}'
      - set:
          fortinet.incidentserialno: '{{parsed_event.message.incidentserialno}}'
          fortinet.direction: '{{parsed_event.message.direction}}'
        filter: '{{parsed_event.message.subtype == "app-ctrl"}}'
      - set:
          fortinet.wanin: '{{parsed_event.message.wanin}}'
          fortinet.wanout: '{{parsed_event.message.wanout}}'
          fortinet.lanin: '{{parsed_event.message.lanint}}'
          fortinet.lanout: '{{parsed_event.message.lanout}}'
          fortinet.collectedemail: '{{parsed_event.message.collectedemail}}'
          fortinet.comment: '{{parsed_event.message.comment}}'
          fortinet.devcategory: '{{parsed_event.message.devcategory}}'
          fortinet.dstcollectedemail: '{{parsed_event.message.dstcollectedemail}}'
          fortinet.dstdevcategory: '{{parsed_event.dstdevcategory}}'
          fortinet.dstdevtype: '{{parsed_event.dstdevtype}}'
          fortinet.dstosname: '{{parsed_event.dstosname}}'
          fortinet.dstosversion: '{{parsed_event.message.dstosversion}}'
          fortinet.dstserver: '{{parsed_event.message.dstserver}}'
          fortinet.dstssid: '{{parsed_event.message.dstssid}}'
          fortinet.dstunauthuser: '{{parsed_event.message.dstunauthuser}}'
          fortinet.dstuuid: '{{parsed_event.message.dstunauthuser}}'
          fortinet.masterdstmac: '{{parsed_event.message.masterdstmac}}'
          fortinet.mastersrcmac: '{{parsed_event.message.mastersrcmac}}'
          fortinet.msg: '{{parsed_event.message.msg}}'
          fortinet.osversion: '{{parsed_event.message.osversion}}'
          fortinet.shaperdroprcvdbyte: '{{parsed_event.message.shaperdroprcvdbyte}}'
          fortinet.shaperdropsentbyte: '{{parsed_event.message.shaperdropsentbyte}}'
          fortinet.shaperperipdropbyte: '{{parsed_event.message.shaperperipdropbyte}}'
          fortinet.shaperperipname: '{{parsed_event.message.shaperperipname}}'
          fortinet.shaperrcvdname: '{{parsed_event.message.shaperrcvdname}}'
          fortinet.shapersentname: '{{parsed_event.message.shapersentname}}'
          fortinet.srcssid: '{{parsed_event.message.srcssid}}'
          fortinet.srcuuid: '{{parsed_event.message.srcuuid}}'
          fortinet.tranip: '{{parsed_event.message.tranip}}'
          fortinet.unauthusersource: '{{parsed_event.message.unauthusersource}}'
          fortinet.vrf: '{{parsed_event.message.vrf}}'
          fortinet.vpn: '{{parsed_event.message.vpn}}'
          fortinet.vpntype: '{{parsed_event.message.vpntype}}'
          fortinet.vwpvlanid: '{{parsed_event.message.vwpvlanid}}'
        filter: '{{parsed_event.message.type == "traffic"}}'
      - set:
          fortinet.msg: '{{parsed_event.message.msg}}'
          fortinet.reason: '{{parsed_event.message.reason}}'
          fortinet.authproto: '{{parsed_event.message.authproto}}'
          fortinet.logdesc: '{{parsed_event.message.logdesc}}'
          fortinet.status: '{{parsed_event.message.status}}'
        filter: '{{parsed_event.message.type == "event"}}'
      - translate:
        dictionary:
          '0': 'hopopt'
          '1': 'icmp'
          '2': 'igmp'
          '3': 'ggp'
          '4': 'ipv4'
          '5': 'st'
          '6': 'tcp'
          '7': 'cbt'
          '8': 'egp'
          '9': 'igp'
          '10': 'bbn-rcc-mon'
          '11': 'nvp-ii'
          '12': 'pup'
          '13': 'argus'
          '14': 'emcon'
          '15': 'xnet'
          '16': 'chaos'
          '17': 'udp'
          '18': 'mux'
          '19': 'dcn-meas'
          '20': 'hmp'
          '21': 'prm'
          '22': 'xns-idp'
          '23': 'trunk-1'
          '24': 'trunk-2'
          '25': 'leaf-1'
          '26': 'leaf-2'
          '27': 'rdp'
          '28': 'irtp'
          '29': 'iso-tp4'
          '30': 'netblt'
          '31': 'mfe-nsp'
          '32': 'merit-inp'
          '33': 'dccp'
          '34': '3pc'
          '35': 'idpr'
          '36': 'xtp'
          '37': 'ddp'
          '38': 'idpr-cmtp'
          '39': 'tp++'
          '40': 'il'
          '41': 'ipv6'
          '42': 'ipv6'
          '43': 'ipv6-route'
          '44': 'ipv6-frag'
          '45': 'idrp'
          '46': 'rsvp'
          '47': 'gre'
          '48': 'dsr'
          '49': 'bna'
          '50': 'esp'
          '51': 'ah'
          '52': 'i-nlsp'
          '53': 'swipe'
          '54': 'narp'
          '55': 'mobile'
          '56': 'tlsp'
          '57': 'skip'
          '58': 'ipv6-icmp'
          '59': 'ipv6-nonxt'
          '60': 'ipv6-opts'
          '62': 'cftp'
          '64': 'sat-expak'
          '65': 'kryptolan'
          '66': 'rvd'
          '67': 'ippc'
          '69': 'sat-mon'
          '70': 'visa'
          '71': 'ipcv'
          '72': 'cpnx'
          '73': 'cphb'
          '74': 'wsn'
          '75': 'pvp'
          '76': 'br-sat-mon'
          '77': 'sun-nd'
          '78': 'wb-mon'
          '79': 'wb-expak'
          '80': 'iso-ip'
          '81': 'vmtp'
          '82': 'secure-vmtp'
          '83': 'vines'
          '84': 'iptm/ttp'
          '85': 'nsfnet-igp'
          '86': 'dgp'
          '87': 'tcf'
          '88': 'eigrp'
          '89': 'ospfigp'
          '90': 'sprite-rpc'
          '91': 'larp'
          '92': 'mtp'
          '93': 'ax.25'
          '94': 'ipip'
          '95': 'micp'
          '96': 'scc-sp'
          '97': 'etherip'
          '98': 'encap'
          '100': 'gmtp'
          '101': 'ifmp'
          '102': 'pnni'
          '103': 'pim'
          '104': 'aris'
          '105': 'scps'
          '106': 'qnx'
          '107': 'a/n'
          '108': 'ipcomp'
          '109': 'snp'
          '110': 'compaq-peer'
          '111': 'ipx-in-ip'
          '112': 'vrrp'
          '113': 'pgm'
          '115': 'l2tp'
          '116': 'ddx'
          '117': 'iatp'
          '118': 'stp'
          '119': 'srp'
          '120': 'uti'
          '121': 'smp'
          '122': 'sm'
          '123': 'ptp'
          '124': 'isis'
          '125': 'fire'
          '126': 'crtp'
          '127': 'crudp'
          '128': 'sscopmce'
          '129': 'iplt'
          '130': 'sps'
          '131': 'pipe'
          '132': 'sctp'
          '133': 'fc'
          '134': 'rsvp-e2e-ignore'
          '135': 'mobility'
          '136': 'udplite'
          '137': 'mpls-in-ip'
          '138': 'manet'
          '139': 'hip'
          '140': 'shim6'
          '141': 'wesp'
          '142': 'roh'
        mapping:
          fortinet.proto: network.protocol
      - translate:
        dictionary:
          'incoming': 'inbound'
          'outgoing': 'outbound'
        mapping:
          fortinet.direction: network.direction
