name: vectra-respond-ux-entity-scoring
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: "message"

  - name: set_ecs_fields

  - name: set_account_fields
    filter: "{{parsed_event.message.type == 'account'}}"

  - name: set_host_fields
    filter: "{{parsed_event.message.type == 'host'}}"

stages:
  set_ecs_fields:
    actions:
      - set:
          observer.vendor: "Vectra"
          observer.product: "Vectra Respond UX"

          event.category: ["configuration"]
          event.type: ["change"]
          event.dataset: "entity_scoring"

      - set:
          "@timestamp": "{{parsed_event.message.event_timestamp | to_rfc3339}}"
          event.reference: "{{parsed_event.message.url}}"

          vectra.entity_scoring.category: "{{parsed_event.message.category}}"
          vectra.entity_scoring.type: "{{parsed_event.message.type}}"
          vectra.entity_scoring.is_prioritized: "{{parsed_event.message.is_prioritized}}"
          vectra.entity_scoring.importance: "{{parsed_event.message.importance}}"
          vectra.entity_scoring.attack_rating: "{{parsed_event.message.attack_rating}}"
          vectra.entity_scoring.last_detection.id: "{{parsed_event.message.last_detection.id}}"
          vectra.entity_scoring.last_detection.type: "{{parsed_event.message.last_detection.type}}"
          vectra.entity_scoring.last_detection.url: "{{parsed_event.message.last_detection.url}}"

  set_account_fields:
    actions:
      - set:
          user.risk.static_score: "{{parsed_event.message.urgency_score}}"
          user.risk.static_level: "{{parsed_event.message.severity}}"

      - set:
          user.name: "{{parsed_event.message.name}}"
        filter: "{{ ':' not in parsed_event.message.name}}"

      - set:
          user.name: "{{parsed_event.message.name.split(':') | last}}"
          vectra.entity_scoring.account.provider: "{{parsed_event.message.name.split(':') | first}}"
        filter: "{{ ':' in parsed_event.message.name}}"

  set_host_fields:
    actions:
      - set:
          host.name: "{{parsed_event.message.name}}"
          host.risk.static_score: "{{parsed_event.message.urgency_score}}"
          host.risk.static_level: "{{parsed_event.message.severity}}"
