name: splunk
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message
  - name: set-common-fields
  - name: set-splunk-fields

stages:
  set-common-fields:
    actions:
      - set:
          event.kind: alert
          observer.product: Splunk
  set-splunk-fields:
    actions:
      - set:
          splunk.app: "{{json_event.message.app}}"
          splunk.sid: "{{json_event.message.sid}}"
          splunk.owner: "{{json_event.message.owner}}"
          splunk.search_name: "{{json_event.message.search_name}}"
          splunk.results_link: "{{json_event.message.results_link}}"
