name: microsoft-defender-xdr-graphapi-incidents
ignored_values: ["none", "unknown"]
pipeline:
  - name: json_event
    external:
      name: json.parse-json

  - name: set_incident_fields
    filter: "{{json_event.message.get('displayName') != None and json_event.message.get('incidentWebUrl') != None}}"

stages:
  set_incident_fields:
    actions:
      - set:
          event.kind: "alert"
          event.category: ["threat"]
          event.type: ["indicator"]
          event.dataset: "incident"
          observer.type: "edr"

          "@timestamp": "{{json_event.message.createdDateTime}}"
          event.reference: "{{json_event.message.incidentWebUrl}}"
          event.reason: "{{json_event.message.displayName}}"

          microsoft.defender.incident.id: "{{json_event.message.id}}"
          microsoft.defender.incident.name: "{{json_event.message.displayName}}"
          microsoft.defender.incident.reference: "{{json_event.message.incidentWebUrl}}"
          microsoft.defender.incident.assignee: "{{json_event.message.assignedTo}}"
          microsoft.defender.incident.tags: "{{json_event.message.customTags}}"
          microsoft.defender.incident.redirect_incident_id: "{{json_event.message.redirectIncidentId}}"

          microsoft.defender.alert.severity: "{{json_event.message.severity}}"
          microsoft.defender.alert.status: "{{json_event.message.status}}"
          microsoft.defender.alert.classification: "{{json_event.message.classification}}"
          microsoft.defender.alert.determination: "{{json_event.message.determination}}"
