version: 2.0
uuid: 09b80858-2b75-40b2-907b-94ee090d2dd5
format_uuid: 3f330d19-fdea-48ac-96bd-91a447bb26bd
rule: Sophos EDR Application Blocked
description: >-
  Sophos EDR detected a potentially malicious application and blocked it.
sources: https://www.sophos.com/en-us/products/endpoint-antivirus/edr
effort: master
detection:
  selection:
    sekoiaio.intake.dialect_uuid: '3f330d19-fdea-48ac-96bd-91a447bb26bd' #SophosEDR dialect
    event.code: 'Event::Endpoint::Application::Blocked'
  condition: selection
alert_category: malicious-code
alert_type: malware
alert_severity: 30
attack:
  - T1204
data_sources:
  - Anti-virus
similarity_strategy:
  - host.name
  - event.reason
event_fields:
  - field: event.code
    description: Sophos EDR detection code
  - field: event.reason
    description: Sophos EDR reason for the detection code
tags:
  - Sophos EDR
changelog:
  - date: 18/03/2026
    level: minor
    change: Update rule type to integration
