name: azure-activity-logs
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_common_fields

  - name: set_administrative
    filter: "{{parsed_event.message.category.value == 'Administrative' or parsed_event.message.category == 'Administrative'}}"

  - name: set_alerts
    filter: "{{parsed_event.message.category.value == 'Alert' or parsed_event.message.category == 'Alert'}}"

  - name: set_security
    filter: "{{parsed_event.message.category.value == 'Security' or parsed_event.message.category == 'Security'}}"

  - name: set_policy
    filter: "{{parsed_event.message.category.value == 'Policy' or parsed_event.message.category == 'Policy'}}"

stages:
  set_common_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_event.message.eventTimestamp}}"
          event.provider: "{{parsed_event.message.resourceProviderName.value}}"
          event.action: "{{parsed_event.message.operationName.value or parsed_event.message.operationName}}"
          event.dataset: "{{parsed_event.message.category.value or parsed_event.message.category}}"
          log.level: "{{parsed_event.message.level}}"
          azure.activity_logs.operation_id: "{{parsed_event.message.operationId}}"
          azure.activity_logs.correlation_id: "{{parsed_event.message.correlationId}}"
          azure.activity_logs.resource.group: "{{parsed_event.message.resourceGroupName}}"
          azure.activity_logs.resource.type: "{{parsed_event.message.resourceType.value}}"
          azure.activity_logs.resource.id: "{{parsed_event.message.resourceId}}"
          azure.activity_logs.channels: "{{parsed_event.message.channels}}"

          observer.name: "{{parsed_event.message.identity.claims.name}}"

  set_administrative:
    actions:
      - set:
          event.category: ["network"]
          event.type: ["info"]

      - set:
          source.user.full_name: "{{parsed_event.message.get('claims', {}).get('name') or parsed_event.message.get('identity', {}).get('claims', {}).get('name')}}"
          source.user.name: "{{parsed_event.message.caller}}"
          source.ip: "{{parsed_event.message.get('claims', {}).get('ipaddr') or parsed_event.message.get('identity', {}).get('claims', {}).get('ipaddr') or parsed_event.message.get('callerIpAddress')}}"
          azure.activity_logs.channels: "{{parsed_event.message.channels}}"
          client.ip: "{{parsed_event.message.httpRequest.clientIpAddress}}"
          http.request.id: "{{parsed_event.message.httpRequest.clientRequestId}}"
          http.request.method: "{{parsed_event.message.httpRequest.method}}"

      - set:
          event.duration: "{{(parsed_event.message.durationMs | int) * 1_000_000}}" # 1 ms = 10 ^ 6 ns
        filter: "{{parsed_event.message.durationMs | int(-1) > 0}}"

  set_alerts:
    actions:
      - set:
          event.kind: "alert"
          event.category: ["network"]
          event.type: ["info"]

      - set:
          event.reason: "{{parsed_event.message.get('description') or parsed_event.message.get('resultDescription')}}"
          source.user.name: "{{parsed_event.message.caller}}"
          azure.activity_logs.id: "{{parsed_event.message.eventDataId}}"
          rule.reference: "{{parsed_event.message.properties.RuleUri}}"
          rule.name: "{{parsed_event.message.properties.RuleName}}"
          rule.description: "{{parsed_event.message.properties.RuleDescription}}"

  set_security:
    actions:
      - set:
          event.category: ["malware"]
          event.type: ["info"]

      - set:
          azure.activity_log.id: "{{parsed_event.message.eventDataId}}"
          event.reason: "{{parsed_event.message.get('description') or parsed_event.message.get('resultDescription')}}"
          rule.reference: "{{parsed_event.message.properties.RuleUri}}"
          rule.name: "{{parsed_event.message.properties.RuleName}}"
          rule.description: "{{parsed_event.message.properties.RuleDescription}}"
          process.command_line: "{{parsed_event.message.properties.commandLine}}"
          process.pid: "{{parsed_event.message.properties.processId}}"
          process.name: "{{parsed_event.message.properties.processName}}"
          process.parent.name: "{{parsed_event.message.properties.parentProcess.name}}"
          process.parent.pid: "{{parsed_event.message.properties.parentProcess.id}}"
          process.user.name: "{{parsed_event.message.properties.userName}}"
          process.user.id: "{{parsed_event.message.properties.userSID}}"
          process.user.domain: "{{parsed_event.message.properties.domainName}}"

  set_policy:
    actions:
      - set:
          event.category: ["network"]
          event.type: ["info"]

      - set:
          source.user.id: "{{parsed_event.message.caller}}"
          event.reason: "{{parsed_event.message.description}}"
          azure.activity_logs.resource.location: "{{parsed_event.message.properties.resourceLocation}}"
          azure.activity_logs.policies: >
            {%- set result = [] -%}
            {%- for item in parsed_event.message.properties.policies | from_json -%}
              {%- set record = {'definition_id': item.get('policyDefinitionId'), 'definition_name': item.get('policyDefinitionName'), 'assignment_id': item.get('policyAssignmentId'), 'assignment_name': item.get('policyAssignmentName') } -%}
              {%- set _ = result.append(record) -%}
            {%- endfor -%}
            {{ result }}
