name: cyberwatch-detection
pipeline:
  - name: parsed_event
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{original.message.replace(''\n'', '''')}}'
        output_field: message
        value_sep: "="
        item_sep: ","

  - name: parsed_fixed_at
    filter: "{{parsed_event.message.fixed_at != null and parsed_event.message.fixed_at != ''}}"
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.fixed_at}}"
        output_field: datetime

  - name: parsed_updated_at
    filter: "{{parsed_event.message.updated_at != null and parsed_event.message.updated_at != ''}}"
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.updated_at}}"
        output_field: datetime

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.category: ["vulnerability"]
          event.type: ["info"]

          observer.vendor: "Cyberwatch"
          observer.type: "scanner"
          observer.product: "cyberwatch"

      - set:
          "@timestamp": "{{parsed_event.message.created_at | to_rfc3339}}"

          event.provider: "{{parsed_event.message.cyberwatch_detection or parsed_event.message.source_node}}"
          cyberwatch.vas.active: "{{parsed_event.message.active}}"
          host.type: "{{parsed_event.message.computer_category or parsed_event.message.asset_category}}"
          cyberwatch.vas.computer.criticality: "{{parsed_event.message.computer_criticality}}"
          device.id: "{{parsed_event.message.computer_id or parsed_event.message.asset_id}}"
          host.id: "{{parsed_event.message.computer_id or parsed_event.message.asset_id}}"
          host.name: "{{parsed_event.message.computer_name or parsed_event.message.asset_name}}"
          host.os.full: "{{parsed_event.message.computer_os}}"
          host.architecture: "{{parsed_event.message.computer_os_arch}}"
          host.os.name: "{{parsed_event.message.computer_os_name}}"

          vulnerability.id: "{{parsed_event.message.cve_code or parsed_event.message.cve}}"
          vulnerability.severity: "{{parsed_event.message.cve_level or parsed_event.message.severity}}"
          vulnerability.description: "{{parsed_event.message.cve_description}}"
          vulnerability.reference: "{{parsed_event.message.cve_url or parsed_event.message.advisory_url}}"

          cyberwatch.vas.cve.published_at: "{{parsed_event.message.cve_published_at | to_rfc3339 }}"

          vulnerability.score.base: "{{parsed_event.message.cve_score}}"
          vulnerability.score.version: "{{parsed_event.message.cvss_version}}"

          cyberwatch.vas.cve.status: "{{parsed_event.message.cve_status}}"
          cyberwatch.vas.cvss.attack_complexity: "{{parsed_event.message.cvss_AC}}"
          cyberwatch.vas.cvss.attack_vector: "{{parsed_event.message.cvss_AV}}"
          cyberwatch.vas.cvss.attack_authentication: "{{parsed_event.message.cvss_Au}}"
          cyberwatch.vas.cvss.availability: "{{parsed_event.message.cvss_A}}"
          cyberwatch.vas.cvss.confidentiality: "{{parsed_event.message.cvss_C}}"
          cyberwatch.vas.cvss.integrity: "{{parsed_event.message.cvss_I}}"
          cyberwatch.vas.epss.score: "{{parsed_event.message.epss}}"
          cyberwatch.vas.exploit.active: "{{parsed_event.message.active_exploit}}"
          cyberwatch.vas.exploit.public: "{{parsed_event.message.public_exploit}}"
          cyberwatch.vas.kev: "{{parsed_event.message.kev or parsed_event.message.is_kev}}"
          cyberwatch.vas.ignored: "{{parsed_event.message.ignored}}"
          cyberwatch.vas.remediation: "{{parsed_event.message.remediation or parsed_event.message.solution}}"

          host.ip: "{{parsed_event.message.ip}}"
          observer.name: "{{parsed_event.message.source_node}}"

      - set:
          vulnerability.enumeration: "CVE"
        filter: "{{(parsed_event.message.cve_code or parsed_event.message.cve) != null}}"

      - set:
          event.end: "{{parsed_fixed_at.datetime}}"
        filter: "{{parsed_event.message.fixed_at != null and parsed_event.message.fixed_at != ''}}"

      - set:
          cyberwatch.vas.fixed_at: "{{parsed_fixed_at.datetime}}"
        filter: "{{parsed_event.message.fixed_at != null and parsed_event.message.fixed_at != ''}}"

      - set:
          cyberwatch.vas.updated_at: "{{parsed_updated_at.datetime}}"
        filter: "{{parsed_event.message.updated_at != null and parsed_event.message.updated_at != ''}}"

      - set:
          cyberwatch.vas.groups: "{{parsed_event.message.groups.split(',')}}"
        filter: "{{parsed_event.message.groups != null and parsed_event.message.groups != ''}}"
