name: beyondtrust-pra-vault-account-activity
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          observer.vendor: "BeyondTrust"
          observer.product: "Privileged Remote Access"
          observer.type: "bastion"
          event.dataset: "Vault Account Activity"

          event.category: ["iam"]
          event.type: ["info"]

      - set:
          "@timestamp": "{{parsed_event.message.timestamp | to_rfc3339}}"
          event.code: "{{parsed_event.message.event_type}}"
          event.reason: "{{parsed_event.message.data}}"

          user.target.id: "{{parsed_event.message.account_id}}"

          user.name: "{{parsed_event.message.performed_by.name}}"
          user.id: "{{parsed_event.message.performed_by.id}}"

      - set:
          beyondtrust.pra.performed_by.type: "{{parsed_event.message.performed_by.type}}"
