name: newrelic-alerts
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: "alert"
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          event.dataset: "newrelic.alerts"

      - set:
          "@timestamp": "{{parsed_event.message.createdAt | to_rfc3339}}"
          event.provider: "{{parsed_event.message.sources}}"
          event.url: "{{parsed_event.message.issueUrl}}"

          log.level: "{{parsed_event.message.priority}}"
          event.reason: "{{parsed_event.message.title}}"

          rule.name: "{{parsed_event.message.alertPolicyNames}}"

          newrelic.alert.id: "{{parsed_event.message.id}}"
          newrelic.alert.conditions: "{{parsed_event.message.alertConditionNames}}"
          newrelic.alert.state: "{{parsed_event.message.state}}"
          newrelic.alert.trigger: "{{parsed_event.message.trigger}}"
          newrelic.alert.total_incidents: "{{parsed_event.message.totalIncidents}}"
          newrelic.alert.is_correlated: "{{parsed_event.message.isCorrelated}}"
          newrelic.alert.impacted_entities: "{{parsed_event.message.impactedEntities}}"