name: trend-micro-vision-one-oat
ignored_values: []
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: set_ecs_fields

  - name: set_custom_fields

  - name: parse_email_date
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.rt_utc}}"
        output_field: datetime
    filter: "{{parsed_event.message.scanType in ['exchange_mailbox_realtime_detection_logs', 'realtime_mailmeta-exchange']}}"

  - name: set_email_fields
    filter: "{{parsed_event.message.scanType in ['exchange_mailbox_realtime_detection_logs', 'realtime_mailmeta-exchange']}}"

stages:
  set_ecs_fields:
    actions:
      - set:
          event.category: ["intrusion_detection"]
          event.type: ["info"]
          observer.vendor: "TrendMicro"

      - set:
          "@timestamp": "{{parsed_event.message.detectedDateTime | to_rfc3339}}"
          action.properties.ScriptBlockText: "{{parsed_event.message.detail.objectRawDataStr}}"
          agent.id: "{{parsed_event.message.endpoint.agentGuid}}"
          cloud.service.name: "{{parsed_event.message.cloudAppName}}"
          destination.as.organization.name: "{{parsed_event.message.detail.dstIsp[0] if parsed_event.message.detail.dstIsp is iterable and parsed_event.message.detail.dstIsp is not string and parsed_event.message.detail.dstIsp | length > 0 else (parsed_event.message.detail.dstIsp if parsed_event.message.detail.dstIsp is string else none)}}"
          destination.domain: "{{parsed_event.message.detail.peerHost or parsed_event.message.detail.cccaDestination or parsed_event.message.detail.denyListHost}}"
          destination.geo.country_name: "{{(parsed_event.message.detail.dstCountry[0] if parsed_event.message.detail.dstCountry is iterable and parsed_event.message.detail.dstCountry is not string and parsed_event.message.detail.dstCountry | length > 0 else (parsed_event.message.detail.dstCountry if parsed_event.message.detail.dstCountry is string else none)) or (parsed_event.message.detail.peerIpCountry[0] if parsed_event.message.detail.peerIpCountry is iterable and parsed_event.message.detail.peerIpCountry is not string and parsed_event.message.detail.peerIpCountry | length > 0 else (parsed_event.message.detail.peerIpCountry if parsed_event.message.detail.peerIpCountry is string else none))}}"
          destination.ip: "{{parsed_event.message.detail.dst or parsed_event.message.detail.peerIp}}"
          destination.mac: "{{parsed_event.message.detail.dmac}}"
          destination.port: "{{parsed_event.message.detail.dpt}}"
          event.dataset: "{{parsed_event.message.source}}"
          event.end: "{{parsed_event.message.detail.lastSeen | to_rfc3339}}"
          event.provider: "{{parsed_event.message.pname or parsed_event.message.detail.pname}}"
          event.reason: "{{parsed_event.message.description}}"
          event.severity: "{{parsed_event.message.detail.severity}}"
          event.start: "{{parsed_event.message.detail.firstSeen | to_rfc3339}}"
          group.id: "{{parsed_event.message.detail.groupId}}"
          host.id: "{{parsed_event.message.detail.endpointGuid}}"
          host.ip: "{{parsed_event.message.endpoint.ips}}"
          host.name: "{{parsed_event.message.endpoint.endpointName or parsed_event.message.detail.interestedHost or parsed_event.message.detail.shost}}"
          host.os.full: "{{parsed_event.message.detail.osDescription}}"
          host.os.name: "{{parsed_event.message.detail.osName}}"
          host.os.version: "{{parsed_event.message.detail.osVer}}"
          network.application: "{{parsed_event.message.detail.app}}"
          observer.name: "{{parsed_event.message.detail.dvchost}}"
          observer.product: "{{parsed_event.message.get('detail', {}).get('dvchost', 'Vision One')}}"
          organization.id: "{{parsed_event.message.orgId}}"
          process.command_line: "{{parsed_event.message.detail.objectCmd}}"
          process.executable: "{{parsed_event.message.detail.ObjectFilePath or parsed_event.message.detail.objectFilePath or parsed_event.message.detail.filePathName}}"
          process.hash.md5: "{{parsed_event.message.detail.ObjectFileHashMd5}}"
          process.hash.sha1: "{{parsed_event.message.detail.ObjectFileHashSha1}}"
          process.hash.sha256: "{{parsed_event.message.detail.ObjectFileHashSha256}}"
          process.name: "{{parsed_event.message.detail.processName | basename or parsed_event.message.detail.ObjectName | basename}}"
          process.parent.command_line: "{{parsed_event.message.detail.processCmd}}"
          process.parent.executable: "{{parsed_event.message.detail.processFilePath}}"
          process.parent.hash.md5: "{{parsed_event.message.detail.processFileHashMd5}}"
          process.parent.hash.sha1: "{{parsed_event.message.detail.processFileHashSha1}}"
          process.parent.hash.sha256: "{{parsed_event.message.detail.processFileHashSha256}}"
          process.parent.parent.command_line: "{{parsed_event.message.detail.parentCmd}}"
          process.parent.parent.executable: "{{parsed_event.message.detail.parentFilePath}}"
          process.parent.parent.hash.md5: "{{parsed_event.message.detail.parentFileHashMd5}}"
          process.parent.parent.hash.sha1: "{{parsed_event.message.detail.parentFileHashSha1}}"
          process.parent.parent.hash.sha256: "{{parsed_event.message.detail.parentFileHashSha256}}"
          process.parent.parent.name: "{{parsed_event.message.detail.parentName | basename}}"
          process.parent.parent.pid: "{{parsed_event.message.detail.parentPid}}"
          process.parent.parent.start: "{{parsed_event.message.detail.parentLaunchTime | to_rfc3339}}"
          process.parent.parent.user.domain: "{{parsed_event.message.detail.parentUserDomain}}"
          process.parent.parent.user.name: "{{parsed_event.message.detail.parentUser}}"
          process.parent.pid: "{{parsed_event.message.detail.processPid}}"
          process.parent.start: "{{parsed_event.message.detail.processLaunchTime | to_rfc3339}}"
          process.parent.user.domain: "{{parsed_event.message.detail.processUserDomain}}"
          process.parent.user.name: "{{parsed_event.message.detail.processUser}}"
          process.pid: "{{parsed_event.message.detail.objectPid}}"
          rule.id: "{{parsed_event.message.detail.ruleId | string}}"
          rule.name: "{{parsed_event.message.ruleName or parsed_event.message.detail.ruleName or (parsed_event.message.filters | map(attribute='name') | list if parsed_event.message.filters and parsed_event.message.filters | length > 0 else none)}}"
          rule.ruleset: "{{parsed_event.message.policyName}}"
          source.as.organization.name: "{{parsed_event.message.detail.srcIsp[0] if parsed_event.message.detail.srcIsp is iterable and parsed_event.message.detail.srcIsp is not string and parsed_event.message.detail.srcIsp | length > 0 else (parsed_event.message.detail.srcIsp if parsed_event.message.detail.srcIsp is string else none)}}"
          source.geo.city_name: "{{parsed_event.message.detail.srcCity[0] if parsed_event.message.detail.srcCity is iterable and parsed_event.message.detail.srcCity is not string and parsed_event.message.detail.srcCity | length > 0 else (parsed_event.message.detail.srcCity if parsed_event.message.detail.srcCity is string else none)}}"
          source.geo.country_name: "{{parsed_event.message.detail.srcCountry[0] if parsed_event.message.detail.srcCountry is iterable and parsed_event.message.detail.srcCountry is not string and parsed_event.message.detail.srcCountry | length > 0 else (parsed_event.message.detail.srcCountry if parsed_event.message.detail.srcCountry is string else none)}}"
          source.ip: "{{parsed_event.message.detail.src or parsed_event.message.detail.interestedIp}}"
          source.mac: "{{parsed_event.message.detail.smac}}"
          source.port: "{{parsed_event.message.detail.spt}}"
          threat.tactic.id: "{{parsed_event.message.detail.tacticId}}"
          url.original: "{{parsed_event.message.request or parsed_event.message.detail.request}}"
          user.domain: "{{parsed_event.message.detail.objectUserDomain or parsed_event.message.detail.domainName}}"
          user.name: "{{parsed_event.message.detail.objectUser or parsed_event.message.detail.suid or parsed_event.message.detail.dUser1}}"

      - set:
          file.name: "{{parsed_event.message.detail.fileName[0]}}"
        filter: "{{parsed_event.message.detail.fileName and parsed_event.message.detail.fileName | length > 0}}"

      - set:
          event.action: "{{parsed_event.message.act[0]}}"
        filter: "{{parsed_event.message.act | length > 0 }}"

      - set:
          rule.id: "{{(parsed_event.message.filters | map(attribute='id') | list | first) | string}}"
          threat.tactic.id: "{{parsed_event.message.filters | map(attribute='mitreTacticIds') | list | sum(start = [])}}"

          threat.technique.id: >
            {%- set ids = [] -%}
            {%- for item in parsed_event.message.filters | map(attribute='mitreTechniqueIds') | list | sum(start = []) -%}
              {%- if "." not in item -%}{%- set ids = ids.append(item) -%}{%- endif -%}
            {%- endfor -%}
            {%- if ids | length > 0 -%}{{ ids | tojson }}{%- endif -%}

          threat.technique.subtechnique.id: >
            {%- set ids = [] -%}
            {%- for item in parsed_event.message.filters | map(attribute='mitreTechniqueIds') | list | sum(start = []) -%}
              {%- if "." in item -%}{%- set ids = ids.append(item) -%}{%- endif -%}
            {%- endfor -%}
            {%- if ids | length > 0 -%}{{ ids | tojson }}{%- endif -%}

        filter: "{{parsed_event.message.filters | length > 0 }}"

  set_custom_fields:
    actions:
      - set:
          trendmicro.visionone.oat.attackphase.source: "{{parsed_event.message.detail.sAttackPhase}}"
          trendmicro.visionone.oat.attackphase.target: "{{parsed_event.message.detail.pAttackPhase}}"
          trendmicro.visionone.oat.count: "{{parsed_event.message.detail.cnt | int}}"
          trendmicro.visionone.oat.detectionType: "{{parsed_event.message.detectionType}}"
          trendmicro.visionone.oat.eventId: "{{parsed_event.message.eventId}}"
          trendmicro.visionone.oat.eventName: "{{parsed_event.message.eventName}}"
          trendmicro.visionone.oat.eventSubName: "{{parsed_event.message.eventSubName}}"
          trendmicro.visionone.oat.malName: "{{parsed_event.message.detail.malName}}"
          trendmicro.visionone.oat.malType: "{{parsed_event.message.detail.malType}}"
          trendmicro.visionone.oat.riskLevel: "{{parsed_event.message.riskLevel or parsed_event.message.detail.filterRiskLevel or (parsed_event.message.filters | map(attribute='riskLevel') | list | join(', ') if parsed_event.message.filters and parsed_event.message.filters | length > 0 else none) or parsed_event.message.detail.severity}}"
          trendmicro.visionone.oat.threatType: "{{parsed_event.message.detail.threatType}}"

  set_email_fields:
    actions:
      - set:
          event.category: ["email"]
          event.type: ["info"]

      - set:
          email.from.address: "{{ parsed_event.message.suser }}"
          email.to.address: "{{ parsed_event.message.duser }}"
          email.subject: "{{ parsed_event.message.mailMsgSubject }}"
          email.local_id: "{{ parsed_event.message.msgUuid }}"
          email.message_id: "{{ parsed_event.message.msgId }}"
          email.delivery_timestamp: "{{ parse_email_date.datetime }}"

      - set:
          email.attachments: >
            [
              {%- for item in parsed_event.message.attachment -%}
                {"file": {"name": "{{ item['attachmentFileName'] }}", "size": {{ item['attachmentFileSize'] }}, "hash": {"sha1": "{{ item['attachmentFileHash'] }}"}}},
              {%- endfor -%}
            ]
        filter: "{{parsed_event.message.attachment | length > 0}}"
