name: microsoft-always-on-vpn
pipeline:
  - name: parsed_event
    external:
      name: dsv.parse-dsv
      properties:
        delimiter: ","
        columnnames:
          - ObserverName
          - ServiceName
          - Date
          - Time
          - PacketType
          - Username
          - FullyQualifiedName
          - CalledStationId
          - CallingStationId
          - CallbackNumber
          - FramedIpAddress
          - NAS_Identifier
          - NAS_IpAddress
          - NAS_Port
          - ClientVendor
          - ClientIpAddress
          - ClientFriendlyName
          - EventTimestamp
          - PortLimit
          - NASPortType
          - ConnectInfo
          - FramedProtocol
          - ServiceType
          - AuthenticationType
          - PolicyName
          - ReasonCode
          - Class
          - SessionTimeout
          - IdleTimeout
          - TerminationAction
          - EAP_FriendlyName
          - ACCT_StatusType
          - ACCT_DelayTime
          - ACCT_InputOctets
          - ACCT_OutputOctets
          - ACCT_SessionId
          - ACCT_Authentic
          - ACCT_SessionTime
          - ACCT_InputPackets
          - ACCT_OutputPackets
          - ACCT_TerminateCause
          - ACCT_MultiSSNId
          - ACCT_LinkCount
          - ACCT_InterimInterval
          - TunnelType
          - TunnelMediumType
          - TunnelClientEndpoint
          - TunnelServerEndpoint
          - ACCT_TunnelConn
          - TunnelPVTGroupId
          - TunnelAssignmentId
          - TunnelPreference
          - MS_ACCT_AuthType
          - MS_ACCT_EAPType
          - MS_RAS_Version
          - MS_RAS_Vendor
          - MS_CHAP_Error
          - MS_CHAP_Domain
          - MS_MPPE_Encryption_Types
          - MS_MPPE_Encryption_Policy
          - ProxyPolicyName
          - ProviderType
          - ProviderName
          - RemoteServerAddress
          - MS_RAS_ClientName
          - MS_RAS_ClientVersion
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.Date}} {{parsed_event.message.Time}}"
        output_field: datetime
        format: "%m/%d/%Y %H:%M:%S"
  - name: set_ecs_fields
  - name: set_windows_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_date.datetime}}"
          event.category: ["network"]
          observer.hostname: "{{parsed_event.message.ObserverName}}"
          service.name: "{{parsed_event.message.ServiceName}}"
          user.email: "{{parsed_event.message.Username}}"
          source.nat.port: "{{parsed_event.message.NAS_Port}}"
          rule.name: "{{parsed_event.message.PolicyName}}"

      - set:
          source.ip: "{{parsed_event.message.ClientIpAddress}}"
        filter: "{{parsed_event.message.ClientIpAddress| is_ipaddress}}"

      - set:
          source.nat.ip: "{{parsed_event.message.CallingStationId}}"
        filter: "{{parsed_event.message.CallingStationId| is_ipaddress}}"

      - set:
          user.domain: '{{parsed_event.message.FullyQualifiedName.split("\\")[0]}}'
          user.name: '{{parsed_event.message.FullyQualifiedName.split("\\")[1]}}'
        filter: '{{parsed_event.message.FullyQualifiedName | re_search(".*\\.*")}}'
      - translate:
        dictionary:
          "1": "PPP"
          "2": "SLIP"
          "3": "ARAP"
          "4": "MLP"
          "5": "SIP"
          "6": "X.75"
          "7": "PDP"
        mapping:
          parsed_event.message.FramedProtocol: network.protocol
      - translate:
        dictionary:
          2: ["allowed"]
          3: ["denied"]
        mapping:
          parsed_event.message.PacketType: event.type
        fallback: ["info"]

  set_windows_fields:
    actions:
      - set:
          windows.remote_access_server.authentication.type: "{{parsed_event.message.AuthenticationType}}"
          windows.remote_access_server.reason.code: "{{parsed_event.message.ReasonCode}}"
          windows.remote_access_server.class: "{{parsed_event.message.Class}}"
          windows.remote_access_server.session.timeout: "{{parsed_event.message.SessionTimeout}}"
          windows.remote_access_server.session.id: "{{parsed_event.message.ACCT_SessionId}}"
          windows.remote_access_server.packet.type: "{{parsed_event.message.PacketType}}"
          windows.remote_access_server.service.type: "{{parsed_event.message.ServiceType}}"
          windows.remote_access_server.tunnel_medium.type: "{{parsed_event.message.TunnelMediumType}}"
          windows.remote_access_server.framed_protocol.type: "{{parsed_event.message.FramedProtocol}}"
          windows.remote_access_server.provider.type: "{{parsed_event.message.ProviderType}}"
          windows.remote_access_server.provider.name: "{{parsed_event.message.ProviderName}}"
      - translate:
        dictionary:
          1: "Access-Request"
          2: "Access-Accept"
          3: "Access-Reject"
          4: "Accounting-Request"
          5: "Accounting-Response"
          11: "Access-Challenge"
          12: "Status-Server"
          13: "Status-Client"
          40: "Disconnect-Request"
          41: "Disconnect-ACK"
          42: "Disconnect-NAK"
          43: "CoA-Request"
          44: "CoA-ACK"
          45: "CoA-NAK"
        mapping:
          windows.remote_access_server.packet.type: windows.remote_access_server.packet.name
      - translate:
        dictionary:
          0: "Invalid"
          1: "PAP"
          2: "CHAP"
          3: "MS-CHAP"
          4: "MS-CHAP2"
          5: "EAP"
          6: "ARAP"
          7: "None"
          8: "Custom"
          9: "MS-CHAP-CPW"
          10: "MS-CHAP2-CPW"
          11: "PEAP"
        mapping:
          windows.remote_access_server.authentication.type: windows.remote_access_server.authentication.name
      - translate:
        dictionary:
          0: "IAS_SUCCESS"
          1: "IAS_INTERNAL_ERROR"
          2: "IAS_ACCESS_DENIED"
          3: "IAS_MALFORMED_REQUEST"
          4: "IAS_GLOBAL_CATALOG_UNAVAILABLE"
          5: "IAS_DOMAIN_UNAVAILABLE"
          6: "IAS_SERVER_UNAVAILABLE"
          7: "IAS_NO_SUCH_DOMAIN"
          8: "IAS_NO_SUCH_USER"
          16: "IAS_AUTH_FAILURE"
          17: "IAS_CHANGE_PASSWORD_FAILURE"
          18: "IAS_UNSUPPORTED_AUTH_TYPE"
          32: "IAS_LOCAL_USERS_ONLY"
          33: "IAS_PASSWORD_MUST_CHANGE"
          34: "IAS_ACCOUNT_DISABLED"
          35: "IAS_ACCOUNT_EXPIRED"
          36: "IAS_ACCOUNT_LOCKED_OUT"
          37: "IAS_INVALID_LOGON_HOURS"
          38: "IAS_ACCOUNT_RESTRICTION"
          48: "IAS_NO_POLICY_MATCH"
          64: "IAS_DIALIN_LOCKED_OUT"
          65: "IAS_DIALIN_DISABLED"
          66: "IAS_INVALID_AUTH_TYPE"
          67: "IAS_INVALID_CALLING_STATION"
          68: "IAS_INVALID_DIALIN_HOURS"
          69: "IAS_INVALID_CALLED_STATION"
          70: "IAS_INVALID_PORT_TYPE"
          71: "IAS_INVALID_RESTRICTION"
          80: "IAS_NO_RECORD"
          96: "IAS_SESSION_TIMEOUT"
          97: "IAS_UNEXPECTED_REQUEST"
        mapping:
          windows.remote_access_server.reason.code: windows.remote_access_server.reason.name
      - translate:
        dictionary:
          1: "Login"
          2: "Framed"
          3: "Callback Login"
          4: "Callback Framed"
          5: "Outbound"
          6: "Administrative"
          7: "NAS Prompt"
          8: "Authenticate Only"
          9: "Callback NAS Prompt"
          10: "Call Check"
          11: "Callback Administrative"
          12: "Voice"
          13: "Fax"
          14: "Modem Relay"
          15: "IAPP-Register"
          16: "IAPP-AP-Check"
          17: "Authorize Only"
          18: "Framed-Management"
          19: "Additional-Authorization"
        mapping:
          windows.remote_access_server.service.type: windows.remote_access_server.service.name
      - translate:
        dictionary:
          1: "IPv4"
          2: "IPv6"
          3: "NSAP"
          4: "HDLC"
          5: "BBN 1822"
          6: "802"
          7: "E.163"
          8: "E.164"
          9: "F.69"
          10: "X.121"
          11: "IPX"
          12: "Appletalk"
          13: "Decnet IV"
          14: "Banyan Vines"
          15: "E.164 with NSAP"
        mapping:
          windows.remote_access_server.tunnel_medium.type: windows.remote_access_server.tunnel_medium.name
      - translate:
        dictionary:
          1: "PPP"
          2: "SLIP"
          3: "ARAP"
          4: "Gandalf SLP/MLP"
          5: "Xylogics ISP/SIP"
          6: "X.75 Synchronous"
          7: "GPRS PDP Context"
        mapping:
          windows.remote_access_server.framed_protocol.type: windows.remote_access_server.framed_protocol.name
      - translate:
        dictionary:
          0: "None"
          1: "Windows"
          2: "Radius Proxy"
        mapping:
          windows.remote_access_server.provider.type: windows.remote_access_server.provider.name
        filter: '{{parsed_event.message.get("ProviderName") == None}}'
