name: nanocorp
ignored_values: []
pipeline:
  - name: parsed_json
    description: Parse the JSON formatted event
    filter: ""
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message
  - name: parsed_date
    description: set the seen_at field from timestamp to datetime format
    filter: ""
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_json.message.seen_at}}"
        output_field: datetime
        format: epoch_millis
        timezone: UTC
  - name: set_fields
    description: ""
    filter: ""
    external: null
stages:
  set_fields:
    actions:
      - set:
          source.ip: "{{parsed_json.message.source_ip}}"
          source.mac: "{{parsed_json.message.source_mac}}"
          event.start: "{{parsed_date.datetime}}"
          event.action: "{{parsed_json.message.event_type}}"
          event.outcome: "success"
          destination.ip: "{{parsed_json.message.dest_ip}}"
          destination.mac: "{{parsed_json.message.dest_mac}}"
          network.protocol: "{{parsed_json.message.network_protocol}}"
          "@timestamp": "{{parsed_date.datetime}}"
          event.category: ["network"]
          event.type: ["connection"]
          observer.vendor: "Nanocorp"
          observer.product: "Nanocorp"
          observer.type: "network"
        filter: ""
        name: set
