name: panda-security-siemfeeder
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef

  - name: set_ecs_fields
  - name: set_cef_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.category: ["host"]
          event.type: ["info"]

  set_cef_fields:
    actions:
      - set:
          siemfeeder: "{{parsed_event.message}}"
          host.name: "{{parsed_event.message.MachineName}}"
          user.name: "{{parsed_event.message.User}}"
          host.id: "{{parsed_event.message.MUID}}"
          registry.path: "{{parsed_event2.message.Path}}"
          registry.key: "{{parsed_event.message.RegKey}}"
      - set:
          source.ip: "{{parsed_event.message.MachineIP}}"
        filter: "{{parsed_event.message.MachineIP| is_ipaddress}}"
