name: SEKOIAIO actitivy logs
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"

  - name: parse_date
    external:
      name: date.parse
      properties:
        input_field: "{{json_event.message.timestamp}}"
        output_field: datetime
  - name: set_common_fields
stages:
  set_common_fields:
    actions:
      - set:
          sekoiaio.activity.archive.uuid: "{{json_event.message.action.parameters.archive.uuid}}"
        filter: '{{json_event.message.action.parameters.archive.get("uuid") != None}}'

      - set:
          sekoiaio.activity.archive.uuid: "{{json_event.message.action.results.archive.uuid}}"
        filter: '{{json_event.message.action.results.archive.get("uuid") != None}}'

      - set:
          client.ip: "{{json_event.message.visit.ip}}"
        filter: "{{json_event.message.visit.ip| is_ipaddress}}"

      - set:
          "@timestamp": "{{parse_date.datetime}}"

          error.code: "{{json_event.message.action.error.code}}"
          error.message: "{{json_event.message.action.error.message}}"
          event.action: "{{json_event.message.action.name}}"
          http.request.method: "{{json_event.message.action.method}}"
          http.request.referrer: "{{json_event.message.visit.referrer}}"
          observer.name: "{{json_event.message.observer.name}}"
          observer.version: "{{json_event.message.observer.version}}"
          url.original: "{{json_event.message.action.url}}"
          url.path: "{{json_event.message.action.path}}"
          user.id: "{{json_event.message.identity.user_uuid}}"
          user.domain: "SEKOIA.IO"
          user.full_name: "{{json_event.message.identity.profile_name}}"
          user_agent.original: "{{json_event.message.visit.user_agent}}"
          sekoiaio.activity.client.id: "{{json_event.message.identity.profile_identity}}"
          sekoiaio.activity.client.type: "{{json_event.message.identity.profile_type}}"
          sekoiaio.activity.communities: "{{json_event.message.action.communities}}"
          sekoiaio.activity.alert_filter.name: "{{json_event.message.action.parameters.alert_filter.name}}"
          sekoiaio.activity.alert_filter.uuid: "{{json_event.message.action.parameters.alert_filter.uuid}}"
          sekoiaio.activity.alert_type.uuid: "{{json_event.message.action.parameters.alert_type.uuid}}"
          sekoiaio.activity.apikey.description: "{{json_event.message.action.parameters.apikey.description}}"
          sekoiaio.activity.apikey.name: "{{json_event.message.action.parameters.apikey.name}}"
          sekoiaio.activity.archive_view.date_end: "{{json_event.message.action.parameters.archive_view.date_end}}"
          sekoiaio.activity.archive_view.date_start: "{{json_event.message.action.parameters.archive_view.date_start}}"
          sekoiaio.activity.archive_view.name: "{{json_event.message.action.parameters.archive_view.name}}"
          sekoiaio.activity.archive_view.uuid: "{{json_event.message.action.parameters.archive_view.uuid}}"
          sekoiaio.activity.archive.name: "{{json_event.message.action.parameters.archive.name}}"
          sekoiaio.activity.archive.provider: "{{json_event.message.action.parameters.archive.provider}}"
          sekoiaio.activity.archive.short_id: "{{json_event.message.action.parameters.archive.short_id}}"
          sekoiaio.activity.archive.snapshot.uuid: "{{json_event.message.action.parameters.archive.snapshot.uuid}}"
          sekoiaio.activity.asset.name: "{{json_event.message.action.parameters.asset.name}}"
          sekoiaio.activity.asset.uuid: "{{json_event.message.action.parameters.asset.uuid}}"
          sekoiaio.activity.community.description: "{{json_event.message.action.parameters.community.description}}"
          sekoiaio.activity.community.homepage_url: "{{json_event.message.action.parameters.community.homepage_url}}"
          sekoiaio.activity.community.name: "{{json_event.message.action.parameters.community.name}}"
          sekoiaio.activity.countermeasure_list.description: "{{json_event.message.action.parameters.countermeasure_list.description}}"
          sekoiaio.activity.countermeasure_list.name: "{{json_event.message.action.parameters.countermeasure_list.name}}"
          sekoiaio.activity.countermeasure_list.relevance: "{{json_event.message.action.parameters.countermeasure_list.relevance}}"
          sekoiaio.activity.countermeasure_list.uuid: "{{json_event.message.action.parameters.countermeasure_list.uuid}}"
          sekoiaio.activity.delegate.type: "{{json_event.message.action.parameters.delegate.type}}"
          sekoiaio.activity.delegate.uuid: "{{json_event.message.action.parameters.delegate.uuid}}"
          sekoiaio.activity.entity.description: "{{json_event.message.action.parameters.entity.description}}"
          sekoiaio.activity.entity.id: "{{json_event.message.action.parameters.entity.id}}"
          sekoiaio.activity.entity.name: "{{json_event.message.action.parameters.entity.name}}"
          sekoiaio.activity.entity.uuid: "{{json_event.message.action.parameters.entity.uuid}}"
          sekoiaio.activity.events_search.earliest_time: "{{json_event.message.action.parameters.events_search.earliest_time}}"
          sekoiaio.activity.events_search.latest_time: "{{json_event.message.action.parameters.events_search.latest_time}}"
          sekoiaio.activity.events_search.results_ttl: "{{json_event.message.action.parameters.events_search.results_ttl}}"
          sekoiaio.activity.events_search.term: "{{json_event.message.action.parameters.events_search.term}}"
          sekoiaio.activity.events_search.uuid: "{{json_event.message.action.parameters.events_search.uuid}}"
          sekoiaio.activity.generation_mode.description: "{{json_event.message.action.parameters.generation_mode.description}}"
          sekoiaio.activity.generation_mode.name: "{{json_event.message.action.parameters.generation_mode.name}}"
          sekoiaio.activity.generation_mode.uuid: "{{json_event.message.action.parameters.generation_mode.uuid}}"
          sekoiaio.activity.intake.format.module.description: "{{json_event.message.action.parameters.intake.format.module.description}}"
          sekoiaio.activity.intake.format.module.name: "{{json_event.message.action.parameters.intake.format.module.name}}"
          sekoiaio.activity.intake.format.module.slug: "{{json_event.message.action.parameters.intake.format.module.slug}}"
          sekoiaio.activity.intake.format.module.uuid: "{{json_event.message.action.parameters.intake.format.module.uuid}}"
          sekoiaio.activity.intake.format.name: "{{json_event.message.action.parameters.intake.format.name}}"
          sekoiaio.activity.intake.format.slug: "{{json_event.message.action.parameters.intake.format.slug}}"
          sekoiaio.activity.intake.format.uuid: "{{json_event.message.action.parameters.intake.format.uuid}}"
          sekoiaio.activity.intake.name: "{{json_event.message.action.parameters.intake.name}}"
          sekoiaio.activity.intake.uuid: "{{json_event.message.action.parameters.intake.uuid}}"
          sekoiaio.activity.invitation.email_address: "{{json_event.message.action.parameters.invitation.email_address}}"
          sekoiaio.activity.mfa_method: "{{json_event.message.action.parameters.mfa_method}}"
          sekoiaio.activity.permissions: "{{json_event.message.action.parameters.permissions}}"
          sekoiaio.activity.role.description: "{{json_event.message.action.parameters.role.description}}"
          sekoiaio.activity.role.name: "{{json_event.message.action.parameters.role.name}}"
          sekoiaio.activity.role.uuid: "{{json_event.message.action.parameters.role.uuid}}"
          sekoiaio.activity.rule.definition_uuid: "{{json_event.message.action.parameters.rule.definition_uuid}}"
          sekoiaio.activity.rule.name: "{{json_event.message.action.parameters.rule.name}}"
          sekoiaio.activity.user.company_name: "{{json_event.message.action.parameters.user.company_name}}"
          sekoiaio.activity.user.email: "{{json_event.message.action.parameters.user.email}}"
          sekoiaio.activity.user.firstname: "{{json_event.message.action.parameters.user.firstname}}"
          sekoiaio.activity.user.lastname: "{{json_event.message.action.parameters.user.lastname}}"
          sekoiaio.activity.user.name: "{{json_event.message.action.parameters.user.name}}"
          sekoiaio.activity.user.uuid: "{{json_event.message.action.parameters.user.uuid}}"
      - set:
          sekoiaio.activity.archive.short_id: "{{json_event.message.action.results.archive.short_id}}"
          sekoiaio.activity.archive_view.uuid: "{{json_event.message.action.results.archive_view.uuid}}"
          sekoiaio.activity.events_search.uuid: "{{json_event.message.action.results.events_search.uuid}}"
          sekoiaio.activity.generation_mode.uuid: "{{json_event.message.action.results.generation_mode.uuid}}"
          sekoiaio.activity.intake.uuid: "{{json_event.message.action.results.intake.uuid}}"
          sekoiaio.activity.intake.format.uuid: "{{json_event.message.action.results.intake.format.uuid}}"
          sekoiaio.activity.intake.format.module.uuid: "{{json_event.message.action.results.intake.format.module.uuid}}"
      - set:
          user.target.id: "{{json_event.message.action.parameters.user.uuid}}"
          user.target.full_name: "{{json_event.message.action.parameters.user.name}}"
          user.target.roles: "[{{json_event.message.action.parameters.role.name}}]"
        filter: '{{json_event.message.action.name in ["role-assignment", "member-removal", "role-removal"]}}'
      - set:
          user.target.email: "{{json_event.message.action.parameters.user.email}}"
        filter: '{{json_event.message.action.name == "invitation"}}'
