name: cisco-secure-access-file-events
pipeline:
  - name: parsed_dsv
    external:
      name: dsv.parse-dsv
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - timestamp
          - organization_id
          - retention_policy_in_days
          - aws_region
          - firewall_eventid
          - file_action
          - disposition
          - sha256
          - direction
          - threat_name
          - filestatic_analysis
          - threat_score
          - filetype_id
          - filename
          - filesize
          - archive_filename
          - archive_filedepth
          - archive_sha
          - dlp_status
          - enforced_by
          - ftd_enforcement_id
          - ftd_enforcement_name
        delimiter: ","

  - name: set_ecs_fields

  - name: set_custom_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.category: ["file", "malware"]
          event.type: ["info"]
          observer.vendor: "Cisco"
          observer.product: "Secure Access"
          observer.type: "proxy"
          event.dataset: "file-events"

      - set:
          "@timestamp": "{{parsed_dsv.message.timestamp | to_rfc3339}}"
          organization.id: "{{parsed_dsv.message.organization_id}}"
          cloud.region: "{{parsed_dsv.message.aws_region}}"
          event.action: "{{parsed_dsv.message.file_action | lower}}"

          file.hash.sha256: "{{parsed_dsv.message.sha256}}"
          file.name: "{{parsed_dsv.message.filename}}"
          file.size: "{{parsed_dsv.message.filesize}}"

          threat.indicator.name: "{{parsed_dsv.message.threat_name}}"

      - translate:
        dictionary:
          "MALWARE": ["failure"]
          "CLEAN": ["success"]
        mapping:
          parsed_dsv.message.disposition: event.outcome
        fallback: ["unknown"]

  set_custom_fields:
    actions:
      - set:
          cisco_secure_access.file.retention_policy_days: "{{parsed_dsv.message.retention_policy_in_days}}"
          cisco_secure_access.file.firewall_event_id: "{{parsed_dsv.message.firewall_eventid}}"
          cisco_secure_access.file.disposition: "{{parsed_dsv.message.disposition}}"
          cisco_secure_access.file.direction: "{{parsed_dsv.message.direction}}"
          cisco_secure_access.file.static_analysis: "{{parsed_dsv.message.filestatic_analysis}}"
          cisco_secure_access.file.threat_score: "{{parsed_dsv.message.threat_score}}"
          cisco_secure_access.file.type_id: "{{parsed_dsv.message.filetype_id}}"
          cisco_secure_access.file.archive_filename: "{{parsed_dsv.message.archive_filename}}"
          cisco_secure_access.file.archive_depth: "{{parsed_dsv.message.archive_filedepth}}"
          cisco_secure_access.file.archive_sha256: "{{parsed_dsv.message.archive_sha}}"
          cisco_secure_access.file.dlp_status: "{{parsed_dsv.message.dlp_status}}"
          cisco_secure_access.file.enforced_by: "{{parsed_dsv.message.enforced_by}}"
          cisco_secure_access.file.ftd_enforcement_id: "{{parsed_dsv.message.ftd_enforcement_id}}"
          cisco_secure_access.file.ftd_enforcement_name: "{{parsed_dsv.message.ftd_enforcement_name}}"
