name: cortex-xdr
pipeline:
  - name: parsed_event
    description: ''
    filter: ''
    external:
      name: cef.parse-cef
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: setter
    description: ''
    filter: ''
    external: null
stages:
  setter:
    actions:
      - set:
          host.name: '{{parsed_event.message.shost}}'
          user.name: '{{parsed_event.message.suser.split("\\"}[1]}'
           user.domain: '{{parsed_event.message.suser.split("\\"}[0]}'
          event.action: '{{parsed_event.message.act|lower}}'
          cortexxdr.category: '{{parsed_event.message.cat|upper}}'
          cortexxdr.event_subtype: '{{parsed_event.message.subtype}}'
          event.severity: '{{parsed_event.message.Severity}}'
          cortexxdr.original_message: '{{parsed_event.message.msg}}'
        filter: ''
        name: set
      - fallback: UNPARSED
        dictionary:
          '0': UNKNOWN
          '6': LOW
          '8': MEDIUM
          '9': HIGH
        mapping:
          cortexxdr.severity_human: cortexxdr.severity_human
        filter: ''
        name: translate
