name: cortex-xdr
pipeline:
  - name: parsed_event
    description: ''
    filter: ''
    external:
      name: cef.parse-cef
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: setter
    description: ''
    filter: ''
    external: null
stages:
  setter:
    actions:
      - set:
          host.name: '{{parsed_event.message.shost}}'
          # Note: these lines are hard to understand.
          # It seems that the suser=['domain\\\\user'] field is parsed as a
          # string and not an array. So I have to first remove the trailing
          # [' and '], then split it around the double antislash, and
          # finally access the fields.
          # This is buggy and will fail in case there are multiple users, or in
          # case the original bug is fixed and the value is parsed as an array.
          user.domain: '{{parsed_event.message.suser[2:-2].split("\\")[0]}}'
          user.name: '{{parsed_event.message.suser[2:-2].split("\\")[2]}}'
          event.action: '{{parsed_event.message.act|lower}}'
          cortexxdr.category: '{{parsed_event.message.cat|upper}}'
          cortexxdr.event_subtype: '{{parsed_event.message.subtype}}'
          event.severity: '{{parsed_event.message.Severity}}'
        filter: ''
        name: set
