name: cortex-xdr
pipeline:
  - name: parsed_event
    description: ''
    filter: ''
    external:
      name: cef.parse-cef
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: grok_suser
    description: ''
    filter: ''
    external:
      name: grok.match
      properties:
        input_field: '{{parsed_event.message.suser}}'
        output_field: fields
        pattern: \[\'%{WORD:domain}\\\\%{WORD:name}
  - name: setter
    description: ''
    filter: ''
    external: null
stages:
  setter:
    actions:
      - set:
          host.name: '{{parsed_event.message.shost}}'
          user.domain: '{{parsed_event.message.suser[2:-2].split("\\")[0]}}'
          user.name: '{{parsed_event.message.suser[2:-2].split("\\")[2]}}'
          event.action: '{{parsed_event.message.act|lower}}'
          event.category: '{{parsed_event.message.cat|upper}}'
          event.type: '{{parsed_event.message.subtype}}'
          event.severity: '{{parsed_event.message.Severity}}'
          event.reason: '{{parsed_event.message.msg}}'
        filter: ''
        name: set
