name: Cloudflare DNS logs
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: parse_date
    external:
      name: date.parse
      properties:
        input_field: "{{json_event.message.Timestamp | float / 1000000000}}"
        output_field: datetime
        format: timestamp
  - name: set_ecs_fields
  - name: set_custom_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{parse_date.datetime}}"
          dns.question.name: "{{json_event.message.QueryName | trim('.')}}"
          event.category: ["network"]
          event.type: ["info"]
          event.dataset: "dns_logs"
          observer.vendor: "Cloudflare"
          observer.type: "dns"

      - set:
          source.ip: "{{json_event.message.SourceIP}}"
        filter: "{{json_event.message.SourceIP  | is_ipaddress}}"

      - translate:
        dictionary:
          1: "A"
          2: "NS"
          3: "MD"
          4: "MF"
          5: "CNAME"
          6: "SOA"
          7: "MB"
          8: "MG"
          9: "MR"
          10: "NULL"
          11: "WKS"
          12: "PTR"
          13: "HINFO"
          14: "MINFO"
          15: "MX"
          16: "TXT"
          17: "RP"
          18: "AFSDB"
          19: "X25"
          20: "ISDN"
          21: "RT"
          22: "NSAP"
          23: "NSAP-PTR"
          24: "SIG"
          25: "KEY"
          26: "PX"
          27: "GPOS"
          28: "AAAA"
          29: "LOC"
          30: "NXT"
          31: "EID"
          32: "NIMLOC"
          33: "SRV"
          34: "ATMA"
          35: "NAPTR"
          36: "KX"
          37: "CERT"
          38: "A6"
          39: "DNAME"
          40: "SINK"
          41: "OPT"
          42: "APL"
          43: "DS"
          44: "SSHFP"
          45: "IPSECKEY"
          46: "RRSIG"
          47: "NSEC"
          48: "DNSKEY"
          49: "DHCID"
          50: "NSEC3"
          51: "NSEC3PARAM"
          52: "TLSA"
          53: "SMIMEA"
          55: "HIP"
          56: "NINFO"
          57: "RKEY"
          58: "TALINK"
          59: "CDS"
          60: "CDNSKEY"
          61: "OPENPGPKEY"
          62: "CSYNC"
          63: "ZONEMD"
          64: "SVCB"
          65: "HTTPS"
          99: "SPF"
          100: "UINFO"
          101: "UID"
          102: "GID"
          103: "UNSPEC"
          104: "NID"
          105: "L32"
          106: "L64"
          107: "LP"
          108: "EUI48"
          109: "EUI64"
          249: "TKEY"
          250: "TSIG"
          251: "IXFR"
          252: "AXFR"
          253: "MAILB"
          254: "MAILA"
          255: "*"
          256: "URI"
          257: "CAA"
          258: "AVC"
          259: "DOA"
          260: "AMTRELAY"
          32768: "TA"
          32769: "DLV"
        mapping:
          json_event.message.QueryType: dns.question.type

      # http://www.iana.org/assignments/dns-parameters/dns-parameters.xhtml#dns-parameters-6
      - translate:
        dictionary:
          0: "NoError"
          1: "FormErr"
          2: "ServFail"
          3: "NXDomain"
          4: "NotImp"
          5: "Refused"
          6: "YXDomain"
          7: "YXRRSet"
          8: "NXRRSet"
          9: "NotAuth"
          10: "NotZone"
          11: "DSOTYPENI"
          16: "BADVERS OR BADSIG"
          17: "BADKEY"
          18: "BADTIME"
          19: "BADMODE"
          20: "BADNAME"
          21: "BADALG"
          22: "BADTRUNC"
          23: "BADCOOKIE"
        mapping:
          json_event.message.ResponseCode: dns.response_code

  set_custom_fields:
    actions:
      - set:
          cloudflare.ColoCode: "{{json_event.message.ColoCode}}"
          cloudflare.ResponseCached: "{{json_event.message.ResponseCached | string}}"
          cloudflare.EDNSSubnet: "{{json_event.message.EDNSSubnet}}"
          cloudflare.EDNSSubnetLength: "{{json_event.message.EDNSSubnetLength}}"
