name: palo alto networks
pipeline:
  # Just use to get the column format
  - name: parsed_dsv
    external:
      name: dsv.parse-dsv
      properties:
        columnnames:
            - tmp1
            - ReceiveTime
            - SerialNum
            - Type
        delimiter: ","

  # TRAFFIC
  - name: parsed_dsv_traffic
    external:
      name: dsv.parse-dsv
      filter: "{{parsed_dsv.message.Type == 'TRAFFIC'}}"
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - PaloAltoDomain
          - ReceiveTime
          - SerialNum
          - Type
          - Threat_ContentType
          - ConfigVersion
          - GenerateTime
          - SourceAddress
          - DestinationAddress
          - NATSourceIP
          - NATDestinationIP
          - Rule
          - SourceUser
          - DestinationUser
          - Application
          - VirtualSystem
          - SourceZone
          - DestinationZone 
          - InboundInterface 
          - OutboundInterface
          - LogAction
          - TimeLogged
          - SessionID
          - RepeatCount
          - SourcePort
          - DestinationPort
          - NATSourcePort
          - NATDestinationPort
          - Flags
          - IPProtocol
          - Action
          - Bytes
          - BytesSent
          - BytesReceived
          - Packets
          - StartTime
          - ElapsedTimeInSec
          - Category
          - Padding
          - seqno
          - ActionFlags
          - SourceCountry
          - DestinationCountry
          - cpadding
          - pkts_sent
          - pkts_received
        delimiter: ","

  # USERID
  - name: parsed_dsv_userid
    external:
      name: dsv.parse-dsv
      filter: "{{parsed_dsv.message.Type == 'USERID'}}"
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - FUTURE_USER
          - ReceiveTime
          - SerialNum
          - Type
          - Threat_ContentType
          - FUTURE_USE
          - GeneratedTime
          - VirtualSystem
          - SourceIP
          - User
          - DataSourceName
          - EventID
          - RepeatCount
          - TimeOutThreshold
          - SourcePort
          - DestinationPort
          - DataSource
          - DataSourceType
          - SequenceNumber
          - ActionFlags
          - DeviceGroupHierarchyLevel1
          - DeviceGroupHierarchyLevel2
          - DeviceGroupHierarchyLevel3
          - DeviceGroupHierarchyLevel4
          - VirtualSystemName
          - DeviceName
          - VirtualSystemID
          - FactorType
          - FactorCompletionTime
          - FactorNumber
          - FUTURE_USE
          - FUTURE_USE2
          - UserGroupFlags
          - UserbySource
        delimiter: ","

  # GLOBALPROTECT
  - name: parsed_dsv_globalprotect
    external:
      name: dsv.parse-dsv
      filter: "{{parsed_dsv.message.Type == 'GLOBALPROTECT'}}"
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - FUTURE_USE
          - ReceiveTime
          - SerialNumber
          - Type
          - Threat_ContentType
          - FUTURE_USE
          - GeneratedTime
          - VirtualSystem
          - EventID
          - Stage
          - AuthenticationMethod
          - TunnelType
          - SourceUser
          - SourceRegion
          - MachineName
          - PublicIP
          - PublicIPv6
          - PrivateIP
          - PrivateIPv6
          - HostID
          - SerialNumber
          - ClientVersion
          - ClientOS
          - ClientOSVersion
          - RepeatCount
          - Reason
          - Error
          - Description
          - Status
          - Location
          - LoginDuration
          - ConnectMethod
          - ErrorCode
          - Portal
          - SequenceNumber
          - ActionFlags
        delimiter: ","

  # SYSTEM
  - name: parsed_dsv_system
    external:
      name: dsv.parse-dsv
      filter: "{{parsed_dsv.message.Type == 'SYSTEM'}}"
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - FUTURE_USE
          - ReceiveTime
          - SerialNumber
          - Type
          - Threat_ContentType
          - FUTURE_USE
          - GeneratedTime
          - VirtualSystem
          - EventID
          - Object
          - FUTURE_USE
          - FUTURE_USE_2
          - Module
          - Severity
          - Description
          - SequenceNumber
          - ActionFlags
          - DeviceGroupHierarchyLevel1
          - DeviceGroupHierarchyLevel2
          - DeviceGroupHierarchyLevel3
          - DeviceGroupHierarchyLevel4
          - VirtualSystemName
          - DeviceName
        delimiter: ","

  # THREAT
  - name: parsed_dsv_threat
    external:
      name: dsv.parse-dsv
      filter: "{{parsed_dsv.message.Type == 'THREAT'}}"
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - PaloAltoDomain                                                                                                                                                                                           
          - ReceiveTime                                                                                                                                                                                              
          - SerialNum                                                                                                                                                                                                
          - Type                                                                                                                                                                                                     
          - Threat_ContentType                                                                                                                                                                                       
          - ConfigVersion                                                                                                                                                                                            
          - GenerateTime                                                                                                                                                                                             
          - SourceAddress                                                                                                                                                                                            
          - DestinationAddress                                                                                                                                                                                       
          - NATSourceIP                                                                                                                                                                                              
          - NATDestinationIP                                                                                                                                                                                         
          - Rule                                                                                                                                                                                                     
          - SourceUser                                                                                                                                                                                               
          - DestinationUser                                                                                                                                                                                          
          - Application                                                                                                                                                                                              
          - VirtualSystem                                                                                                                                                                                            
          - SourceZone
          - DestinationZone
          - InboundInterface
          - OutboundInterface
          - LogAction
          - TimeLogged
          - SessionID
          - RepeatCount
          - SourcePort
          - DestinationPort
          - NATSourcePort
          - NATDestinationPort
          - Flags
          - IPProtocol
          - Action
          - URLFilename
          - Threat_ContentName
          - Category
          - Severity
          - Direction
          - seqno
          - ActionFlags
          - SourceCountry
          - DestinationCountry
          - cpadding
          - ContentType
          - PcapID
          - FileDigest
          - Cloud
          - URLID
          - UserAgent
          - FileType
          - Xff
          - Referer
          - Sender
          - Subject
          - Recipient
          - ReportID
          - DeviceGroupHierarchyLevel1
          - DeviceGroupHierarchyLevel2
          - DeviceGroupHierarchyLevel3
          - DeviceGroupHierarchyLevel4
          - VirtualSystemName
          - DeviceName
          - FileURL
          - SourceVMUUID
          - DestinationVMUUID
          - HttpMethod
          - TunnelIDIMSI
          - MonitorTagIMEI
          - ParentSessionID
          - ParentSessionStartTime
          - Tunnel
          - Threat_Category
          - Contentver
          - SigFlags
          - SCTPAssociationID
          - PayloadProtocolID
          - HttpHeaders
        delimiter: ","

  - name: field_extraction_traffic
    filter: "{{parsed_dsv.message.Type == 'TRAFFIC'}}"
  - name: field_extraction_userid
    filter: "{{parsed_dsv.message.Type == 'USERID'}}"
  - name: field_extraction_globalprotect
    filter : "{{parsed_dsv.message.Type == 'GLOBALPROTECT'}}"
  - name: field_extraction_system
    filter: "{{parsed_dsv.message.Type == 'SYSTEM'}}"
  - name: field_extraction_threat
    filter: "{{parsed_dsv.message.Type == 'THREAT'}}"
    
stages:
  field_extraction_traffic:
    actions:
      - set:
          destination.address: '{{parsed_dsv_traffic.message.DestinationAddress}}'
          destination.port: '{{parsed_dsv_traffic.message.DestinationPort}}'
          destination.nat.ip: '{{parsed_dsv_traffic.message.NATDestinationIP}}'
          destination.nat.port: '{{parsed_dsv_traffic.message.NATDestinationPort}}'
          destination.bytes: '{{parsed_dsv_traffic.message.BytesReceived}}'
          destination.packets: '{{parsed_dsv_traffic.message.pkts_received}}'
          source.address: '{{parsed_dsv_traffic.message.SourceAddress}}'
          source.port: '{{parsed_dsv_traffic.message.SourcePort}}'
          source.nat.ip: '{{parsed_dsv_traffic.message.NATSourceIP}}'
          source.nat.port: '{{parsed_dsv_traffic.message.NATSourcePort}}'
          source.bytes: '{{parsed_dsv_traffic.message.BytesSent}}'
          source.packets: '{{parsed_dsv_traffic.message.pkts_sent}}'
          network.packets: '{{parsed_dsv_traffic.message.Packets}}'
          network.bytes: '{{parsed_dsv_traffic.message.Bytes}}'
          network.transport: '{{parsed_dsv_traffic.message.IPProtocol}}'
          event.category: '{{parsed_dsv_traffic.message.Type | lower}}'
          action.type: '{{parsed_dsv_traffic.message.Threat_ContentType}}'
          action.name: '{{parsed_dsv_traffic.message.Action}}'
          event.duration: '{{parsed_dsv_traffic.message.ElapsedTimeInSec}}'
          user.name: '{{parsed_dsv_traffic.message.SourceUser}}'
          source.ip: '{{parsed_dsv_traffic.message.SourceAddress}}'
          destination.ip: '{{parsed_dsv_traffic.message.DestinationAddress}}'
      - set:
          action.outcome: "success"
        filter: '{{parsed_dsv_traffic.message.Action != null}}'

  field_extraction_userid:
    actions:
      - set:
          destination.port: '{{parsed_dsv_userid.message.DestinationPort}}'
          source.address: '{{parsed_dsv_userid.message.SourceIP}}'
          source.port: '{{parsed_dsv_userid.message.SourcePort}}'
          event.category: '{{parsed_dsv_userid.message.Type | lower}}'
          action.type: '{{parsed_dsv_userid.message.Threat_ContentType}}'
          log.logger: '{{parsed_dsv_userid.message.DataSourceName}}'
          log.hostname: '{{parsed_dsv_userid.message.DeviceName}}'
          source.ip: '{{parsed_dsv_userid.message.SourceIP}}'
          user.name: '{{parsed_dsv_userid.message.User}}'

  field_extraction_globalprotect:
    actions:
      - set:
          source.address: '{{parsed_dsv_globalprotect.message.PublicIP}}'
          event.category: '{{parsed_dsv_globalprotect.message.Type | lower}}'
          action.type: '{{parsed_dsv_globalprotect.message.Threat_ContentType}}'
          action.outcome: '{{parsed_dsv_globalprotect.message.Status}}'
          user.name: '{{parsed_dsv_globalprotect.message.SourceUser}}'
          action.outcome_reason: '{{parsed_dsv_globalprotect.message.Description}}'
          user_agent.os.name: '{{parsed_dsv_globalprotect.message.ClientOS}}'
          user_agent.os.version: '{{parsed_dsv_globalprotect.message.ClientOSVersion}}'
          geo.country_iso_code: '{{parsed_dsv_globalprotect.message.SourceRegion}}'
          source.ip: '{{parsed_dsv_globalprotect.message.PublicIP}}'

  field_extraction_system:
    actions:
      - set:
          event.category: '{{parsed_dsv_system.message.Type | lower}}'
          action.type: '{{parsed_dsv_system.message.Threat_ContentType}}'
          action.outcome_reason: '{{parsed_dsv_system.message.Description}}'
          log.hostname: '{{parsed_dsv_system.message.DeviceName}}'
          log.level: '{{parsed_dsv_system.message.Severity}}'

  field_extraction_threat:
    actions:
      - set:
          destination.address: '{{parsed_dsv_threat.message.DestinationAddress}}'
          destination.port: '{{parsed_dsv_threat.message.DestinationPort}}'
          destination.nat.ip: '{{parsed_dsv_threat.message.NATDestinationIP}}'
          destination.nat.port: '{{parsed_dsv_threat.message.NATDestinationPort}}'
          source.address: '{{parsed_dsv_threat.message.SourceAddress}}'
          source.port: '{{parsed_dsv_threat.message.SourcePort}}'
          source.nat.ip: '{{parsed_dsv_threat.message.NATSourceIP}}'
          source.nat.port: '{{parsed_dsv_threat.message.NATSourcePort}}'
          network.transport: '{{parsed_dsv_threat.message.IPProtocol}}'
          event.category: '{{parsed_dsv_threat.message.Type | lower}}'
          action.type: '{{parsed_dsv_threat.message.Threat_ContentType}}'
          action.name: '{{parsed_dsv_threat.message.Action}}'
          user.name: '{{parsed_dsv_threat.message.SourceUser}}'
          log.hostname: '{{parsed_dsv_threat.message.DeviceName}}'
          log.level: '{{parsed_dsv_threat.message.Severity}}'
          file.path: '{{parsed_dsv_threat.message.URLFilename}}'
          event.reason: '{{parsed_dsv_threat.message.Threat_ContentName}}'
          paloalto.content_type: '{{parsed_dsv_threat.message.ContentType}}'
          user_agent.name: '{{parsed_dsv_threat.message.UserAgent}}'
          http.request.method: '{{parsed_dsv_threat.message.HttpMethod}}'
          http.request.referrer: '{{parsed_dsv_threat.message.Referer}}'
          email.subject: '{{parsed_dsv_threat.message.Subject}}'
          email.from.address: '{{parsed_dsv_threat.message.Sender}}'
          email.to.address: '{{parsed_dsv_threat.message.Recipient}}'
          event.action: '{{parsed_dsv_threat.message.Threat_Category}}'
          source.ip: '{{parsed_dsv_threat.message.SourceAddress}}'
          destination.ip: '{{parsed_dsv_threat.message.DestinationAddress}}'
      - set:
          action.outcome: "success"
        filter: '{{parsed_dsv_threat.message.Action != null}}'

