name: usta-atp
ignored_values: []
pipeline:
  - name: parse_event
    description: 'Parse received message'
    filter: ''
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: message
  - name: set_atp_fields
    description: 'Extract USTA-ATP fields'
    filter: ''
    external: null
stages:
  set_atp_fields:
    actions:
      - set:
          event.kind: alert
          event.type:
            - indicator
            - info
          event.outcome: success
          event.category:
            - threat
            - iam
          observer.vendor: PRODAFT
          observer.product: USTA
        filter: ''
        name: set
      - set:
          prodaft.usta.atp.event.id: '{{parse_event.message.id}}'
          prodaft.usta.atp.source: '{{parse_event.message.content.source}}'
          prodaft.usta.atp.iscorporate: '{{parse_event.message.content.is_corporate}}'
          prodaft.usta.atp.url: '{{parse_event.message.content.url}}'
          prodaft.usta.atp.password: '{{parse_event.message.content.password}}'
          prodaft.usta.atp.username: '{{parse_event.message.content.username}}'
          prodaft.usta.atp.victimdetails.malware: '{{parse_event.message.content.victim_detail.malware}}'
          prodaft.usta.atp.victimdetails.computername: '{{parse_event.message.content.victim_detail.computer_name}}'
          prodaft.usta.atp.victimdetails.computerusername: '{{parse_event.message.content.victim_detail.username}}'
          prodaft.usta.atp.victimdetails.infectiondate: '{{parse_event.message.content.victim_detail.infection_date}}'
          prodaft.usta.atp.victimdetails.phonenumber: '{{parse_event.message.content.victim_detail.phone_number}}'
          prodaft.usta.atp.victimdetails.os: '{{parse_event.message.content.victim_detail.os}}'
          prodaft.usta.atp.victimdetails.memory: '{{parse_event.message.content.victim_detail.memory}}'
          prodaft.usta.atp.victimdetails.cpu: '{{parse_event.message.content.victim_detail.cpu}}'
          prodaft.usta.atp.victimdetails.gpu: '{{parse_event.message.content.victim_detail.gpu}}'
          prodaft.usta.atp.victimdetails.ipaddress: '{{parse_event.message.content.victim_detail.ip}}'
          prodaft.usta.atp.victimdetails.language: '{{parse_event.message.content.victim_detail.language}}'
          prodaft.usta.atp.victimdetails.country: '{{parse_event.message.content.victim_detail.country}}'
        filter: '{{parse_event.message.content != null}}'
        name: set
