name: microsoft-intune
pipeline:
  - name: json_event
    external:
      name: json.parse-json
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: "{{json_event.message.time}}"
        output_field: datetime
  - name: set_common_fields

stages:
  set_common_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_date.datetime}}"
          event.reason: "{{json_event.message.properties.Description}}"
          action.name: "{{json_event.message.operationName}}"
          action.target: "user"
          action.type: "{{json_event.message.category}}"
          event.type: ["info"]
          host.id: "{{json_event.message.properties.DeviceId}}"

      - set:
          host.mac: ["{{json_event.message.properties.WifiMacAddress}}"]
        filter: "{{json_event.message.properties.WifiMacAddress != null}}"
      - set:
          host.name: "{{json_event.message.properties.ManagedDeviceName or json_event.message.properties.DeviceHostName }}"
          host.type: "{{json_event.message.properties.Model}}"
          microsoft.intune.compliant_state: "{{json_event.message.properties.CompliantState}}"
          network.application: "{{json_event.message.ApplicationName}}"
          host.os.full: "{{json_event.message.properties.OS}}"
          host.os.version: "{{json_event.message.properties.OSVersion}}"
          service.name: "{{json_event.message.properties.ManagedBy}}"

      - set:
          source.ip: "{{json_event.message.actor.ipAddress}}"
        filter: "{{json_event.message.actor.ipAddress | is_ipaddress}}"

      - set:
          source.mac: "{{json_event.message.properties.WifiMacAddress}}"
          user.email: "{{json_event.message.properties.UserEmail}}"
          user.id: "{{json_event.message.properties.IntuneAccountId}}"
          user.name: "{{json_event.message.properties.UserName or json_event.message.properties.Actor.UPN}}"
          user.roles: "{{json_event.message.properties.Actor.UserPermissions}}"
