name: message-trace-graph-api
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"

  - name: extract_fields

stages:
  extract_fields:
    actions:
      - set:
          event.category: ["email"]
          event.type: ["info"]
          event.action: "{{json_event.message.status}}"

      - set:
          "@timestamp": "{{json_event.message.receivedDateTime}}"
          email.message_id: "{{json_event.message.messageId}}"
          email.from.address: ["{{json_event.message.senderAddress}}"]
          email.to.address: ["{{json_event.message.recipientAddress}}"]
          email.subject: "{{json_event.message.subject}}"

          network.bytes: "{{json_event.message.size}}"

      - set:
          source.ip: "{{json_event.message.fromIP}}"
        filter: "{{json_event.message.fromIP | is_ipaddress}}"

      - set:
          destination.ip: "{{json_event.message.toIP}}"
        filter: "{{json_event.message.toIP | is_ipaddress}}"
