name: microsoft-sentinel
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message
  - name: read_event_date
    external:
      name: date.parse
      properties:
        input_field: "{{json_event.message.alertTime}}"
        output_field: datetime
  - name: set-common-fields
  - name: set-sentinel-fields

stages:
  set-common-fields:
    actions:
      - set:
          "@timestamp": "{{read_event_date.datetime}}"
          event.kind: "{{json_event.message.alertKind}}"
          event.reason: "{{json_event.message.alertDescription}}"
          observer.product: "{{ json_event.message.productName}}"
          observer.vendor: "{{ json_event.message.vendorName}}"
  set-sentinel-fields:
    actions:
      - set:
          sentinel.alert.severity: "{{json_event.message.severity}}"
          sentinel.alert.system_id: "{{json_event.message.systemAlertId}}"
          sentinel.alert.type: "{{json_event.message.alertType}}"
          sentinel.alert.description: "{{json_event.message.alertDescription}}"
          sentinel.alert.provider_id: "{{json_event.message.providerAlertId}}"
          sentinel.alert.display_name: "{{json_event.message.alertDisplayName}}"
          sentinel.incident.id: "{{json_event.message.incidentNumber}}"
          sentinel.incident.url: "{{json_event.message.incidentUrl}}"
          sentinel.incident.description: "{{json_event.message.incidentDescription}}"
