name: FortiWeb
pipeline:
  - name: parsed_event
    external:
      name: kv.parse-kv

  - name: set_fields

stages:
  set_fields:
    actions:
      - set:
          action.outcome: "{{parsed_event.message.status}}"
          action.outcome_reason: "{{parsed_event.message.reason}}"
          action.properties.device_id: "{{parsed_event.message.device_id}}"
          action.properties.log_id: "{{parsed_event.message.log_id}}"
          action.properties.cat: "{{parsed_event.message.cat}}"
          destination.ip: "{{parsed_event.message.dst}}"
          destination.port: "{{parsed_event.message.dst_port}}"
          event.action: "{{parsed_event.message.action}}"
          event.category: "{{parsed_event.message.subtype}}"
          event.kind: "{{parsed_event.message.type}}"
          event.message: "{{parsed_event.message.msg}}"
          event.reason: "{{parsed_event.message.trigger_policy}}"
          http.request.bytes: "{{parsed_event.message.http_request_bytes}}"
          http.request.method: "{{parsed_event.message.http_method}}"
          http.request.referrer: "{{parsed_event.message.http_refer}}"
          http.response.bytes: "{{parsed_event.message.http_response_bytes}}"
          http.response.status_code: "{{parsed_event.message.http_retcode}}"
          http.version: "{{parsed_event.message.http_version}}"
          log.level: "{{parsed_event.message.pri}}"
          network.protocol: "{{parsed_event.message.proto}}"
          rule.ruleset: "{{parsed_event.message.policy}}"
          source.geo.name: "{{parsed_event.message.srccountry}}"
          source.ip: "{{parsed_event.message.src or parsed_event.message.src_ip}}"
          source.port: "{{parsed_event.message.src_port}}"
          tls.cipher: "{{parsed_event.message.cipher_suite}}"
          url.domain: "{{parsed_event.message.http_host}}"
          url.path: "{{parsed_event.message.http_url}}"
          url.username: "{{parsed_event.message.user_name}}"
          user.name: "{{parsed_event.message.user or parsed_event.message.user_name}}"
          user_agent.original: "{{parsed_event.message.http_agent}}"
          user.id: "{{parsed_event.message.user_id}}"

      - set:
          user.name: "{{parsed_event.message.user_name.split('@')[0]}}"
          user.domain: "{{parsed_event.message.user_name.split('@')[1]}}"
          user.email: "{{parsed_event.message.user_name}}"
        filter: "{{parsed_event.message.user_name != None and '@' in parsed_event.message.user_name}}"
