name: radware-defensepro
ignored_values: []
pipeline:
  - name: parsing
    description: Grok matching for Radware patterns
    external:
      name: grok.match
      properties:
        input_field: '{{original.message}}'
        output_field: message
        pattern: '%{RADWARE_ATTACK}|%{RADWARE_BDOS}|%{RADWARE_LOGIN}'
        custom_patterns:
          RADWARE_ATTACK: >-
            %{GREEDYDATA:date}
            %{WORD:DefensePro_severity} %{INT:Radware_id}
            %{DATA:DefensePro_category} "%{DATA:Radware_attack_name}"
            %{WORD:Radware_protocol} %{IP:source_ip} %{INT:source_port}
            %{IP:destination_ip} %{INT:destination_port}
            %{INT:DefensePro_physical_port} %{DATA:Radware_context}
            "%{DATA:DefensePro_policy_name}" %{DATA:DefensePro_attack_status}
            %{INT:DefensePro_packet_count} %{INT:DefensePro_volume}
            %{DATA:DefensePro_VLAN_tag} %{DATA:DefensePro_MPLS_RD}
            %{DATA:DefensePro_MPLS_tag} %{WORD:DefensePro_risk}
            %{DATA:DefensePro_action_name} %{DATA:DefensePro_UniqueID}
          RADWARE_BDOS: >-
            %{GREEDYDATA:date}
            %{WORD:DefensePro_severity} BDoS baseline learning is
            %{DATA:DefensePro_baseline_status} on inbound IPv4 traffic for
            policy "%{DATA:DefensePro_policy_name}".
          RADWARE_LOGIN: >-
            %{GREEDYDATA:date}
            %{WORD:DefensePro_severity} User radware (logged in|successfully
            authenticated) via (%{DATA:login_type}
            %{IP:login_ip}|%{DATA:login_type} \(IP:%{IP:login_ip}\))
  - name: parsing_date
    description: Grok date pattern
    external:
      name: date.parse
      properties:
        input_field: '{{parsing.message.date}}'
        output_field: datetime
        format: '%d-%m-%Y %H:%M:%S'
        timezone: UTC+1
  - name: fields
    description: Set parsed fields
stages:
  fields:
    actions:
      - set:
          '@timestamp': '{{parsing_date.datetime}}'
          radware.defensepro.login.ip: '{{parsing.message.login_ip}}'
          event.code: '{{parsing.message.Radware_id}}'
          radware.defensepro.login.type: '{{parsing.message.login_type}}'
          action.name: '{{parsing.message.DefensePro_action_name}}'
          source.port: '{{parsing.message.source_port}}'
          source.ip: '{{parsing.message.source_ip}}'
          host.risk.calculated_level: '{{parsing.message.DefensePro_risk}}'
          radware.defensepro.context: '{{parsing.message.Radware_context}}'
          destination.port: '{{parsing.message.destination_port}}'
          network.protocol: '{{parsing.message.Radware_protocol}}'
          radware.defensepro.volume: '{{parsing.message.DefensePro_volume}}'
          radware.defensepro.MPLS.RD: '{{parsing.message.DefensePro_MPLS_RD}}'
          radware.defensepro.MPLS.tag: '{{parsing.message.DefensePro_MPLS_tag}}'
          radware.defensepro.VLAN.tag: '{{parsing.message.DefensePro_VLAN_tag}}'
          radware.defensepro.category: '{{parsing.message.DefensePro_category}}'
          radware.defensepro.UniqueID: '{{parsing.message.DefensePro_UniqueID}}'
          radware.defensepro.attack.name: '{{parsing.message.Radware_attack_name}}'
          destination.ip: '{{parsing.message.destination_ip}}'
          radware.defensepro.policy.name: '{{parsing.message.DefensePro_policy_name}}'
          network.packets: '{{parsing.message.DefensePro_packet_count}}'
          radware.defensepro.attack.status: '{{parsing.message.DefensePro_attack_status}}'
          radware.defensepro.physical.port: '{{parsing.message.DefensePro_physical_port}}'
          log.level: '{{parsing.message.DefensePro_severity}}'
          radware.defensepro.baseline.status: '{{parsing.message.DefensePro_baseline_status}}'
        name: set