name: radware-defensepro
ignored_values: []
pipeline:
  - name: parsing
    description: Grok matching for Radware patterns
    external:
      name: grok.match
      properties:
        input_field: '{{original.message}}'
        output_field: message
        pattern: '%{RADWARE_ATTACK}|%{RADWARE_BDOS}|%{RADWARE_LOGIN}'
        custom_patterns:
          RADWARE_ATTACK: >-
            %{DATA:DefensePro_date} %{DATA:DefensePro_time}
            %{WORD:DefensePro_severity} %{INT:Radware_id}
            %{DATA:DefensePro_category} "%{DATA:Radware_attack_name}"
            %{WORD:Radware_protocol} %{IP:source_ip} %{INT:source_port}
            %{IP:destination_ip} %{INT:destination_port}
            %{INT:DefensePro_physical_port} %{DATA:Radware_context}
            "%{DATA:DefensePro_policy_name}" %{DATA:DefensePro_attack_status}
            %{INT:DefensePro_packet_count} %{INT:DefensePro_volume}
            %{DATA:DefensePro_VLAN_tag} %{DATA:DefensePro_MPLS_RD}
            %{DATA:DefensePro_MPLS_tag} %{WORD:DefensePro_risk}
            %{DATA:DefensePro_action_name} %{DATA:DefensePro_UniqueID}
          RADWARE_BDOS: >-
            %{DATA:DefensePro_date} %{DATA:DefensePro_time}
            %{WORD:DefensePro_severity} BDoS baseline learning is
            %{DATA:DefensePro_baseline_status} on inbound IPv4 traffic for
            policy "%{DATA:DefensePro_policy_name}".
          RADWARE_LOGIN: >-
            %{DATA:DefensePro_date} %{DATA:DefensePro_time}
            %{WORD:DefensePro_severity} User radware (logged in|successfully
            authenticated) via (%{DATA:login_type}
            %{IP:login_ip}|%{DATA:login_type} \(IP:%{IP:login_ip}\))
  - name: fields
    description: Set parsed fields
stages:
  fields:
    actions:
      - set:
          login.ip: '{{stage1.message.login_ip}}'
          Radware.id: '{{stage1.message.Radware_id}}'
          login.type: '{{stage1.message.login_type}}'
          action.name: '{{stage1.message.DefensePro_action_name}}'
          source.port: '{{stage1.message.source_port}}'
          source.address: '{{stage1.message.source_ip}}'
          DefensePro.date: '{{stage1.message.DefensePro_date}}'
          DefensePro.risk: '{{stage1.message.DefensePro_risk}}'
          DefensePro.time: '{{stage1.message.DefensePro_time}}'
          Radware.context: '{{stage1.message.Radware_context}}'
          destination.port: '{{stage1.message.destination_port}}'
          network.protocol: '{{stage1.message.Radware_protocol}}'
          DefensePro.volume: '{{stage1.message.DefensePro_volume}}'
          DefensePro.MPLS.RD: '{{stage1.message.DefensePro_MPLS_RD}}'
          DefensePro.MPLS.tag: '{{stage1.message.DefensePro_MPLS_tag}}'
          DefensePro.VLAN.tag: '{{stage1.message.DefensePro_VLAN_tag}}'
          DefensePro.category: '{{stage1.message.DefensePro_category}}'
          DefensePro.UniqueID: '{{stage1.message.DefensePro_UniqueID}}'
          Radware.attack.name: '{{stage1.message.Radware_attack_name}}'
          destination.address: '{{stage1.message.destination_ip}}'
          DefensePro.policy.name: '{{stage1.message.DefensePro_policy_name}}'
          DefensePro.packet.count: '{{stage1.message.DefensePro_packet_count}}'
          DefensePro.attack.status: '{{stage1.message.DefensePro_attack_status}}'
          DefensePro.physical.port: '{{stage1.message.DefensePro_physical_port}}'
          log.syslog.severity.name: '{{stage1.message.DefensePro_severity}}'
          DefensePro.baseline.status: '{{stage1.message.DefensePro_baseline_status}}'
        name: set