name: one-identity
ignored_values: []
pipeline:
  - name: parse_cef
    external:
      name: cef.parse-cef
  - name: set_fields
stages:
  set_fields:
    actions:
      - set:
          "@timestamp": "{{parse_cef.start | to_rfc3339}}"
      - set:
          host.ip: "{{parse_cef.message.dvc}}"
          source.ip: "{{parse_cef.message.src}}"
          source.port: "{{parse_cef.message.spt}}"
          event.action: "{{parse_cef.message.Name}}"
          action.outcome: "{{parse_cef.message.Verdict}}"
          destination.ip: "{{parse_cef.message.dst}}"
          host.name: "{{parse_grok.message.host}}"
          destination.port: "{{parse_cef.message.dpt}}"
          network.protocol: "{{parse_cef.message.app}}"
          observer.product: "{{parse_cef.message.DeviceProduct}}"
          observer.version: "{{parse_cef.message.DeviceVersion}}"
          source.user.name: "{{parse_cef.message.suser}}"
          process.command_line: "{{parse_cef.message.Command}}"
          destination.user.name: "{{parse_cef.message.duser}}"
          oneidentity.session.id: '{{parse_cef.message["Session ID"]}}'
          destination.domain: "{{parse_cef.message.dhost}}"
          source.domain: "{{parse_cef.message.shost}}"
      - set:
          file.path: "{{parse_cef.message.filePath}}"
          action.name: "{{parse_cef.message.act}}"
        filter: '{{parse_cef.message.Name == "FileTransfer"}}'
      - set:
          oneidentity.window.title: "{{parse_cef.message.cs2}}"
        filter: '{{parse_cef.message.cs2Label == "Window title"}}'
      - set:
          event.reason: "{{parse_cef.message.reason}}"
        filter: '{{parse_cef.message.Name == "ChannelAlert"}}'
