name: pradeo
pipeline:
  - name: parse_json
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message.split(": ")[1]}}'
        output_field: result
  - name: stage2
    external: null
stages:
  stage2:
    actions:
      - set:
          user.name: '{{parse_json.result.USER}}'
          action.type: '{{parse_json.result.ACTION_VALUES.ACTION}}'
          action.name: '{{parse_json.result.ACTION}}'
        name: set
      - set:
          package.checksum: '{{parse_json.result.ITEM.APP_SHA1_SIG}}'
          package.version: '{{parse_json.result.ITEM.APP_VERSION}}'
          package.name: '{{parse_json.result.ITEM.APP_PKG_NAME}}'
        name: set
      - set:
          pradeo.allowed: '{{parse_json.result.ACTION_VALUES.ALLOWED}}'
          pradeo.policy: '{{parse_json.result.ACTION_VALUES.POLICY}}'
          pradeo.match_threats: '{{parse_json.result.ACTION_VALUES.MATCH_THREATS}}'
        name: set
