name: azure-network-watcher
pipeline:
  - name: json_event
    external:
      name: json.parse-json

  - name: parsed_flow_0
    filter: "{{json_event.message.get('flow.0') != None}}"
    external:
      name: grok.match
      properties:
        input_field: "{{json_event.message.get('flow.0')}}"
        output_field: result
        pattern: "%{NUMBER:timestamp},%{IP:source_ip},%{IP:destination_ip},%{NUMBER:source_port},%{NUMBER:destination_port},%{PROTOCOL:protocol},%{TRAFFICFLOW:traffic_flow},%{TRAFFICDECISION:traffic_decision}(|,(%{FLOWSTATE:flow_state}|),(%{INT:source_packets}|),(%{INT:source_bytes}|),(%{INT:destination_packets}|),(%{INT:destination_bytes}|))"
        custom_patterns:
          "PROTOCOL": "T|U"
          "TRAFFICFLOW": "I|O"
          "TRAFFICDECISION": "A|D"
          "FLOWSTATE": "B|C|E"

  - name: set_common_fields
  - name: set_network_fields
  - name: set_source_fields
  - name: set_destination_fields

stages:
  set_source_fields:
    actions:
      - set:
          source.ip: "{{json_event.message.source_addr or parsed_flow_0.result.source_ip}}"
          source.port: "{{json_event.message.source_port or parsed_flow_0.result.source_port}}"
          source.packets: "{{parsed_flow_0.result.source_packets}}"
          source.bytes: "{{parsed_flow_0.result.source_bytes}}"
          source.mac: "{{json_event.message.macAddress}}"

  set_destination_fields:
    actions:
      - set:
          destination.ip: "{{json_event.message.destination_addr or parsed_flow_0.result.destination_ip}}"
          destination.port: "{{json_event.message.destination_port or parsed_flow_0.result.destination_port}}"
          destination.packets: "{{parsed_flow_0.result.destination_packets}}"
          destination.bytes: "{{parsed_flow_0.result.destination_bytes}}"

  set_network_fields:
    actions:
      - translate:
        dictionary:
          "T": "tcp"
        mapping:
          parsed_flow_0.result.protocol: network.transport
        fallback: "udp"

      - translate:
        dictionary:
          "begin": "inbound"
          "end": "outbound"
        mapping:
          json_event.message.flow_state: network.direction
        fallback: "{{json_event.message.traffic_flow}}"
        filter: "{{json_event.message.flow_state != null}}"

      - translate:
        dictionary:
          "B": "inbound"
          "E": "outbound"
        mapping:
          parsed_flow_0.result.flow_state: network.direction
        filter: "{{json_event.message.flow_state == null}}"

  set_common_fields:
    actions:
      - set:
          event.category: ["network"]
          event.code: "{{json_event.message.operationName}}"
          "@timestamp": "{{json_event.message.flowtime}}"

          rule.name: "{{json_event.message.rule}}"

          action.type: "{{json_event.message.rule}}"
          action.target: "network-traffic"
          action.properties: >
            [
              {
                {% if json_event.message.get("operationName") != None %}
                'OperationName': '{{json_event.message.operationName}}',
                {% endif %}
                {% if json_event.message.get("flow_state") != None %}
                'FlowState': '{{json_event.message.flow_state}}',
                {% elif parsed_flow_0.result.flow_state == "B" %}
                'FlowState': 'begin',
                {% elif parsed_flow_0.result.flow_state == "E" %}
                'FlowState': 'end',
                {% elif parsed_flow_0.result.flow_state == "C" %}
                'FlowState': 'continue',
                {% endif %}
                {% if json_event.message.get("version") != None %}
                'Version': '{{json_event.message.version}}',
                {% endif %}
              }
            ]

          host.name: "{{json_event.message.resourceId}}"

      - translate:
        dictionary:
          "A": "accept"
        mapping:
          parsed_flow_0.result.traffic_decision: event.action
        fallback: "reject"

      - translate:
        dictionary:
          "A": "accept"
        mapping:
          parsed_flow_0.result.traffic_decision: action.name
        fallback: "reject"

      - translate:
        dictionary:
          "A": ["allowed"]
        mapping:
          parsed_flow_0.result.traffic_decision: event.type
        fallback: ["denied"]
