name: Generate Intakes list

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop

jobs:
  generate-intakes-list:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out the repo under $GITHUB_WORKSPACE
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - id: list-intakes
        name: List intakes
        run: |
          echo "intakes=$(find . -maxdepth 2 -type d ! -name '.*' ! -path './.git*' ! -path './utils*' ! -name '_meta' | awk -F/ 'NF == 3 && $2 {print $2 "/" $3}' | sort | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: my-app-install token
        id: my-app
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.PRIVATE_DISPATCH_APP_ID }}
          private_key: ${{ secrets.PRIVATE_DISPATCH_APP_SECRET_KEY }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.my-app.outputs.token }}
          event-type: refresh-intake-formats-list
          repository: SekoiaLab/platform
          client-payload: '{"intakes": ${{ env.intakes }}}'
