name: Trigger a documentation rebuild

on:
  push:
    branches:
      - main
      - develop

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: my-app-install token
        id: my-app
        uses: getsentry/action-github-app-token@d4b5da6c5e37703f8c3b3e43abb5705b46e159cc # v3.0.0
        with:
          app_id: ${{ secrets.DISPATCH_APP_ID }}
          private_key: ${{ secrets.DISPATCH_APP_SECRET_KEY }}

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@28959ce8df70de7be546dd1250a005dd32156697 # v4.0.1
        with:
          token: ${{ steps.my-app.outputs.token }}
          event-type: rebuild-intake-documentation
          repository: SEKOIA-IO/documentation/
