name: Comment with Checks results

on:
  workflow_run:
    workflows: ["Check intakes"]
    types:
      - completed

permissions: {}

jobs:
  comment_prs:
    permissions:
      actions: read  # for actions/download-artifact to download artifacts from other workflow runs
      issues: write  # for peter-evans/create-or-update-comment to create or update comment
      pull-requests: write  # for peter-evans/create-or-update-comment to create or update comment
    runs-on: ubuntu-latest
    # Only run this job if the workflow run was "Check intakes" that failed
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          name: pr_comment.md
          github-token: ${{ github.token }}
          run-id: ${{ github.event.workflow_run.id }}

      - name: Find Comment
        uses: peter-evans/find-comment@b30e6a3c0ed37e7c023ccd3f1db5c6c0b0c23aad # v4.0.0
        id: find-comment
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          comment-author: github-actions[bot]
          body-includes: Intake Format Checks Failed

      - name: Comment on PR with Analysis
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
        with:
          issue-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          body-path: pr_comment.md
          comment-id: ${{ steps.find-comment.outputs.comment-id }}
          edit-mode: replace
