name: aioniq
pipeline:
  - name: json_load
    external:
      name: json.parse-json
  - name: parsed_date
    external:
      name: date.parse
      properties:
        input_field: "{{json_load.message.timestamp_analyzed}}"
        output_field: datetime
  - name: common
  - name: malcore
    filter: '{{json_load.message.type == "malcore"}}'
  - name: suricata
    filter: '{{json_load.message.type == "suricata"}}'

stages:
  common:
    actions:
      - set:
          source.ip: "{{json_load.message.src_ip}}"
        filter: "{{json_load.message.src_ip | is_ipaddress}}"

      - set:
          destination.ip: "{{json_load.message.dest_ip}}"
        filter: "{{json_load.message.dest_ip | is_ipaddress}}"

      - set:
          "@timestamp": "{{parsed_date.datetime}}"
          source.port: "{{json_load.message.src_port}}"
          destination.port: "{{json_load.message.dest_port}}"
          observer.name: "{{json_load.message.gcap}}"
          observer.version: "0.2"
          observer.hostname: "{{json_load.message.host}}"
          observer.type: "firewall"
          network.transport: "{{json_load.message.proto}}"
          network.protocol: "{{json_load.message.app_proto}}"
          gatewatcher.type: "{{json_load.message.type}}"
          gatewatcher.state: "{{json_load.message.state}}"
          gatewatcher.gcenter: "{{json_load.message.gcenter}}"
          gatewatcher.gcap: "{{json_load.message.gcap}}"
          gatewatcher.flow_id: "{{json_load.message.flow_id}}"
          gatewatcher.timestamp_analyzed: "{{json_load.message.timestamp_analyzed}}"
          gatewatcher.timestamp_detected: "{{json_load.message.timestamp_detected}}"
          gatewatcher.event_type: "{{json_load.message.event_type}}"
          event.category: ["network"]
          event.type: ["info"]
          event.severity: "{{json_load.message.severity}}"
      - set:
          observer.mac: '["{{json_load.message.ether.src_mac}}", "{{json_load.message.ether.dest_mac}}"]'
        filter: "{{json_load.message.ether != null}}"
      - name: translate
        dictionary:
          alert: alert
        mapping:
          gatewatcher.event_type: event.kind
        fallback: event

  malcore:
    actions:
      - set:
          file.name: "{{json_load.message.fileinfo.filename}}"
          file.size: "{{json_load.message.fileinfo.size}}"
          file.hash.md5: "{{json_load.message.fileinfo.md5}}"
          file.hash.sha256: "{{json_load.message.fileinfo.sha256}}"
          url.path: "{{json_load.message.http.url}}"
          url.domain: "{{json_load.message.http.hostname}}"
          http.version: "{{json_load.message.http.version}}"
          http.request.method: "{{json_load.message.http.http_method}}"
          user_agent.original: "{{json_load.message.http.http_user_agent}}"
          http.response.status_code: "{{json_load.message.http.status}}"
          gatewatcher.retroact: "{{json_load.message.retroact}}"
          gatewatcher.nb_rescans: "{{json_load.message.nb_rescans}}"
          gatewatcher.malcore.code: "{{json_load.message.code|string}}"
          gatewatcher.malcore.file: "{{json_load.message.file}}"
          gatewatcher.malcore.magic: "{{json_load.message.magic}}"
          gatewatcher.malcore.replica: "{{json_load.message.replica}}"
          gatewatcher.reporting_token: "{{json_load.message.reporting_token}}"
          gatewatcher.malcore.detail_threat_found: "{{json_load.message.detail_threat_found}}"
          event.category: ["malware"]
          event.type: ["info"]

  suricata:
    actions:
      - set:
          source.bytes: "{{json_load.message.flow.bytes_toserver}}"
          source.packets: "{{json_load.message.flow.pkts_toserver}}"
          destination.bytes: "{{json_load.message.flow.bytes_toclient}}"
          destination.packets: "{{json_load.message.flow.pkts_toclient}}"
          url.path: "{{json_load.message.http.url}}"
          url.domain: "{{json_load.message.http.hostname}}"
          http.version: "{{json_load.message.http.version}}"
          http.request.method: "{{json_load.message.http.http_method}}"
          user_agent.original: "{{json_load.message.http.http_user_agent}}"
          http.response.status_code: "{{json_load.message.http.status}}"
          dns.id: "{{json_load.message.dns.id}}"
          dns.type: "{{json_load.message.dns.type}}"
          dns.question.name: "{{json_load.message.dns.rrname}}"
          dns.question.type: "{{json_load.message.dns.rrtype}}"
          rule.name: "{{json_load.message.alert.signature}}"
          rule.id: "{{json_load.message.alert.signature_id|string}}"
          rule.version: "{{json_load.message.alert.rule.version}}"
          rule.category: "{{json_load.message.alert.category}}"
          event.action: "{{json_load.message.alert.action}}"
          file.name: "{{json_load.message.fileinfo.filename}}"
          file.size: "{{json_load.message.fileinfo.size}}"
          file.hash.md5: "{{json_load.message.fileinfo.md5}}"
          file.hash.sha256: "{{json_load.message.fileinfo.sha256}}"
