name: SEKOIA.IO for Endpoints
pipeline:
  - name: json
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: event
  - name: fields
stages:
  fields:
    actions:
      - name: set
        set:
          '@timestamp': '{{json.event["@timestamp"]}}'
          action: '{{json.event.action}}'
          agent: '{{json.event.agent}}'
          destination: '{{json.event.destination}}'
          dll: '{{json.event.dll}}'
          dns: '{{json.event.dns}}'
          event.action: '{{json.event.event.action}}'
          event.category: '{{json.event.event.category}}'
          event.code: '{{json.event.event.code | string}}'
          event.kind: '{{json.event.event.kind}}'
          event.message: '{{json.event.event.message}}'
          event.provider: '{{json.event.event.provider}}'
          action.outcome: '{{json.event.event.outcome}}'
          file: '{{json.event.file}}'
          host: '{{json.event.host}}'
          network: '{{json.event.network}}'
          process: '{{json.event.process}}'
          registry: '{{json.event.registry}}'
          source: '{{json.event.source}}'
          url: '{{json.event.url}}'
          user: '{{json.event.user}}'
          sekoiaio.agent: '{{json.event.sekoiaio.agent}}'
          sekoiaio.host: '{{json.event.sekoiaio.host}}'
          sekoiaio.process: '{{json.event.sekoiaio.process}}'
          sekoiaio.source_process: '{{json.event.sekoiaio.source_process}}'
          sekoiaio.target_process: '{{json.event.sekoiaio.target_process}}'

      - set:
          # prevent event to contain 'type': ['null']
          event.type: ['{{json.event.event.type}}']
        filter: '{{json.event.event.type != null}}'
      - set:
          auditd.data.a1: '{{json.event.event.action.properties.a1}}'
          auditd.data.a2: '{{json.event.event.action.properties.a2}}'
          auditd.data.a3: '{{json.event.event.action.properties.a3}}'
          auditd.data.syscall: '{{json.event.event.action.properties.syscall}}'
          auditd.data.socket.family: '{{json.event.event.action.properties.socket_family}}'
          auditd.data.socket.addr: '{{json.event.event.action.properties.socket_addr}}'
          auditd.data.socket.port: '{{json.event.event.action.properties.socket_port}}'
