name: Cisco Secure Web Appliance
pipeline:
  - name: parsed_event
    external:
      name: grok.match
      properties:
        input_field: original.message
        output_field: message
        pattern: '%{PREFIX}%{NUMBER:timestamp}\s+%{NUMBER:elapsed}\s+%{IP:source_ip}\s+%{WORD:code}/%{NUMBER:status}\s+%{NUMBER:http_response_bytes}\s+%{WORD:method}\s+%{NOTSPACE:url}\s+%{NOTSPACE:username}\s+%{NOTSPACE:hierarchy_code}/(%{IP:peerhostip}|%{NOTSPACE:peerhost})\s+%{NOTSPACE:mime_type}\s+(%{NOTSPACE}:%{NUMBER}\s+)*%{NOTSPACE:acl_decision}\s+<%{VERDICT:scanning_verdict_information}>\s+%{NOTSPACE:user_agent}.*'
        custom_patterns:
          PREFIX: '(?:Info:\s+)*'
          VERDICT: "(?:[^>]+)"
  - name: parsed_files
    external:
      name: grok.match
      properties:
        input_field: original.message
        output_field: message
        pattern: 'Info: %{DATA:event_reason} (\(#counter_group: %{DATA:counter_group} #interval %{DATA:interval} #Serial number: %{GREEDYDATA:serial_number} #Time since data generated: %{NUMBER:last_gen})?(\(#files: %{DATA:file_name} %{DATA:interval} #files: %{INT:sightings} #rows: %{INT} #total rows %{INT}\) #duration\(s\): %{NUMBER:duration} #rate: %{DATA:rate})?'
  - name: parsed_timestamp
    external:
      name: date.parse
      properties:
        input_field: parsed_event.message.timestamp
        output_field: start_date
        format: timestamp
  - name: parsed_acl_decision
    filter: '{{ parsed_event.get("message").get("acl_decision") != None}}'
    external:
      name: grok.match
      properties:
        input_field: parsed_event.message.acl_decision
        output_field: result
        pattern: "%{WORD:decision_tag}-%{WORD:policy_group_name}-%{WORD:policy_identity}-%{WORD:outbound_malware_scanning_policy}-%{WORD:data_security_policy}-%{WORD:external_dlp_policy}-%{WORD:routing_policy}"
  - name: parsed_scanning_verdict
    filter: '{{ parsed_event.get("message") != None }}'
    external:
      name: dsv.parse-dsv
      properties:
        input_field: "{{parsed_event.message.scanning_verdict_information}}"
        output_field: results
        columnnames:
          - url_category
          - url_reputation_score
          - webroot_malware_category_code
          - webroot_malware_name
          - webroot_threat_risk_ratio
          - webroot_threat_id
          - webroot_trace_id
          - mcafee_malware_category_code
          - mcafee_file_name
          - mcafee_detection_error
          - mcafee_detection_type_code
          - mcafee_malware_type_code
          - mcafee_malware_name
          - sophos_malware_category_code
          - sophos_process_exit_code
          - sophos_file_name
          - sophos_malware_name
          - cisco_data_security_code
          - cisco_external_dlp_code
          - predefined_url_category
          - cisco_dca_url_category
          - malware_category
          - threat_type_code
          - application_name
          - application_type
          - application_behavior
          - safe_browsing_result
          - bandwidth_avg
          - bandwidth_was_throttled
          - user_type
          - malware_result
          - outbound_malware_scanning_threat_name
          - threat_category_code
          - threat_name
          - threat_score
          - analysis_is_required
          - file_name
          - file_sha256
          - file_reputation
          - archivescan_result
          - archivescan_detail
        delimiter: ","
  - name: set_ecs_fields
    filter: "{{parsed_event.message != None}}"
  - name: set_cisco_fields
    filter: "{{parsed_event.message != None }}"
  - name: set_file_fields
    filter: "{{parsed_files.message != None}}"
stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{parsed_timestamp.start_date}}"
          event.start: "{{parsed_timestamp.start_date}}"
          event.duration: "{{parsed_event.message.elapsed}}"
          event.category:
            - web
            - network
          observer.product: "Cisco Web Security Appliances"
          observer.type: proxy
          observer.vendor: Cisco
          network.direction: egress
          http.request.method: "{{parsed_event.message.method}}"
          http.response.status_code: "{{parsed_event.message.status}}"
          http.response.bytes: "{{parsed_event.message.http_response_bytes}}"
          url.original: "{{parsed_event.message.url}}"

      - set:
          rule.ruleset: '{{parsed_acl_decision.result.policy_identity | replace("_", " ")}}'
        filter: '{{parsed_acl_decision.get("result").get("policy_identity") != None}}'

      - set:
          rule.id: "{{parsed_acl_decision.result.decision_tag}}"
        filter: '{{parsed_acl_decision.get("result").get("decision_tag") != None}}'

      - set:
          user_agent.original: "{{parsed_event.message.useragent}}"
        filter: '{{parsed_event.message.useragent != "-"}}'

      - set:
          user.name: "{{parsed_event.message.username}}"
        filter: '{{parsed_event.message.username != "-"}}'

      - set:
          http.response.mime_type: "{{parsed_event.message.mime_type}}"
        filter: '{{parsed_event.message.mime_type != "-"}}'

      - set:
          source.ip: "{{parsed_event.message.source_ip}}"
        filter: "{{parsed_event.message.source_ip  | is_ipaddress}}"

      - set:
          network.transport: "tcp"
        filter: '{{parsed_event.message.code.startswith("TCP_") }}'

      - set:
          network.transport: "udp"
        filter: '{{parsed_event.message.code.startswith("UDP_") }}'

      - set:
          event.type:
            - connection
            - denied
        filter: '{{parsed_event.message.code.endswith("_DENIED")}}'

      - set:
          destination.domain: "{{parsed_event.message.peerhost}}"
        filter: '{{parsed_event.message.peerhost != "-"}}'

      - set:
          destination.ip: "{{parsed_event.message.peerhostip}}"
        filter: "{{parsed_event.message.peerhostip  | is_ipaddress}}"

      - set:
          file.name: "{{parsed_scanning_verdict.results.file_name}}"
        filter: '{{parsed_scanning_verdict.results.file_name != "-"}}'

      - set:
          file.hash.sha256: "{{parsed_scanning_verdict.results.file_sha256}}"
        filter: '{{parsed_scanning_verdict.results.file_sha256 != "-"}}'

  set_file_fields:
    actions:
      - set:
          event.category:
            - web
            - network
          event.reason: "{{parsed_files.message.event_reason}}"
          file.name: "{{parsed_files.message.file_name}}"
          observer.product: "Cisco Web Security Appliances"
          observer.type: proxy
          observer.vendor: Cisco
          network.direction: egress

  set_cisco_fields:
    actions:
      - set:
          cisco_wsa.hierarchy_code: "{{parsed_event.message.hierarchy_code}}"

      - set:
          cisco_wsa.rule.policy.name: "{{parsed_acl_decision.result.policy_group_name}}"
          cisco_wsa.rule.policy.outbound_malware_scanning: "{{parsed_acl_decision.result.outbound_malware_scanning_policy}}"
          cisco_wsa.rule.policy.data_security: "{{parsed_acl_decision.result.data_security_policy}}"
          cisco_wsa.rule.policy.external_dlp: "{{parsed_acl_decision.result.external_dlp_policy}}"
          cisco_wsa.rule.policy.routing: "{{parsed_acl_decision.result.routing_policy}}"
        filter: "{{parsed_acl_decision.result != None}}"

      - set:
          cisco_wsa.cache_status: hit
        filter: '{{parsed_event.message.code.endswith("_HIT")}}'

      - set:
          cisco_wsa.cache_status: miss
        filter: '{{parsed_event.message.code.endswith("_MISS")}}'

      - set:
          cisco_wsa.cache_status: denied
        filter: '{{parsed_event.message.code.endswith("_DENIED")}}'

      - set:
          cisco_wsa.url.category_code: "{{parsed_scanning_verdict.results.url_category}}"
        filter: '{{parsed_scanning_verdict.results.url_category != "nc"}}'

      - translate:
        dictionary:
          "IW_adlt": "Adult"
          "IW_adv": "Advertisements"
          "IW_alc": "Alcohol"
          "IW_art": "Arts"
          "IW_astr": "Astrology"
          "IW_auct": "Auctions"
          "IW_busi": "Business and Industry"
          "IW_chat": "Chat and Instant Messaging"
          "IW_plag": "Cheating and Plagiarism"
          "IW_cprn": "Child Abuse Content"
          "IW_csec": "Computer Security"
          "IW_comp": "Computers and Internet"
          "IW_date": "Dating"
          "IW_card": "Digital Postcards"
          "IW_food": "Dining and Drinking"
          "IW_dyn": "Dynamic and Residential"
          "IW_edu": "Education"
          "IW_ent": "Entertainment"
          "IW_extr": "Extreme"
          "IW_fash": "Fashion"
          "IW_fts": "File Transfer Services"
          "IW_filt": "Filter Avoidance"
          "IW_fnnc": "Finance"
          "IW_free": "Freeware and Shareware"
          "IW_gamb": "Gambling"
          "IW_game": "Games"
          "IW_gov": "Government and Law"
          "IW_hack": "Hacking"
          "IW_hate": "Hate Speech"
          "IW_hlth": "Health and Nutrition"
          "IW_lol": "Humor"
          "IW_ilac": "Illegal Activities"
          "IW_ildl": "Illegal Downloads"
          "IW_drug": "Illegal Drugs"
          "IW_infr": "Infrastructure and Content Delivery Networks"
          "IW_voip": "Internet Telephony"
          "IW_job": "Job Search"
          "IW_ling": "Lingerie and Swimsuits"
          "IW_lotr": "Lotteries"
          "IW_cell": "Mobile Phones"
          "IW_natr": "Nature"
          "IW_news": "News"
          "IW_ngo": "Non-Governmental Organizations"
          "IW_nsn": "Non-Sexual Nudity"
          "IW_comm": "Online Communities"
          "IW_osb": "Online Storage and Backup"
          "IW_trad": "Online Trading"
          "IW_pem": "Organizational Email"
          "IW_park": "Parked Domains"
          "IW_p2p": "Peer File Transfer"
          "IW_pers": "Personal Sites"
          "IW_img": "Photo Searches and Images"
          "IW_pol": "Politics"
          "IW_porn": "Pornography"
          "IW_pnet": "Professional Networking"
          "IW_rest": "Real Estate"
          "IW_ref": "Reference"
          "IW_rel": "Religion"
          "IW_saas": "B2B"
          "IW_kids": "Safe for Kids"
          "IW_sci": "Science and Technology"
          "IW_srch": "Search Engines and Portals"
          "IW_sxed": "Sex Education"
          "IW_shop": "Shopping"
          "IW_snet": "Social Networking"
          "IW_socs": "Social Science"
          "IW_scty": "Society and Culture"
          "IW_swup": "Software Updates"
          "IW_sprt": "Sports and Recreation"
          "IW_aud": "Streaming Audio"
          "IW_vid": "Streaming Video"
          "IW_tob": "Tobacco"
          "IW_trns": "Transportation"
          "IW_trvl": "Travel"
          "IW_weap": "Weapons"
          "IW_whst": "Web Hosting"
          "IW_tran": "Web Page Translation"
          "IW_mail": "Web-Based Email"
        mapping:
          cisco_wsa.url.category_code: cisco_wsa.url.category
        fallback: "Unclassified"
        filter: '{{parsed_scanning_verdict.results.url_category != "nc"}}'

      - set:
          cisco_wsa.threat.name: "{{parsed_scanning_verdict.results.threat_name}}"
        filter: '{{parsed_scanning_verdict.results.threat_name != "\"-\""}}'

      - set:
          cisco_wsa.threat.category_code: "{{parsed_scanning_verdict.results.threat_category_code}}"
        filter: '{{parsed_scanning_verdict.results.threat_category_code != "-"}}'

      - set:
          cisco_wsa.threat.reputation_score: "{{parsed_scanning_verdict.results.threat_score}}"
        filter: '{{parsed_scanning_verdict.results.threat_score != "-"}}'

      - translate:
        dictionary:
          0: "Unknown"
          1: "Not Scanned"
          2: "Timeout"
          3: "Error"
          4: "Unscannable"
          10: "Generic Spyware"
          12: "Browser Helper Object"
          13: "Adware"
          14: "System Monitor"
          18: "Commercial System Monitor"
          19: "Dialer"
          20: "Hijacker"
          21: "Phishing URL"
          22: "Trojan Downloader"
          23: "Trojan Horse"
          24: "Trojan Phisher"
          25: "Worm"
          26: "Encrypted File"
          27: "Virus"
          33: "Other Malware"
          34: "PUA"
          35: "Aborted"
          36: "Outbreak Heuristics"
          37: "Known Malicious and High-Risk Files"
        mapping:
          cisco_wsa.threat.category_code: cisco_wsa.threat.category
        fallback: "Not Set"
